(()=>{
const VER38='3.8';
const LOGIN38_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-login-v33';
const AUTH38_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-auth-v38';
const GROUP38_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-groups-v38';
let loginCandidates38=[],selectedLogin38=null,loginBusy38=false,loginIsDeveloper38=false;
let prefetch38=0,composing38=false;
const probeCache38=new Map();
let myMemberships38=[],membershipsReady38=false,membershipAt38=0,membershipBusy38=null,currentPinDefault38=null;

async function post38(url,body={},auth=false){
 const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(auth&&T?{authorization:'Bearer '+T}:{})},body:JSON.stringify(body),cache:'no-store'});
 const x=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(x.error||'요청 처리에 실패했습니다.');e.status=r.status;e.payload=x;throw e}return x;
}
async function probe38(name,force=false){const key=String(name||'').trim();if(!key)throw new Error('이름을 입력해주세요.');const c=probeCache38.get(key);if(!force&&c&&Date.now()-c.at<5000)return c.data;const data=await post38(LOGIN38_API,{action:'probe',name:key});probeCache38.set(key,{at:Date.now(),data});return data}
function info38(c){const year=c.year?`${esc(c.year)}년생`:'출생연도 미등록',gender=String(c.gender||'').trim(),cls=c.cls?`${esc(c.cls)}급`:'급수 미등록',role=esc(c.roleLabel||'회원');return[year,gender?esc(gender):'',cls,role].filter(Boolean).join(' · ')}
function candidate38(c,i){return `<button type="button" class="choiceBtn" onclick="chooseLogin38(${i})"><b>${esc(pendingLoginName)}</b><span>${info38(c)}</span><small>${esc(c.groupName||'모임')}</small></button>`}
window.renderLoginCandidates38=function(){if(!loginCandidates38.length)return renderLoginName();$('loginBox').innerHTML=`<h2>회원 선택</h2><div class="authName">${esc(pendingLoginName)}</div><div class="note">같은 이름 또는 여러 모임의 회원정보가 있습니다. 출생연도·성별·급수·역할·모임을 확인하고 본인을 선택해주세요.</div><div class="choiceList">${loginCandidates38.map(candidate38).join('')}</div><div id="loginErr" class="error"></div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="renderLoginName()">← 이름 다시 입력</button>`};
window.chooseLogin38=function(i){const c=loginCandidates38[Number(i)];if(!c)return;selectedLogin38=c;loginIsDeveloper38=false;renderLoginPin38()};
function renderLoginPin38(){const c=selectedLogin38||{},title=loginIsDeveloper38?'개발자 PIN':'모임 PIN';$('loginBox').innerHTML=`<h2>${title} 입력</h2><div class="loginMember33"><b>${esc(pendingLoginName)}</b>${loginIsDeveloper38?'<span>개발자</span>':`<span>${info38(c)}</span><small>${esc(c.groupName||'모임')}</small>`}</div><div class="note" style="margin-bottom:12px">${loginIsDeveloper38?'마지막으로 사용한 모임으로 자동 접속합니다.':'선택한 모임의 PIN을 입력해주세요.'}</div><div class="field"><label>${title}</label><input id="loginPin" type="password" inputmode="numeric" autocomplete="current-password" placeholder="${title} 입력"></div><button id="loginSubmit38" class="btn pri" style="width:100%" onclick="submitLogin()">로그인</button><div id="loginErr" class="error"></div><button class="btn ghost" style="width:100%;margin-top:8px" onclick="${!loginIsDeveloper38&&loginCandidates38.length>1?'renderLoginCandidates38()':'renderLoginName()'}">← ${!loginIsDeveloper38&&loginCandidates38.length>1?'회원 다시 선택':'이름 다시 입력'}</button>`;const p=$('loginPin');if(p){p.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing)submitLogin()});setTimeout(()=>p.focus(),20)}}
function scheduleProbe38(){clearTimeout(prefetch38);if(composing38)return;const name=$('loginName')?.value.trim()||'';if(name.length<2)return;prefetch38=setTimeout(()=>probe38(name).catch(()=>{}),180)}
renderLoginName=function(){loginCandidates38=[];selectedLogin38=null;loginIsDeveloper38=false;pendingLoginPin='';$('loginBox').innerHTML=`<h1>🏸 콕매치</h1><div class="meta" style="font-size:14px;margin-bottom:18px">모임 회원 로그인</div><div class="field"><label>등록된 이름</label><input id="loginName" autocomplete="username" placeholder="이름"></div><button id="loginNext38" class="btn pri" style="width:100%" onclick="startLogin()">다음</button><div id="loginErr" class="error"></div><div class="note" style="margin-top:12px">일반 회원은 본인 정보를 선택한 뒤 모임 PIN으로 로그인합니다. 개발자는 이름 확인 후 바로 개발자 PIN을 입력합니다.</div>`;const n=$('loginName');if(n){n.addEventListener('compositionstart',()=>composing38=true);n.addEventListener('compositionend',()=>{composing38=false;scheduleProbe38()});n.addEventListener('input',scheduleProbe38);n.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing)startLogin()});setTimeout(()=>n.focus(),20)}};
startLogin=async function(){if(loginBusy38)return;const name=$('loginName')?.value.trim()||'',err=$('loginErr'),btn=$('loginNext38');if(err)err.textContent='';if(!name){if(err)err.textContent='이름을 입력해주세요.';return}loginBusy38=true;if(btn){btn.disabled=true;btn.textContent='회원정보 확인 중...'}try{const x=await probe38(name);pendingLoginName=name;loginCandidates38=Array.isArray(x.memberships)?x.memberships.map(c=>({...c})):[];if(x.globalAdmin){loginIsDeveloper38=true;const last=localStorage.getItem(GROUP_KEY)||'';selectedLogin38=loginCandidates38.find(c=>c.groupId===last)||loginCandidates38[0]||{globalAdminOnly:true,groupId:last,memberId:'',groupName:''};renderLoginPin38();return}loginIsDeveloper38=false;if(loginCandidates38.length===1){selectedLogin38=loginCandidates38[0];renderLoginPin38()}else renderLoginCandidates38()}catch(e){if(err)err.textContent=e.message}finally{loginBusy38=false;if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent='다음'}}};
function initialPinAlert38(){alert('초기 비밀번호 000000을 사용 중입니다.\n\n보안을 위해 개인 비밀번호를 변경해주세요.\n변경 방법: 설정 → 개인 비밀번호 변경 → 현재 비밀번호(초기 000000) 입력 → 새 비밀번호 입력\n\n000000을 그대로 사용하면 로그인할 때마다 이 안내가 표시됩니다.')}
async function finalizeLogin38(x,c){T=x.token;localStorage.setItem(TOKEN_KEY,T);const gid=x.groupId||c?.groupId||'';if(gid){currentGroupId=gid;localStorage.setItem(GROUP_KEY,gid)}$('login').classList.add('hide');pendingLoginPin='';await loadState(true);await refreshMyMemberships38(true).catch(()=>{});const mine=me?.memberId?M(me.memberId):null;if(x.initialPinPending)setTimeout(initialPinAlert38,40);if(mine?.state==='out')setTimeout(()=>openEntry(),70)}
submitLogin=async function(){if(loginBusy38)return;const c=selectedLogin38||loginCandidates38[0]||{},pin=$('loginPin')?.value.trim()||pendingLoginPin,err=$('loginErr'),btn=$('loginSubmit38');if(!pin){if(err)err.textContent=loginIsDeveloper38?'개발자 PIN을 입력해주세요.':'모임 PIN을 입력해주세요.';return}pendingLoginPin=pin;loginBusy38=true;if(btn){btn.disabled=true;btn.textContent='로그인 중...'}try{const x=await post38(LOGIN38_API,{action:'login',name:pendingLoginName,pin,groupId:c.groupId||localStorage.getItem(GROUP_KEY)||'',memberId:loginIsDeveloper38?'':(c.memberId||'')});await finalizeLogin38(x,c)}catch(e){$('login')?.classList.remove('hide');if(err)err.textContent=e.message;else alert(e.message)}finally{loginBusy38=false;if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent='로그인'}}};

async function auth38(action,body={}){return post38(AUTH38_API,{action,...body},true)}
async function refreshMyMemberships38(force=false){if(!T||!me)return null;const now=Date.now();if(!force&&membershipsReady38&&now-membershipAt38<15000)return{memberships:myMemberships38,currentPinDefault:currentPinDefault38};if(membershipBusy38&&!force)return membershipBusy38;membershipBusy38=auth38('my_memberships',{currentGroupId}).then(x=>{myMemberships38=Array.isArray(x.memberships)?x.memberships:[];currentPinDefault38=typeof x.currentPinDefault==='boolean'?x.currentPinDefault:null;membershipsReady38=true;membershipAt38=Date.now();try{renderHeader()}catch{}if(currentView==='settings')try{renderSettings()}catch{}return x}).finally(()=>membershipBusy38=null);return membershipBusy38}
const loadStatePrev38=loadState;
loadState=async function(...args){const r=await loadStatePrev38(...args);if(T&&me)refreshMyMemberships38(false).catch(()=>{});return r};

function roleText38(m){return m.roleLabel||'회원'}
openGroupSwitch=function(){if(!membershipsReady38||myMemberships38.length<=1)return;openModal(`<h3>내 모임 선택</h3><div class="note">본인이 가입된 운영중 모임만 표시됩니다.</div><div class="choiceList">${myMemberships38.map(m=>`<button class="choiceBtn" ${m.groupId===currentGroupId?'disabled':''} onclick="switchOwnGroup38('${m.groupId}')"><b>${esc(m.groupName)}</b><span class="meta">${esc(roleText38(m))}${m.groupId===currentGroupId?' · 현재 모임':''}</span></button>`).join('')}</div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="closeModal()">취소</button>`)};
window.switchOwnGroup38=async function(id){if(!id||id===currentGroupId){closeModal();return}try{const x=await auth38('switch_group',{groupId:id});if(x.token){T=x.token;localStorage.setItem(TOKEN_KEY,T)}currentGroupId=x.groupId||id;localStorage.setItem(GROUP_KEY,currentGroupId);membershipsReady38=false;closeModal();await loadState(true);await refreshMyMemberships38(true);if(currentView==='members'&&typeof window.memberPageGo46==='function')window.memberPageGo46(1);window.scrollTo(0,0)}catch(e){showError(e);refreshMyMemberships38(true).catch(()=>{})}};
window.adminSwitchGroup38=async function(id,view='members'){if(!me?.globalAdmin)return switchOwnGroup38(id);currentGroupId=id;localStorage.setItem(GROUP_KEY,id);closeModal();try{await loadState(true);membershipsReady38=false;await refreshMyMemberships38(true).catch(()=>{});if(view==='members'&&typeof window.memberPageGo46==='function')window.memberPageGo46(1);goView(view)}catch(e){showError(e)}};
switchGroup=function(id,view='members'){return me?.globalAdmin?adminSwitchGroup38(id,view):switchOwnGroup38(id)};
const renderHeaderPrev38=renderHeader;
renderHeader=function(){const r=renderHeaderPrev38();const b=$('groupBtn');if(!b)return r;const selectable=membershipsReady38&&myMemberships38.length>1;b.textContent=(group?.name||'모임')+(selectable?' ▾':'');b.disabled=!selectable;b.onclick=selectable?openGroupSwitch:null;return r};

window.openMyPinChange38=function(){openModal(`<h3>개인 비밀번호 변경</h3><div class="note">모임장·운영진 개인 비밀번호입니다. 숫자 4~8자리로 설정할 수 있으며 000000은 새 비밀번호로 사용할 수 없습니다.</div><div class="field"><label>현재 비밀번호</label><input id="myPinOld38" type="password" inputmode="numeric" placeholder="초기 비밀번호는 000000"></div><div class="field"><label>새 비밀번호</label><input id="myPinNew38" type="password" inputmode="numeric" placeholder="숫자 4~8자리"></div><div class="field"><label>새 비밀번호 확인</label><input id="myPinNew238" type="password" inputmode="numeric" placeholder="한 번 더 입력"></div><div class="acts"><button class="btn ghost" onclick="closeModal()">취소</button><button id="saveMyPin38" class="btn pri" onclick="saveMyPin38()">변경</button></div>`);setTimeout(()=>$('myPinOld38')?.focus(),30)};
window.saveMyPin38=async function(){const old=$('myPinOld38')?.value.trim()||'',n1=$('myPinNew38')?.value.trim()||'',n2=$('myPinNew238')?.value.trim()||'',btn=$('saveMyPin38');if(!old)return alert('현재 비밀번호를 입력해주세요.');if(!/^\d{4,8}$/.test(n1))return alert('새 비밀번호는 숫자 4~8자리로 입력해주세요.');if(n1!==n2)return alert('새 비밀번호 확인이 일치하지 않습니다.');if(btn){btn.disabled=true;btn.textContent='변경 중...'}try{await auth38('change_pin',{currentPin:old,newPin:n1});currentPinDefault38=false;closeModal();renderSettings();alert('개인 비밀번호를 변경했습니다. 다음 로그인부터 초기 비밀번호 안내가 표시되지 않습니다.')}catch(e){showError(e);if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent='변경'}}};
const renderSettingsPrev38=renderSettings;
renderSettings=function(){const r=renderSettingsPrev38();const box=$('settings');if(!box)return r;if(me&&!me.globalAdmin&&['manager','organizer'].includes(String(me.role))&&!box.querySelector('#personalPinCard38')){const title=box.querySelector('.title');const state=currentPinDefault38===true?'<div class="warn" style="margin-top:7px">초기 비밀번호 000000 사용 중 · 변경을 권장합니다.</div>':currentPinDefault38===false?'<div class="meta" style="margin-top:7px">개인 비밀번호가 변경되어 있습니다.</div>':'<div class="meta" style="margin-top:7px">비밀번호 상태 확인 중...</div>';title?.insertAdjacentHTML('afterend',`<div id="personalPinCard38" class="card"><div class="between"><div><b>개인 비밀번호</b><div class="meta">${me.role==='manager'?'모임장':'운영진'} 계정용</div></div><button class="btn pri" onclick="openMyPinChange38()">비밀번호 변경</button></div>${state}</div>`)}return r};

async function groupToggleReq38(groupId,active){return post38(GROUP38_API,{action:'set_active',groupId,active},true)}
window.toggleGroupActive38=async function(id,active){const g=groupSummaries.find(x=>x.groupId===id);if(!g)return;const verb=active?'활성화':'비활성화';if(!confirm(`${g.name} 모임을 ${verb}하시겠습니까?${active?'':'\n비활성화하면 해당 모임의 일반 로그인 세션이 종료됩니다.'}`))return;try{await groupToggleReq38(id,active);await loadGroups();membershipsReady38=false;await refreshMyMemberships38(true).catch(()=>{});if(!active&&currentGroupId===id&&me?.globalAdmin){const next=myMemberships38.find(x=>groupSummaries.some(g=>g.groupId===x.groupId&&g.isActive))||groupSummaries.find(x=>x.isActive);if(next){currentGroupId=next.groupId;localStorage.setItem(GROUP_KEY,currentGroupId);await loadState(true)}}renderGroups()}catch(e){showError(e)}};
function toggleHtml38(g){return `<button class="groupToggle38 ${g.isActive?'on':'off'}" aria-pressed="${g.isActive?'true':'false'}" onclick="toggleGroupActive38('${g.groupId}',${!g.isActive})"><span></span>${g.isActive?'ON':'OFF'}</button>`}
renderGroups=function(){if(!$('groups')||!canManageGroups())return;$('groups').innerHTML=`<div class="title"><h2>모임관리</h2><button class="btn pri" onclick="openGroupEditor()">+ 모임 생성</button></div><div class="note">ON/OFF로 모임 운영상태를 즉시 관리할 수 있습니다. 비활성 모임의 데이터는 보존됩니다.</div>${groupSummaries.map(g=>`<div class="card groupCard ${g.isActive?'':'inactive'}"><div class="between"><div><b>${esc(g.name)}</b><div class="meta">${g.isActive?'운영중':'비활성'}</div></div><div class="groupCountToggle38"><span class="tag">${g.memberCount}명</span>${toggleHtml38(g)}</div></div><div class="groupStats"><span>모임장 ${g.managers.length?esc(g.managers.join(', ')):'미지정'}</span><span>운영진 ${g.organizers.length?esc(g.organizers.join(', ')):'없음'}</span><span>대기 ${g.waiting}</span><span>게임중 ${g.playing}</span></div><div class="groupActs">${g.isActive?`<button class="btn pri" onclick="adminSwitchGroup38('${g.groupId}','members')">인원/권한 관리</button>`:''}<button class="btn ghost" onclick="openGroupEditor('${g.groupId}')">모임 수정</button>${!g.isActive&&typeof window.purgeGroup42==='function'?`<button class="btn danger" onclick="purgeGroup42('${g.groupId}')">완전삭제</button>`:''}</div></div>`).join('')||'<div class="empty">등록된 모임이 없습니다.</div>'}`};

function style38(){if($('style38'))return;const s=document.createElement('style');s.id='style38';s.textContent=`.groupCountToggle38{display:flex;align-items:center;gap:7px}.groupToggle38{border:0;border-radius:999px;min-width:66px;height:30px;padding:0 9px;display:flex;align-items:center;justify-content:center;gap:6px;font-weight:900;font-size:11px;cursor:pointer}.groupToggle38 span{width:15px;height:15px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.25)}.groupToggle38.on{background:#20a464;color:#fff}.groupToggle38.off{background:#c9ced8;color:#4d5562}.groupCard.inactive{opacity:.72}.choiceBtn:disabled{opacity:.55;cursor:default}`;document.head.appendChild(s)}
style38();
const renderSettingsVersion38=renderSettings;
renderSettings=function(){const r=renderSettingsVersion38();const box=$('settings');if(box)[...box.querySelectorAll('.meta')].forEach(el=>{if(/콕매치 v(?:\d+|\d+\.\d+)/.test(el.textContent||''))el.textContent='콕매치 v3.8 · 내 모임 전환 · 개발자 마지막모임 로그인 · 초기 PIN 안내 · 10명 페이지'});return r};

if(T&&me)refreshMyMemberships38(true).catch(()=>{});else if(!T)renderLoginName();
})();
