(()=>{
const BULK34_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-bulk-v44';
function yearNow34(){return Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Seoul',year:'numeric'}).format(new Date()))||new Date().getFullYear()}
function roleLabel34(r){return r==='manager'?'모임장':r==='organizer'?'운영진':'일반'}
function canAssign34(role){if(me?.globalAdmin)return ['member','organizer','manager'].includes(role);if(me?.role==='manager')return ['member','organizer'].includes(role);return role==='member'}
function parseRole34(raw){const t=String(raw||'일반').trim().toLowerCase();if(['모임장','모임관리자','manager'].includes(t))return{type:'member',role:'manager'};if(['운영진','게임편성자','organizer'].includes(t))return{type:'member',role:'organizer'};if(['일반','일반회원','회원','member',''].includes(t))return{type:'member',role:'member'};if(['게스트','guest'].includes(t))return{type:'guest',role:'member'};return null}
function parseBulk34(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),rows=[],errors=[];lines.forEach((line,idx)=>{const cells=(line.includes('\t')?line.split('\t'):line.split(',')).map(x=>x.trim());if(idx===0&&['이름','name'].includes((cells[0]||'').toLowerCase()))return;const [name,yr,gender,clsRaw,kindRaw='일반']=cells,year=Number(yr),cls=String(clsRaw||'').toUpperCase(),rr=parseRole34(kindRaw);if(!name)errors.push(`${idx+1}행: 이름이 없습니다.`);if(!Number.isInteger(year)||year<1900||year>yearNow34())errors.push(`${idx+1}행: 출생연도를 확인해주세요.`);if(!['남','여'].includes(gender))errors.push(`${idx+1}행: 성별은 남 또는 여로 입력해주세요.`);if(!['A','B','C','D','E'].includes(cls))errors.push(`${idx+1}행: 급수는 A~E로 입력해주세요.`);if(!rr)errors.push(`${idx+1}행: 구분은 모임장, 운영진, 일반 또는 게스트로 입력해주세요.`);else if(rr.type!=='guest'&&!canAssign34(rr.role))errors.push(`${idx+1}행: ${roleLabel34(rr.role)} 역할을 등록할 권한이 없습니다.`);rows.push({name,year,gender,cls,type:rr?.type||'member',role:rr?.role||'member'})});return{rows,errors}}
function allowedText34(){if(me?.globalAdmin)return'모임장 · 운영진 · 일반 · 게스트';if(me?.role==='manager')return'운영진 · 일반 · 게스트';return'일반 · 게스트'}
window.openBulkMembers37=function(){openModal(`<h3>회원 일괄등록</h3><div class="note">엑셀에서 아래 순서로 복사해 붙여넣을 수 있습니다.<br><b>이름 / 출생연도 / 성별 / 급수 / 구분</b><br>구분은 <b>모임장 · 운영진 · 일반 · 게스트</b> 중 하나를 입력합니다.<br>현재 등록 가능: <b>${allowedText34()}</b><br><span class="bulkPinNote34">신규 모임장·운영진의 초기 PIN은 자동으로 <b>000000</b>으로 설정됩니다.</span></div><div class="bulkExample37">홍길동\t1990\t남\tC\t일반<br>김운영\t1988\t남\tB\t운영진<br>이모임\t1985\t여\tA\t모임장</div><div class="field"><label>회원 목록 붙여넣기</label><textarea id="bulkText37" rows="11" placeholder="홍길동    1990    남    C    일반\n김운영    1988    남    B    운영진\n이모임    1985    여    A    모임장"></textarea></div><div id="bulkPreview37" class="meta">탭으로 구분된 엑셀 복사 또는 쉼표(,) 구분 입력을 지원합니다.</div><div class="acts"><button class="btn ghost" onclick="previewBulk37()">내용 확인</button><button class="btn pri" onclick="submitBulk37()">일괄등록</button></div><button class="btn ghost" style="width:100%;margin-top:8px" onclick="closeModal()">취소</button>`);setTimeout(()=>$('bulkText37')?.focus(),50)};
window.previewBulk37=function(){const p=parseBulk34($('bulkText37')?.value||''),el=$('bulkPreview37');if(!el)return;if(!p.rows.length){el.innerHTML='<span class="bulkErr37">등록할 내용을 붙여넣어주세요.</span>';return}if(p.errors.length){el.innerHTML=`<span class="bulkErr37">${p.errors.slice(0,8).map(esc).join('<br>')}</span>`;return}const c={manager:0,organizer:0,member:0,guest:0};for(const r of p.rows){if(r.type==='guest')c.guest++;else c[r.role]++}el.innerHTML=`<b>${p.rows.length}명</b> 등록 준비 · 모임장 ${c.manager}명 · 운영진 ${c.organizer}명 · 일반 ${c.member}명 · 게스트 ${c.guest}명`};
window.submitBulk37=async function(){const p=parseBulk34($('bulkText37')?.value||'');if(!p.rows.length)return alert('등록할 회원 목록을 붙여넣어주세요.');if(p.errors.length)return alert(p.errors.slice(0,12).join('\n'));if(!confirm(`${group?.name||'현재 모임'}에 ${p.rows.length}명을 한 번에 등록하시겠습니까?`))return;try{const r=await fetch(BULK34_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:JSON.stringify({groupId:currentGroupId,members:p.rows}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(x.error||'일괄등록에 실패했습니다.');e.details=x.details||[];throw e}S=x.data;normalizeClient();closeModal();renderAll();const staff=p.rows.filter(x=>x.type!=='guest'&&['manager','organizer'].includes(x.role)).length;alert(`${Number(x.addedCount)||p.rows.length}명을 등록했습니다.${staff?`\n모임장·운영진 초기 PIN: 000000`:''}`)}catch(e){alert([e.message,...(e.details||[]).slice(0,12)].join('\n'))}};
function syncInitialPin34(){if(editMemberId)return;const role=$('fmRole'),pin=$('fmPin'),wrap=$('fmPinWrap');if(!role)return;const staff=['manager','organizer'].includes(role.value);if(pin){if(staff){pin.value='000000';pin.readOnly=true;pin.dataset.autoPin34='1'}else if(pin.dataset.autoPin34==='1'){pin.value='';pin.readOnly=false;delete pin.dataset.autoPin34}}let note=$('staffPinNote34');if(staff){if(!note){note=document.createElement('div');note.id='staffPinNote34';note.className='meta staffPinNote34';(wrap||role.closest('.field'))?.appendChild(note)}note.innerHTML='신규 모임장·운영진 초기 PIN은 <b>000000</b>으로 자동 설정됩니다.'}else note?.remove()}
const openMemberModal33=openMemberModal;openMemberModal=function(m){const r=openMemberModal33(m);if(!m)setTimeout(()=>{const role=$('fmRole'),type=$('fmType');if(role&&!role.dataset.pin34){role.dataset.pin34='1';role.addEventListener('change',()=>setTimeout(syncInitialPin34,0))}if(type&&!type.dataset.pin34){type.dataset.pin34='1';type.addEventListener('change',()=>setTimeout(syncInitialPin34,0))}syncInitialPin34()},0);return r};
const saveMemberNow33=saveMemberNow;saveMemberNow=async function(){if(!editMemberId){const role=$('fmRole')?.value,pin=$('fmPin');if(pin&&['manager','organizer'].includes(role))pin.value='000000'}return saveMemberNow33()};
const renderSettings33=renderSettings;renderSettings=function(){renderSettings33();const b=$('settings');if(!b)return;[...b.querySelectorAll('.meta')].forEach(el=>{if(/콕매치 v(?:\d+|\d+\.\d+)/.test(el.textContent||''))el.textContent='콕매치 v3.4 · 역할별 회원 일괄등록 · 운영진 초기 PIN 000000 · 등록방식 통합'})};
})();
