(()=>{
const CUR51='5.1';let latest51=CUR51,refreshBusy51=false;
function style51(){if(document.getElementById('v51style'))return;const s=document.createElement('style');s.id='v51style';s.textContent='#topActions50{display:none!important}#topActions51{margin-left:auto;display:flex;align-items:center;justify-content:flex-end;gap:4px;position:relative;z-index:150;pointer-events:auto;min-width:0}#currentVersion51{font-size:10px;font-weight:900;padding:6px 5px;border-radius:8px;background:rgba(255,255,255,.18);white-space:nowrap;flex:0 0 auto}#headerRefresh51{flex:0 1 auto;min-width:0;max-width:170px;min-height:30px;padding:6px 8px;font-size:10.5px;font-weight:800;line-height:1.15;white-space:normal;overflow-wrap:anywhere}#logout51{flex:0 0 64px;width:64px;min-width:64px;max-width:64px;min-height:30px;padding:6px 4px;font-size:11px;white-space:nowrap}@media(max-width:380px){#currentVersion51{display:none}#headerRefresh51{max-width:135px;font-size:9.5px}#logout51{flex-basis:56px;width:56px;min-width:56px;max-width:56px;font-size:10px}}';document.head.appendChild(s)}
function cmp51(a,b){const A=String(a||'0').replace(/^v/i,'').split('.').map(n=>Number(n)||0),B=String(b||'0').replace(/^v/i,'').split('.').map(n=>Number(n)||0);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x!==y)return x>y?1:-1}return 0}
function update51(){const v=document.getElementById('currentVersion51'),b=document.getElementById('headerRefresh51');if(v)v.textContent='v'+CUR51;if(!b)return;const newer=cmp51(latest51,CUR51)>0;b.textContent=refreshBusy51?'불러오는 중…':newer?`v${latest51} 업데이트 · 새로고침`:'↻ 새로고침'}
function ensure51(){style51();const row=document.querySelector('.toprow');if(!row)return;let a=document.getElementById('topActions51');if(!a){a=document.createElement('div');a.id='topActions51';a.innerHTML='<span id="currentVersion51">v5.1</span><button id="headerRefresh51" class="btn ghost" type="button">↻ 새로고침</button><button id="logout51" type="button">로그아웃</button>';row.appendChild(a);a.querySelector('#headerRefresh51')?.addEventListener('click',()=>window.refreshApp51());a.querySelector('#logout51')?.addEventListener('click',()=>logout())}update51()}
async function latestCheck51(){try{const r=await fetch('/latest-version.json?t='+Date.now(),{cache:'no-store'});if(r.ok){const x=await r.json();latest51=String(x.semanticVersion||x.label||CUR51).replace(/^v/i,'')||CUR51}}catch{}update51();return latest51}
window.refreshApp51=async function(target=''){if(refreshBusy51)return;refreshBusy51=true;update51();try{const v=String(target||await latestCheck51()||CUR51).replace(/^v/i,'');try{if(typeof saveRefreshState==='function')saveRefreshState()}catch{}location.replace('/?v='+encodeURIComponent(v)+'&refresh='+Date.now())}catch(e){refreshBusy51=false;update51();if(typeof showError==='function')showError(e)}};
window.refreshApp50=window.refreshApp51;window.refreshApp49=window.refreshApp51;
const renderHeaderPrev51=renderHeader;renderHeader=function(){const r=renderHeaderPrev51();ensure51();return r};
const renderSettingsPrev51=renderSettings;renderSettings=function(){const r=renderSettingsPrev51();const box=typeof $==='function'?$('settings'):null;if(box&&me?.globalAdmin===true&&String(me?.displayName||'').trim()==='박태영'){const card=[...box.querySelectorAll('.card')].find(c=>String(c.textContent||'').includes('프로그램 버전'));if(card){const m=card.querySelector('.meta');if(m)m.textContent='콕매치 v5.1 · 실사용 QA 안정화 · 동시성/권한 검증 완료'}}return r};
setTimeout(()=>{ensure51();latestCheck51()},0);setInterval(()=>latestCheck51(),60000);
})();
