(()=>{
if(window.__kokmatchV54Fix6)return;window.__kokmatchV54Fix6=true;window.__kokmatchVersionLock='5.4';window.__kokmatchProfileFixReady='6.2';
const PROFILE6='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53',override6=new Map();
const baseAvatar6=typeof avatar==='function'?avatar:null;
function fallback6(m){return baseAvatar6?String(baseAvatar6(m)||''):`<div class="avatar ${m?.gender==='여'?'female':'male'}">●</div>`}
function avatar6(m){const image=override6.get(String(m?.id||''));return image?`<div class="avatar profileAvatar53"><img src="${image}" alt="${esc(m?.name||'프로필')} 프로필"></div>`:fallback6(m)}
try{avatar=function(m){return avatar6(m)}}catch{window.avatar=avatar6}
function genderText6(m){const f=m?.gender==='여';return `<span class="v54genderText ${f?'female':'male'}">${f?'여':'남'}</span>`}
function refreshMembers6(){const box=typeof $==='function'?$('members'):document.getElementById('members');if(!box||!Array.isArray(S?.members))return;const cards=[...box.querySelectorAll('.memberCard')];cards.forEach((card,i)=>{const m=S.members[i];if(!m)return;[...card.children].filter(el=>el?.classList?.contains('avatar')).forEach(el=>el.remove());card.insertAdjacentHTML('afterbegin',avatar6(m))})}
function refreshQueue6(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((card,i)=>{const m=ids[i]&&typeof M==='function'?M(ids[i]):null;if(!m)return;card.querySelectorAll('.avatar,.profileAvatar53,.queueProfile53,.genderAvatar39,.genderPerson54,.genderMini39,.v54genderText').forEach(x=>x.remove());const ord=card.querySelector('.ord');if(!ord)return;let h=avatar6(m);h=h.replace('class="avatar ','class="avatar queueProfile53 ');ord.insertAdjacentHTML('afterend',h);const photo=card.querySelector('.profileAvatar53 img');if(photo)photo.closest('.profileAvatar53')?.insertAdjacentHTML('afterend',genderText6(m))})}
function refreshSettings6(){const card=document.getElementById('profileCard53');if(!card)return;const image=override6.get(String(me?.memberId||''));if(image){const p=card.querySelector('.profilePreview53');if(p)p.innerHTML=`<img src="${image}" alt="내 프로필 사진">`}}
function refreshAll6(){try{refreshMembers6();refreshQueue6();refreshSettings6()}catch(e){console.warn('profile refresh6',e)}}
function imageElement6(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>resolve({source:im,cleanup:()=>URL.revokeObjectURL(u)});im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('선택한 사진을 읽지 못했습니다. 다른 사진 또는 JPG/PNG 사진을 선택해주세요.'))};im.src=u})}
async function decode6(file){let source=null,cleanup=()=>{};try{if(typeof createImageBitmap==='function'){try{source=await createImageBitmap(file);cleanup=()=>{try{source.close()}catch{}}}catch{source=null}}if(!source){const x=await imageElement6(file);source=x.source;cleanup=x.cleanup}const w=source.width||source.naturalWidth,h=source.height||source.naturalHeight,size=Math.min(w,h);if(!size)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');g.drawImage(source,(w-size)/2,(h-size)/2,size,size,0,0,256,256);let d=c.toDataURL('image/jpeg',.82);if(d.length>210000)d=c.toDataURL('image/jpeg',.65);if(d.length>210000)d=c.toDataURL('image/jpeg',.5);if(d.length>220000)throw new Error('사진 용량을 줄인 뒤 다시 선택해주세요.');return d}finally{cleanup()}}
async function post6(body){const r=await fetch(PROFILE6,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`프로필 저장 실패 (${r.status})`);return x}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file||!T||!me?.memberId)return;const id=String(me.memberId),had=override6.has(id),before=override6.get(id),card=document.getElementById('profileCard53'),label=card?.querySelector('label[for="profileFile53"]'),preview=card?.querySelector('.profilePreview53');let temp='';if(label){label.textContent='사진 적용 중…';label.style.pointerEvents='none'}try{temp=URL.createObjectURL(file);if(preview)preview.innerHTML=`<img src="${temp}" alt="선택한 프로필 사진">`;const image=await decode6(file);override6.set(id,image);try{renderMembers();renderQueue();if(currentView==='settings')renderSettings()}catch{}refreshAll6();if(label)label.textContent='저장 중…';await post6({action:'save_profile',groupId:String(currentGroupId||''),image});refreshAll6();if(label)label.textContent='저장됨';setTimeout(()=>{const l=document.querySelector('label[for="profileFile53"]');if(l)l.textContent='사진 변경'},800)}catch(e){if(had)override6.set(id,before);else override6.delete(id);try{renderMembers();renderQueue();if(currentView==='settings')renderSettings()}catch{}refreshAll6();if(typeof showError==='function')showError(e);else alert(e.message)}finally{if(temp)URL.revokeObjectURL(temp);if(input)input.value='';if(label){label.style.pointerEvents='none';setTimeout(()=>{label.style.pointerEvents=''},0)}}};
const oldDelete6=window.deleteProfile53;window.deleteProfile53=async function(){const id=String(me?.memberId||'');if(!id||!T)return;try{await post6({action:'delete_profile',groupId:String(currentGroupId||'')});override6.delete(id);if(typeof oldDelete6==='function'){/* server already deleted; do not call twice */}try{renderMembers();renderQueue();if(currentView==='settings')renderSettings()}catch{}refreshAll6()}catch(e){if(typeof showError==='function')showError(e)}};
const rq6=renderQueue;renderQueue=function(){const r=rq6();refreshQueue6();return r};const rm6=renderMembers;renderMembers=function(){const r=rm6();refreshMembers6();return r};const rs6=renderSettings;renderSettings=function(){const r=rs6();refreshSettings6();return r};const ra6=renderAll;renderAll=function(){const r=ra6();refreshAll6();return r};refreshAll6();
})();