(()=>{
if(window.__kokmatchV54Hotfix3)return;window.__kokmatchV54Hotfix3=true;
const CUR54='5.4',DRAFT_KEY54='kokmatch_draft_v54_',PROFILE54='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
let restoredGroup54='',profiles54={},profilesGroup54='',profileLoadSeq54=0,profileSaveSeq54=0;
const avatarBefore54=typeof avatar==='function'?avatar:null;
function gid54(){return String(currentGroupId||'')}
function draftKey54(){return DRAFT_KEY54+gid54()}
function saveDraft54(){try{if(!gid54()||!Array.isArray(draft))return;localStorage.setItem(draftKey54(),JSON.stringify(draft.slice(0,4)))}catch{}}
function restoreDraft54(){try{if(!gid54()||!Array.isArray(draft)||!Array.isArray(S?.members)||!S.members.length)return false;const raw=localStorage.getItem(draftKey54());if(!raw)return true;const a=JSON.parse(raw);if(!Array.isArray(a))return true;const valid=a.slice(0,4).map(id=>id&&typeof M==='function'&&M(id)?id:null);while(valid.length<4)valid.push(null);draft.splice(0,draft.length,...valid);return true}catch{return false}}
function ensureDraft54(){const g=gid54();if(!g||restoredGroup54===g)return;if(restoreDraft54())restoredGroup54=g}
function clearDraft54(){try{localStorage.removeItem(draftKey54())}catch{};restoredGroup54=gid54()}
function wrapDraft54(name,after){const f=window[name];if(typeof f!=='function'||f.__v54fix3)return;const w=function(...a){const r=f.apply(this,a);Promise.resolve(r).finally(()=>{try{after?.()}catch{}});return r};w.__v54fix3=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}
for(const n of ['draftClick','draftRemove','recommendDraft'])wrapDraft54(n,()=>{saveDraft54();try{renderQueue()}catch{}});
wrapDraft54('registerDraft',()=>clearDraft54());

function style54(){if(document.getElementById('v54style3'))return;const s=document.createElement('style');s.id='v54style3';s.textContent=`
.composer54 .slots.pendingGrid{display:grid!important;grid-template-columns:1fr 1fr!important;gap:7px!important}
.composer54 .slot54.pendingSlot{min-height:66px!important;border-radius:12px!important;background:#f2f5fd!important;padding:8px!important;position:relative!important;border:1px solid transparent!important}
.composer54 .slot54.pendingSlot.emptySlot{border:1px dashed #b8c4e0!important;background:#fafbff!important;color:#72809a!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;font-weight:850!important}
.composer54 .slot54 .slotName{font-weight:900!important;padding-right:24px!important}.composer54 .slot54 .meta{margin-top:2px!important}
.composer54 .slot54 .pendingX{position:absolute!important;right:5px!important;top:5px!important;border:0!important;background:#fff0f0!important;color:var(--red)!important;border-radius:50%!important;width:23px!important;height:23px!important;font-weight:950!important}
.composer54 .slot54 .gradeBadge50,.composer54 .slot54 .tag{margin-left:4px!important}.composer54 .slot54 .roleBadge,.composer54 .slot54 .roleShuttle50{vertical-align:middle!important}
#profileFile53{display:none!important}.profilePreview53 img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}
#headerRefresh52.v54hidden{display:none!important}
`;document.head.appendChild(s)}
function fallbackAvatar54(m){return avatarBefore54?String(avatarBefore54(m)||''):`<div class="avatar ${m?.gender==='여'?'female':'male'}">●</div>`}
function avatar54(m){const p=profiles54[String(m?.id||'')]?.image||'';return p?`<div class="avatar profileAvatar53"><img src="${p}" alt="${esc(m?.name||'프로필')} 프로필"></div>`:fallbackAvatar54(m)}
try{avatar=function(m){return avatar54(m)}}catch{window.avatar=avatar54}

function composerSlotHtml54(id,i){const m=id&&typeof M==='function'?M(id):null;if(!m)return `<div class="slot54 pendingSlot emptySlot"><span><b>${i<2?'A팀':'B팀'} ${i%2+1}</b><br><span class="meta">개인 게임대기에서 선택</span></span></div>`;return `<div class="slot54 pendingSlot filled"><button class="pendingX slotX" type="button" onclick="event.stopPropagation();draftRemove(${i})">×</button><div class="slotLabel">${i<2?'A팀':'B팀'} ${i%2+1}</div><div class="slotName">${esc(m.name)} ${ageTag(m)} ${roleBadge(m)}</div><div class="meta">게임 ${dailyCount(id)}회 · ${waitMins(m)}분 대기</div></div>`}
function mirrorPendingLayout54(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box)return;const comp=box.querySelector('.composer54,.composer');if(!comp)return;comp.classList.add('composer54');const slots=comp.querySelector('.slots');if(!slots)return;slots.classList.add('pendingGrid');slots.innerHTML=(Array.isArray(draft)?draft:[null,null,null,null]).slice(0,4).map(composerSlotHtml54).join('')}
function decoratePhotoGender54(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((c,i)=>{const id=ids[i],m=id&&typeof M==='function'?M(id):null;if(!m)return;c.querySelectorAll('.avatar,.profileAvatar53,.queueProfile53,.genderAvatar39,.genderPerson54,.v54genderText').forEach(x=>x.remove());const ord=c.querySelector('.ord');if(ord)ord.insertAdjacentHTML('afterend',avatar54(m).replace('class="avatar ','class="avatar queueProfile53 '));const photo=c.querySelector('.profileAvatar53 img');if(photo){const f=m.gender==='여';photo.closest('.profileAvatar53')?.insertAdjacentHTML('afterend',`<span class="v54genderText ${f?'female':'male'}">${f?'여':'남'}</span>`)}})}
function patchProfileCard54(){const card=document.getElementById('profileCard53');if(!card)return;const inp=card.querySelector('#profileFile53');if(inp){inp.setAttribute('accept','image/*');inp.removeAttribute('onchange');if(!inp.dataset.v54bound){inp.dataset.v54bound='1';inp.addEventListener('change',()=>window.changeProfile53(inp))}}const id=String(me?.memberId||'');const img=profiles54[id]?.image||'';const preview=card.querySelector('.profilePreview53');if(preview&&img)preview.innerHTML=`<img src="${img}" alt="내 프로필 사진">`;const label=card.querySelector('label[for="profileFile53"]');if(label)label.textContent='사진 변경'}
async function profileReq54(url,opt={}){const r=await fetch(url,opt),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`프로필 저장 실패 (${r.status})`);return x}
async function loadProfiles54(force=false){if(!T||!gid54()||gid54()==='__global__')return;const g=gid54();if(!force&&profilesGroup54===g)return;const seq=++profileLoadSeq54,saveAtStart=profileSaveSeq54;const u=new URL(PROFILE54);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());try{const x=await profileReq54(u,{headers:{authorization:'Bearer '+T},cache:'no-store'});if(seq!==profileLoadSeq54||g!==gid54()||saveAtStart!==profileSaveSeq54)return;profiles54=x.profiles||{};profilesGroup54=g;try{renderMembers();renderQueue();if(currentView==='settings'){renderSettings();patchProfileCard54()}}catch{}}catch(e){console.warn('profile load',e)}}
function imageToJpeg54(file){return new Promise((resolve,reject)=>{if(!file)return reject(new Error('사진을 선택해주세요.'));if(file.size>20*1024*1024)return reject(new Error('사진은 20MB 이하만 선택할 수 있습니다.'));const url=URL.createObjectURL(file),im=new Image();im.onload=()=>{try{const size=Math.min(im.naturalWidth,im.naturalHeight);if(!size)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.drawImage(im,(im.naturalWidth-size)/2,(im.naturalHeight-size)/2,size,size,0,0,256,256);let d=c.toDataURL('image/jpeg',.82);if(d.length>210000)d=c.toDataURL('image/jpeg',.65);if(d.length>210000)d=c.toDataURL('image/jpeg',.5);URL.revokeObjectURL(url);if(d.length>220000)return reject(new Error('사진 용량을 줄인 뒤 다시 선택해주세요.'));resolve(d)}catch(e){URL.revokeObjectURL(url);reject(e)}};im.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('이 사진 형식은 브라우저에서 읽을 수 없습니다. 다른 사진 또는 JPG/PNG를 선택해주세요.'))};im.src=url})}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file||!T||!me?.memberId)return;const card=document.getElementById('profileCard53'),label=card?.querySelector('label[for="profileFile53"]'),preview=card?.querySelector('.profilePreview53');const oldHtml=preview?.innerHTML||'';if(label){label.textContent='저장 중…';label.style.pointerEvents='none'}let temp='';try{temp=URL.createObjectURL(file);if(preview)preview.innerHTML=`<img src="${temp}" alt="선택한 프로필 사진">`;const image=await imageToJpeg54(file);const g=gid54(),id=String(me.memberId);const x=await profileReq54(PROFILE54,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({action:'save_profile',groupId:g,image}),cache:'no-store'});profileSaveSeq54++;profileLoadSeq54++;profiles54[id]={image:x.image||image,updatedAt:new Date().toISOString()};profilesGroup54=g;try{renderMembers();renderQueue();if(currentView==='settings'){renderSettings();patchProfileCard54()}}catch{} }catch(e){if(preview)preview.innerHTML=oldHtml;if(typeof showError==='function')showError(e);else alert(e.message)}finally{if(temp)URL.revokeObjectURL(temp);if(input)input.value='';if(label){label.textContent='사진 변경';label.style.pointerEvents=''}}};
window.deleteProfile53=async function(){if(!T||!me?.memberId)return;try{await profileReq54(PROFILE54,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({action:'delete_profile',groupId:gid54()}),cache:'no-store'});profileSaveSeq54++;profileLoadSeq54++;delete profiles54[String(me.memberId)];profilesGroup54=gid54();renderMembers();renderQueue();if(currentView==='settings'){renderSettings();patchProfileCard54()}}catch(e){if(typeof showError==='function')showError(e)}};

async function syncLatest54(){const b=document.getElementById('headerRefresh52');if(!b)return;try{const r=await fetch('/latest-version.json?t='+Date.now(),{cache:'no-store'}),x=await r.json(),latest=String(x.semanticVersion||x.label||CUR54).replace(/^v/i,'');b.classList.toggle('v54hidden',latest===CUR54);if(latest!==CUR54)b.textContent=`v${latest} 업데이트 · 새로고침`}catch{b.classList.add('v54hidden')}}
function mark54(){document.title='콕매치 v5.4';document.documentElement.dataset.kokmatchVersion='5.4';const old=document.getElementById('currentVersion52');if(old&&old.textContent!=='v5.4'){const v=old.cloneNode(true);v.textContent='v5.4';old.replaceWith(v)}syncLatest54()}
const rq54=renderQueue;renderQueue=function(){ensureDraft54();const r=rq54();style54();mirrorPendingLayout54();decoratePhotoGender54();saveDraft54();mark54();return r};
const ra54=renderAll;renderAll=function(){ensureDraft54();const r=ra54();style54();try{mirrorPendingLayout54();decoratePhotoGender54();if(currentView==='settings')patchProfileCard54()}catch{}saveDraft54();mark54();const g=gid54();if(T&&g&&g!=='__global__'&&profilesGroup54!==g)queueMicrotask(()=>loadProfiles54().catch(()=>{}));return r};
const rs54=renderSettings;renderSettings=function(){const r=rs54();style54();patchProfileCard54();return r};
const gv54=goView;goView=function(id){const r=gv54(id);if(id==='settings'){patchProfileCard54();loadProfiles54().catch(()=>{})}return r};
style54();ensureDraft54();setTimeout(()=>{mark54();try{renderQueue();if(currentView==='settings')patchProfileCard54();if(T)loadProfiles54(true)}catch{}},0);setInterval(()=>{mark54();syncLatest54()},30000);
})();