(()=>{
const BULK35_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-bulk-v44';
function role35(raw){const t=String(raw||'일반').trim().toLowerCase();if(['모임장','모임관리자','manager'].includes(t))return{type:'member',role:'manager'};if(['운영진','게임편성자','organizer'].includes(t))return{type:'member',role:'organizer'};if(['일반','일반회원','회원','member',''].includes(t))return{type:'member',role:'member'};if(['게스트','guest'].includes(t))return{type:'guest',role:'member'};return null}
function year35(){return Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Seoul',year:'numeric'}).format(new Date()))||new Date().getFullYear()}
function parse35(text){const rows=[],errors=[];String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach((line,idx)=>{const c=(line.includes('\t')?line.split('\t'):line.split(',')).map(x=>x.trim());if(idx===0&&['이름','name'].includes((c[0]||'').toLowerCase()))return;const [name,yr,gender,clsRaw,kind='일반']=c,y=Number(yr),cls=String(clsRaw||'').toUpperCase(),rr=role35(kind);if(!name)errors.push(`${idx+1}행: 이름이 없습니다.`);if(!Number.isInteger(y)||y<1900||y>year35())errors.push(`${idx+1}행: 출생연도를 확인해주세요.`);if(!['남','여'].includes(gender))errors.push(`${idx+1}행: 성별은 남 또는 여로 입력해주세요.`);if(!['A','B','C','D','E'].includes(cls))errors.push(`${idx+1}행: 급수는 A~E로 입력해주세요.`);if(!rr)errors.push(`${idx+1}행: 구분은 모임장, 운영진, 일반 또는 게스트로 입력해주세요.`);rows.push({name,year:y,gender,cls,type:rr?.type||'member',role:rr?.role||'member'})});return{rows,errors}}
function sig35(x){return [String(x?.name||'').trim(),String(Number(x?.year)||''),String(x?.gender||'').trim(),String(x?.cls||'').trim().toUpperCase()].join('|')}
function label35(x){return `${String(x?.name||'').trim()} · ${Number(x?.year)||''}년생 · ${String(x?.gender||'')} · ${String(x?.cls||'').toUpperCase()}급`}
function exactDuplicates35(rows){const existing=new Map(),batch=new Map(),dups=[];(S?.members||[]).filter(m=>m?.type!=='guest').forEach(m=>existing.set(sig35(m),m));for(const r of rows){if(r.type==='guest')continue;const s=sig35(r);if(existing.has(s))dups.push({kind:'existing',row:r});else if(batch.has(s))dups.push({kind:'batch',row:r});else batch.set(s,r)}return dups}
window.submitBulk37=async function(){const p=parse35($('bulkText37')?.value||'');if(!p.rows.length)return alert('등록할 회원 목록을 붙여넣어주세요.');if(p.errors.length)return alert(p.errors.slice(0,12).join('\n'));const d=exactDuplicates35(p.rows);if(d.length){const lines=[...new Map(d.map(x=>[sig35(x.row),label35(x.row)])).values()];alert(`동일한 회원 정보가 확인되었습니다.\n\n${lines.slice(0,10).join('\n')}\n\n이름·출생연도·성별·급수가 모두 같은 회원은 중복 등록할 수 없습니다.`);return}if(!confirm(`${group?.name||'현재 모임'}에 ${p.rows.length}명을 한 번에 등록하시겠습니까?`))return;try{const r=await fetch(BULK35_API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:JSON.stringify({groupId:currentGroupId,members:p.rows}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok){const details=Array.isArray(x.details)?x.details:[];if(x.duplicateWarning||details.some(v=>/동일 회원|같은 회원/.test(String(v)))){alert(['동일한 회원 정보가 확인되었습니다.',...details.slice(0,10),'','이름·출생연도·성별·급수가 모두 같은 회원은 중복 등록할 수 없습니다.'].join('\n'));return}const e=new Error(x.error||'일괄등록에 실패했습니다.');e.details=details;throw e}S=x.data;normalizeClient();closeModal();renderAll();const staff=p.rows.filter(x=>x.type!=='guest'&&['manager','organizer'].includes(x.role)).length;alert(`${Number(x.addedCount)||p.rows.length}명을 등록했습니다.${staff?'\n모임장·운영진 초기 PIN: 000000':''}`)}catch(e){alert([e.message,...(e.details||[]).slice(0,12)].join('\n'))}};
const renderSettings34=renderSettings;renderSettings=function(){renderSettings34();const b=$('settings');if(!b)return;[...b.querySelectorAll('.meta')].forEach(el=>{if(/콕매치 v(?:\d+|\d+\.\d+)/.test(el.textContent||''))el.textContent='콕매치 v3.5 · 동명이인 허용 · 이름/출생연도/성별/급수 완전일치만 중복 경고'})};
})();
