(()=>{
if(window.__kokmatchV56)return;window.__kokmatchV56=true;window.__kokmatchV56Patch='1.0';
const VERSION='5.6',PROFILE='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
let cacheGroup='',profiles={},loadSeq=0,lastGroup='';
const token=()=>String(window.T||'');const gid=()=>String(window.currentGroupId||'');
const esc56=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gender56(m){const g=String(m?.gender||'').trim().toLowerCase();return ['여','여자','여성','f','female'].includes(g)?'여':'남'}
function photo56(m){const g=gid(),id=String(m?.id||'');return cacheGroup===g?String(profiles?.[id]?.image||''):''}
function avatar56(m){const p=photo56(m),female=gender56(m)==='여';return p?`<div class="avatar profileAvatar53 ${female?'female':'male'}"><img src="${p}" alt="${esc56(m?.name||'프로필')} 프로필"></div>`:`<div class="avatar ${female?'female':'male'}">●</div>`}
function lockAvatar56(){try{Object.defineProperty(window,'avatar',{configurable:true,enumerable:true,get:()=>avatar56,set:()=>{}})}catch{try{window.avatar=avatar56;avatar=avatar56}catch{}}}
function lockVersion56(){try{Object.defineProperty(window,'__kokmatchVersionLock',{configurable:true,enumerable:true,get:()=>VERSION,set:()=>{}})}catch{window.__kokmatchVersionLock=VERSION}document.documentElement.dataset.kokmatchVersion=VERSION;document.title='콕매치 v'+VERSION;const ids=['currentVersion51','currentVersion52'];ids.forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='v'+VERSION})}
function memberById56(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function memberForCard56(card){let id='';const p=card?.querySelector?.('.pairBtn')?.getAttribute('onclick')||'';const hit=p.match(/openPairs\(['"]([^'"]+)['"]\)/);if(hit)id=hit[1];if(!id)id=String(card?.dataset?.memberId80||card?.dataset?.memberId56||'');const m=memberById56(id);if(m){card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}return m}
function queueMembers56(){try{return typeof sortedQueue==='function'?sortedQueue().map(id=>memberById56(id)):[]}catch{return []}}
function makeIdentity56(m,queue=false){const p=photo56(m),female=gender56(m)==='여',d=document.createElement('div');d.className=`avatar profileIdentity80 genderVisual10 ${p?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.memberId56=String(m?.id||'');d.dataset.gender=female?'여':'남';d.dataset.photo=p?'1':'0';d.setAttribute('aria-label',p?`${String(m?.name||'회원')} 프로필 사진 크게 보기`:(female?'여성':'남성'));if(p){d.setAttribute('role','button');d.setAttribute('tabindex','0');const im=document.createElement('img');im.src=p;im.alt=`${String(m?.name||'프로필')} 프로필`;d.appendChild(im)}else d.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg>';return d}
function directIdentity56(card){return [...(card?.children||[])].find(x=>x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('queueProfile53'))}
function sameIdentity56(el,m){if(!el||!m)return false;const p=photo56(m),g=gender56(m);return String(el.dataset?.memberId||el.dataset?.memberId56||'')===String(m.id)&&String(el.dataset?.gender||'')===g&&String(el.dataset?.photo||'0')===(p?'1':'0')&&(!p||String(el.querySelector?.('img')?.getAttribute('src')||'')===p)}
function clearDirect56(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText')||x.classList?.contains('queueProfile53'))x.remove()}
function fixMemberCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);card.insertBefore(makeIdentity56(m,false),card.firstChild)}card.dataset.memberId56=String(m.id)}
function fixQueueCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);const d=makeIdentity56(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}
function canonicalize56(){lockVersion56();lockAvatar56();try{document.querySelectorAll('#members .memberCard').forEach(card=>fixMemberCard56(card,memberForCard56(card)));const ms=queueMembers56(),cards=[...document.querySelectorAll('#queue .queueCard')];cards.forEach((card,i)=>fixQueueCard56(card,ms[i]||null))}catch(e){console.warn('v5.6 identity',e)}}
async function loadProfiles56(group=gid(),force=false){const g=String(group||'');if(!g||g==='__global__'||!token())return;if(g!==cacheGroup){cacheGroup=g;profiles={};canonicalize56()}else if(!force&&Object.keys(profiles).length)return;const seq=++loadSeq;try{const u=new URL(PROFILE);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+token()},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 조회 실패');if(seq!==loadSeq||g!==gid())return;cacheGroup=g;profiles=x.profiles||{};canonicalize56();try{renderMembers();renderQueue()}catch{};requestAnimationFrame(canonicalize56)}catch(e){console.warn('v5.6 profiles',e)}}
function watch56(){const g=gid();if(g!==lastGroup){lastGroup=g;cacheGroup=g;profiles={};loadSeq++;lockAvatar56();canonicalize56();if(g&&g!=='__global__'&&token())loadProfiles56(g,true)}else if(g&&g!=='__global__'&&token()&&cacheGroup===g&&!Object.keys(profiles).length)loadProfiles56(g,true)}
function wrap56(name){try{const f=window[name];if(typeof f!=='function'||f.__v56)return;const w=function(){const r=f.apply(this,arguments);queueMicrotask(()=>{watch56();canonicalize56()});return r};w.__v56=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}catch{}}
['renderMembers','renderQueue','renderAll','renderHeader'].forEach(wrap56);
for(const n of ['changeProfile53','deleteProfile53']){try{const f=window[n];if(typeof f==='function'&&!f.__v56){const w=async function(){const r=await f.apply(this,arguments);await loadProfiles56(gid(),true);return r};w.__v56=true;window[n]=w;try{eval(`${n}=window[n]`)}catch{}}}catch{}}
let raf=0;const mo=new MutationObserver(()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;canonicalize56()})});function start56(){lockVersion56();lockAvatar56();const m=document.getElementById('members'),q=document.getElementById('queue');if(m)mo.observe(m,{childList:true,subtree:true});if(q)mo.observe(q,{childList:true,subtree:true});watch56();canonicalize56()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start56,{once:true});else start56();
setInterval(()=>{lockVersion56();lockAvatar56();watch56()},250);
})();