(()=>{
const CUR54='5.4',DRAFT_KEY54='kokmatch_draft_v54_';
let restoredGroup54='',profileWriteGen54=0,profileCommittedImage54='';
function gid54(){return String(currentGroupId||'')}
function draftKey54(){return DRAFT_KEY54+gid54()}
function saveDraft54(){try{if(!gid54()||!Array.isArray(draft))return;localStorage.setItem(draftKey54(),JSON.stringify(draft.slice(0,4)))}catch{}}
function restoreDraft54(){try{if(!gid54()||!Array.isArray(draft)||!Array.isArray(S?.members)||!S.members.length)return false;const raw=localStorage.getItem(draftKey54());if(!raw)return true;const a=JSON.parse(raw);if(!Array.isArray(a))return true;const valid=a.slice(0,4).map(id=>id&&typeof M==='function'&&M(id)?id:null);while(valid.length<4)valid.push(null);draft.splice(0,draft.length,...valid);return true}catch{return false}}
function ensureDraft54(){const g=gid54();if(!g||restoredGroup54===g)return;if(restoreDraft54())restoredGroup54=g}
function clearDraft54(){try{localStorage.removeItem(draftKey54())}catch{};restoredGroup54=gid54()}
function wrapDraft54(name,after){const f=window[name];if(typeof f!=='function'||f.__v54fix)return;const w=function(...a){const r=f.apply(this,a);Promise.resolve(r).finally(()=>{try{after?.()}catch{}});return r};w.__v54fix=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}
for(const n of ['draftClick','draftRemove','recommendDraft'])wrapDraft54(n,()=>{saveDraft54();try{decorateComposer54()}catch{}});
wrapDraft54('registerDraft',()=>{clearDraft54()});

function style54(){if(document.getElementById('v54style2'))return;const s=document.createElement('style');s.id='v54style2';s.textContent=`
.composer54 .slots{gap:6px!important}.composer54 .slot54{padding:8px 9px!important;min-height:86px!important}.composer54 .slotTop53{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:6px!important}.composer54 .slotBadges53{display:flex!important;align-items:center!important;gap:4px!important}.composer54 .slotName53{display:flex!important;align-items:center!important;gap:4px!important;flex-wrap:wrap!important;margin-top:3px!important}.composer54 .gradeBadge50,.composer54 .tag{margin:0!important}.composer54 .genderAvatar39,.composer54 .profileAvatar53,.composer54 .queueProfile53,.composer54 .genderPerson54{display:none!important}
.composerGender54{width:24px;height:24px;min-width:24px;display:inline-flex;align-items:center;justify-content:center;border-radius:50%}.composerGender54 svg{width:16px;height:16px;fill:currentColor}.composerGender54.male{color:#3977d5;background:#eef5ff}.composerGender54.female{color:#d85b8f;background:#fff2f7}
.v54genderText{display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;min-width:22px;border-radius:50%;font-size:10px;font-weight:900;line-height:1;border:1px solid currentColor;margin-left:4px;vertical-align:middle}.v54genderText.female{color:#d85b8f;background:#fff2f7}.v54genderText.male{color:#3977d5;background:#eef5ff}.queueCard .profileAvatar53+.v54genderText{margin-left:3px}#headerRefresh52.v54hidden{display:none!important}
`;document.head.appendChild(s)}
function genderText54(m){const f=m?.gender==='여';return `<span class="v54genderText ${f?'female':'male'}" aria-label="${f?'여':'남'}">${f?'여':'남'}</span>`}
function genderPerson54x(m){const f=m?.gender==='여';return `<span class="composerGender54 ${f?'female':'male'}" aria-label="${f?'여성':'남성'}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg></span>`}
function decorateComposer54(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box)return;const slots=[...box.querySelectorAll('.composer54 .slot54')];slots.forEach((slot,i)=>{slot.querySelectorAll('.genderPerson54,.genderAvatar39,.profileAvatar53,.queueProfile53,.composerGender54').forEach(x=>x.remove());const id=Array.isArray(draft)?draft[i]:null,m=id&&typeof M==='function'?M(id):null;if(!m)return;let top=slot.querySelector('.slotTop53'),label=slot.querySelector('.slotLabel');if(!top&&label){top=document.createElement('div');top.className='slotTop53';label.parentNode.insertBefore(top,label);top.appendChild(label)}const name=slot.querySelector('.slotName53');const role=name?.querySelector('.roleBadge');const badges=document.createElement('span');badges.className='slotBadges53';badges.innerHTML=genderPerson54x(m);if(role)badges.appendChild(role);if(top){top.querySelector('.slotBadges53')?.remove();top.appendChild(badges)}const grade=name?.querySelector('.gradeBadge50,.tag');if(grade){grade.style.margin='0'}})}
function decoratePhotoGender54(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((c,i)=>{c.querySelectorAll('.v54genderText').forEach(x=>x.remove());const m=ids[i]&&typeof M==='function'?M(ids[i]):null;if(!m)return;const photo=c.querySelector('.profileAvatar53 img');if(photo)photo.closest('.profileAvatar53')?.insertAdjacentHTML('afterend',genderText54(m))})}

const nativeFetch54=window.fetch.bind(window);if(!window.__profileFetchGuard54){window.__profileFetchGuard54=true;window.fetch=async function(input,init){const url=String(typeof input==='string'?input:input?.url||'');const isProfile=url.includes('/kokmatch-profile-v53');if(!isProfile)return nativeFetch54(input,init);const method=String(init?.method||'GET').toUpperCase(),startGen=profileWriteGen54;let pendingImage='';if(method==='POST'){try{const b=JSON.parse(String(init?.body||'{}'));if(b.action==='save_profile')pendingImage=String(b.image||'')}catch{}}const r=await nativeFetch54(input,init);if(method==='POST'&&r.ok&&pendingImage){profileCommittedImage54=pendingImage;profileWriteGen54++}if(method==='GET'&&r.ok&&startGen<profileWriteGen54&&profileCommittedImage54&&me?.memberId){try{const x=await r.clone().json();x.profiles=x.profiles||{};x.profiles[String(me.memberId)]={image:profileCommittedImage54,updatedAt:new Date().toISOString()};return new Response(JSON.stringify(x),{status:r.status,statusText:r.statusText,headers:{'content-type':'application/json','cache-control':'no-store'}})}catch{}}return r}}

async function syncLatest54(){const b=document.getElementById('headerRefresh52');if(!b)return;try{const r=await nativeFetch54('/latest-version.json?t='+Date.now(),{cache:'no-store'}),x=await r.json(),latest=String(x.semanticVersion||x.label||CUR54).replace(/^v/i,'');b.classList.toggle('v54hidden',latest===CUR54);if(latest!==CUR54)b.textContent=`v${latest} 업데이트 · 새로고침`}catch{b.classList.add('v54hidden')}}
function mark54(){document.title='콕매치 v5.4';document.documentElement.dataset.kokmatchVersion='5.4';const old=document.getElementById('currentVersion52');if(old&&old.textContent!=='v5.4'){const v=old.cloneNode(true);v.textContent='v5.4';old.replaceWith(v)}syncLatest54()}
const rq54=renderQueue;renderQueue=function(){ensureDraft54();const r=rq54();style54();decorateComposer54();decoratePhotoGender54();mark54();return r};
const ra54=renderAll;renderAll=function(){ensureDraft54();const r=ra54();style54();try{decorateComposer54();decoratePhotoGender54()}catch{}mark54();return r};
if(typeof window.changeProfile53==='function'){const oldChange=window.changeProfile53;window.changeProfile53=async function(input){const f=input?.files?.[0];if(!f)return;let temp='';try{temp=URL.createObjectURL(f);const p=document.querySelector('#profileCard53 .profilePreview53');if(p)p.innerHTML=`<img src="${temp}" alt="내 프로필 사진">`}catch{}try{return await oldChange(input)}finally{if(temp)URL.revokeObjectURL(temp);await new Promise(res=>requestAnimationFrame(()=>requestAnimationFrame(res)));try{renderMembers();renderQueue();if(currentView==='settings')renderSettings()}catch{}mark54()}}}
style54();ensureDraft54();setTimeout(()=>{mark54();try{renderQueue()}catch{}},0);setInterval(()=>{mark54();syncLatest54()},30000);
})();