(()=>{
'use strict';
if(window.__kokmatchV54Fix21)return;
window.__kokmatchV54Fix21=true;
window.__kokmatchProfileCanonical='21.0';
const API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const photos=new Map();
let loadedKey='',busy=null,seq=0,raf=0,ta=0,tb=0;

function esc(v){return String(v??'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function mem(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function sex(m){return String(m?.gender||'').trim()==='여'?'여':'남'}
function pic(m){return String(photos.get(String(m?.id||''))||'')}
function meMember(){const d=mem(me?.memberId);if(d)return d;const n=String(me?.displayName||me?.name||'').trim();if(!n||!Array.isArray(S?.members))return null;const a=S.members.filter(m=>String(m?.name||'').trim()===n);return a.length===1?a[0]:null}
function pageRows(){const all=Array.isArray(S?.members)?S.members:[],q=String(document.getElementById('memberSearchInput46')?.value||'').trim().toLowerCase();const f=!q?all:all.filter(m=>{let r='';try{r=typeof roleLabel==='function'&&typeof roleOf==='function'?roleLabel(roleOf(m)):''}catch{}return[m?.name,m?.cls,m?.gender,m?.inviter,r,m?.type==='guest'?'게스트':'일반회원'].some(v=>String(v||'').toLowerCase().includes(q))});const p=Math.max(1,Number(document.querySelector('#members .memberPager46 b')?.textContent)||1);return f.slice((p-1)*10,p*10)}
function visibleName(card){return String(card?.querySelector('.memberName45')?.textContent||'').trim()||String(card?.querySelector('.name')?.childNodes?.[0]?.textContent||'').trim()}
function cardMember(card,index,rows){rows=rows||pageRows();const name=visibleName(card),meta=String(card?.querySelector('.meta')?.textContent||''),g=(meta.match(/(?:년생\s*·\s*|^|\s)(남|여)(?:\s|·|$)/)||[])[1]||'',y=(meta.match(/(\d{4})년생/)||[])[1]||'',grade=(String(card?.querySelector('.gradeBadge50,.tag')?.textContent||'').match(/([A-E])$/i)||[])[1]?.toUpperCase()||'';let c=rows.filter(m=>!name||String(m?.name||'').trim()===name);if(g)c=c.filter(m=>String(m?.gender||'').trim()===g);if(y)c=c.filter(m=>String(m?.year||'')===y);if(grade)c=c.filter(m=>String(m?.cls||'').trim().toUpperCase()===grade);if(c.length===1)return c[0];const on=String(card?.querySelector('.pairBtn')?.getAttribute('onclick')||''),id=(on.match(/openPairs\(\s*['\"]([^'\"]+)['\"]\s*\)/)||[])[1];const hinted=c.find(m=>String(m?.id||'')===String(id||''));return hinted||rows[index]||c[0]||null}
function queueMember(card){try{const box=document.getElementById('queue'),i=[...(box?.querySelectorAll('.queueCard')||[])].indexOf(card),ids=typeof sortedQueue==='function'?sortedQueue():[];return mem(ids[i])}catch{return null}}
function css(){if(document.getElementById('v54fix21style'))return;const s=document.createElement('style');s.id='v54fix21style';s.textContent=`
.profileIdentity21{position:relative!important;display:grid!important;place-items:center!important;border-radius:50%!important;overflow:hidden!important;flex:0 0 auto!important;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
.profileIdentity21 img{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:50%!important;display:block!important;pointer-events:none!important;-webkit-user-drag:none!important}
.profileIdentity21.noPhoto21{font-size:14px!important;font-weight:950!important;line-height:1!important}
.profileIdentity21.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}.profileIdentity21.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
.memberCard.memberIdentity21{grid-template-columns:50px minmax(0,1fr) auto!important;column-gap:10px!important}.memberCard.memberIdentity21>.profileIdentity21{width:50px!important;height:50px!important;min-width:50px!important}
.queueCard.queueIdentity21{grid-template-columns:29px 44px minmax(0,1fr) 18px!important;column-gap:7px!important;align-items:center!important}.queueCard.queueIdentity21>.profileIdentity21{width:44px!important;height:44px!important;min-width:44px!important;margin:0!important}
.profilePreview53 .profileFallback21{width:100%!important;height:100%!important;min-height:64px!important;border-radius:50%!important;display:grid!important;place-items:center!important;font-size:18px!important;font-weight:950!important}.profilePreview53 .profileFallback21.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}.profilePreview53 .profileFallback21.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
#profileModal21{position:fixed;inset:0;z-index:1200;display:none;align-items:center;justify-content:center;background:#080d19ed;padding:18px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}#profileModal21.on{display:flex}.profileSheet21{position:relative;width:min(760px,96vw);max-height:94vh;display:flex;flex-direction:column;align-items:center;gap:9px}.profileImg21{display:block;max-width:94vw;max-height:84vh;width:auto;height:auto;object-fit:contain;border-radius:14px;background:#fff;box-shadow:0 18px 56px #0008;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}.profileClose21{position:absolute;right:0;top:-6px;width:40px;height:40px;border:0;border-radius:50%;background:#fffffff2;color:#172033;font-size:25px;font-weight:900;display:grid;place-items:center}.profileName21{color:#fff;font-size:14px;font-weight:900}.profileState21{color:#dfe6f3;font-size:11px;min-height:16px}
@media(max-width:599px){.memberCard.memberIdentity21{grid-template-columns:46px minmax(0,1fr)!important}.memberCard.memberIdentity21>.profileIdentity21{width:46px!important;height:46px!important;min-width:46px!important}.queueCard.queueIdentity21{grid-template-columns:27px 42px minmax(0,1fr) 16px!important}.queueCard.queueIdentity21>.profileIdentity21{width:42px!important;height:42px!important;min-width:42px!important}}
`;document.head.appendChild(s)}
function identity(m,queue=false){const g=sex(m),f=g==='여',src=pic(m),d=document.createElement('div');d.className=`avatar profileIdentity21 ${src?'hasPhoto21':'noPhoto21'} ${f?'female':'male'}${queue?' queueProfile21':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.gender=g;d.dataset.photo=src?'1':'0';if(src){d.setAttribute('role','button');d.setAttribute('tabindex','0');d.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);d.innerHTML=`<img src="${esc(src)}" alt="${esc(m?.name||'프로필')} 프로필" draggable="false">`}else{d.setAttribute('aria-label',f?'여성':'남성');d.textContent=g}return d}
function avatarHtml(m){const g=sex(m),f=g==='여',src=pic(m);return src?`<div class="avatar profileIdentity21 hasPhoto21 ${f?'female':'male'}" data-member-id="${esc(m?.id||'')}" data-gender="${g}" data-photo="1"><img src="${esc(src)}" alt="${esc(m?.name||'프로필')} 프로필" draggable="false"></div>`:`<div class="avatar profileIdentity21 noPhoto21 ${f?'female':'male'}" data-member-id="${esc(m?.id||'')}" data-gender="${g}" data-photo="0" aria-label="${f?'여성':'남성'}">${g}</div>`}
function installAvatar(){try{avatar=avatarHtml}catch{}try{window.avatar=avatarHtml}catch{}}
function clearIdentity(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('profileIdentity21')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove()}
function fixActions(card,id){for(const el of card?.querySelectorAll?.('[onclick]')||[]){let c=String(el.getAttribute('onclick')||''),n=c;n=n.replace(/openPairs\(\s*['\"][^'\"]+['\"]\s*\)/g,`openPairs('${id}')`).replace(/openEditMember\(\s*['\"][^'\"]+['\"]\s*\)/g,`openEditMember('${id}')`).replace(/setOther\(\s*['\"][^'\"]+['\"]\s*,/g,`setOther('${id}',`);if(n!==c)el.setAttribute('onclick',n)}}
function members(){const box=document.getElementById('members');if(!box)return;const cards=[...box.querySelectorAll('.memberCard')],rows=pageRows();cards.forEach((card,i)=>{const m=cardMember(card,i,rows);if(!m)return;const id=String(m.id||''),g=sex(m),src=pic(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity21'));const ok=cur&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0')&&(src?String(cur.querySelector('img')?.getAttribute('src')||'')===src:String(cur.textContent||'').trim()===g);card.dataset.memberId21=id;fixActions(card,id);if(!ok){clearIdentity(card);card.insertBefore(identity(m),card.firstChild)}card.classList.add('memberIdentity21')})}
function queue(){const box=document.getElementById('queue');if(!box)return;for(const card of box.querySelectorAll('.queueCard')){const m=queueMember(card);if(!m)continue;const id=String(m.id||''),g=sex(m),src=pic(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity21'));const ok=cur&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0');card.dataset.memberId21=id;if(!ok){clearIdentity(card);const d=identity(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.classList.add('queueIdentity21')}}
function settings(){const p=document.querySelector('#profileCard53 .profilePreview53');if(!p)return;const m=meMember();if(!m){p.innerHTML='';p.dataset.profile21='';return}const g=sex(m),f=g==='여',src=pic(m),sig=`${m.id}|${g}|${src}`;if(p.dataset.profile21===sig)return;p.dataset.profile21=sig;p.innerHTML=src?`<img src="${esc(src)}" alt="내 프로필 사진" draggable="false">`:`<div class="profileFallback21 ${f?'female':'male'}" aria-label="${f?'여성':'남성'}">${g}</div>`}
function decorate(){css();installAvatar();members();queue();settings()}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;decorate()});clearTimeout(ta);clearTimeout(tb);ta=setTimeout(decorate,80);tb=setTimeout(decorate,350)}
async function load(force=false){const g=String(currentGroupId||''),t=String(T||''),key=g+'|'+t;if(!g||g==='__global__'||!t){loadedKey=key;photos.clear();window.__kokmatchProfilesLoaded21=g;schedule();return}if(!force&&loadedKey===key&&window.__kokmatchProfilesLoaded21===g)return;if(busy&&!force)return busy;photos.clear();loadedKey=key;window.__kokmatchProfilesLoaded21='';schedule();const mine=++seq;busy=(async()=>{try{const u=new URL(API);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+t},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 조회 실패');if(mine!==seq||String(currentGroupId||'')!==g||String(T||'')!==t)return;for(const [id,v] of Object.entries(x?.profiles||{})){const s=String(v?.image||'');if(s)photos.set(String(id),s)}window.__kokmatchProfilesLoaded21=g;schedule()}catch(e){console.warn('profile21',e);if(mine===seq){photos.clear();window.__kokmatchProfilesLoaded21=g;schedule()}}finally{if(mine===seq)busy=null}})();return busy}
function ensure(){const key=String(currentGroupId||'')+'|'+String(T||'');if(key!==loadedKey||window.__kokmatchProfilesLoaded21!==String(currentGroupId||''))load(false);schedule()}
function modal(){let m=document.getElementById('profileModal21');if(m)return m;m=document.createElement('div');m.id='profileModal21';m.innerHTML='<div class="profileSheet21"><button class="profileClose21" type="button" aria-label="닫기">×</button><img class="profileImg21" alt="프로필 사진 크게 보기" draggable="false"><div class="profileName21"></div><div class="profileState21"></div></div>';m.addEventListener('click',e=>{if(e.target===m)closeModal()});m.querySelector('.profileClose21')?.addEventListener('click',closeModal);document.body.appendChild(m);return m}
function closeModal(){document.getElementById('profileModal21')?.classList.remove('on');try{document.body.style.overflow=''}catch{}}
async function openModal(el){if(!el||el.dataset.photo!=='1')return;const id=String(el.dataset.memberId||''),m=mem(id),thumb=String(el.querySelector('img')?.getAttribute('src')||'');if(!id||!thumb)return;const d=modal(),im=d.querySelector('.profileImg21'),nm=d.querySelector('.profileName21'),st=d.querySelector('.profileState21');im.src=thumb;nm.textContent=String(m?.name||'');st.textContent='고화질 사진 불러오는 중…';d.classList.add('on');try{document.body.style.overflow='hidden'}catch{}try{const u=new URL(API);u.searchParams.set('groupId',String(currentGroupId||''));u.searchParams.set('memberId',id);u.searchParams.set('full','1');u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store'}),x=await r.json().catch(()=>({}));const full=String(x.fullImage||x.image||thumb);if(d.classList.contains('on'))im.src=full;st.textContent=full!==thumb?'고화질 보기':'저장된 프로필 사진 보기'}catch{st.textContent='저장된 프로필 사진 보기'}}
window.openProfilePhoto21=openModal;window.closeProfilePhoto21=closeModal;
function dataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>res(String(r.result||''));r.readAsDataURL(file)})}
function imgFrom(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
async function source(file){if(typeof createImageBitmap==='function')try{return await createImageBitmap(file)}catch{}return await imgFrom(await dataUrl(file))}
function jpeg(src,maxSide,q,crop=false){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas'),g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');if(crop){const size=Math.min(w,h);c.width=c.height=maxSide;g.fillStyle='#fff';g.fillRect(0,0,maxSide,maxSide);g.drawImage(src,(w-size)/2,(h-size)/2,size,size,0,0,maxSide,maxSide)}else{const sc=Math.min(1,maxSide/Math.max(w,h));c.width=Math.max(1,Math.round(w*sc));c.height=Math.max(1,Math.round(h*sc));g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(src,0,0,w,h,0,0,c.width,c.height)}return c.toDataURL('image/jpeg',q)}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 저장 실패');return x}
function status(text,bad=false){const el=document.querySelector('#profileStatus65,.profileHelp53');if(el){el.textContent=text;el.style.color=bad?'#b42318':'#667085'}}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file)return;if(file.size>30*1024*1024){status('원본 사진은 30MB 이하만 사용할 수 있습니다.',true);input.value='';return}try{status('사진 처리 중…');const src=await source(file);let thumb=jpeg(src,256,.82,true),full=jpeg(src,2048,.9,false);for(const q of [.84,.78,.72,.66]){if(full.length<=2350000)break;full=jpeg(src,2048,q,false)}if(full.length>2450000)full=jpeg(src,1600,.78,false);if(thumb.length>220000)thumb=jpeg(src,256,.62,true);if(thumb.length>220000||full.length>2500000)throw new Error('사진 용량을 줄인 뒤 다시 선택해주세요.');await post({action:'save_profile',groupId:String(currentGroupId||''),image:thumb,fullImage:full});try{src.close?.()}catch{}await load(true);status('프로필 사진 저장 완료');schedule()}catch(e){status(e?.message||'프로필 사진 저장에 실패했습니다.',true)}finally{if(input)input.value=''}};
window.deleteProfile53=async function(){try{status('프로필 사진 삭제 중…');await post({action:'delete_profile',groupId:String(currentGroupId||'')});await load(true);status('기본 프로필로 변경 완료');schedule()}catch(e){status(e?.message||'프로필 삭제에 실패했습니다.',true)}};
try{changeProfile53=window.changeProfile53;deleteProfile53=window.deleteProfile53}catch{}
try{const rm=renderMembers;renderMembers=function(){const r=rm();ensure();return r};const rq=renderQueue;renderQueue=function(){const r=rq();ensure();return r};const rs=renderSettings;renderSettings=function(){const r=rs();ensure();return r};const ra=renderAll;renderAll=function(){const r=ra();ensure();return r}}catch{}
if(!window.__kokmatchProfileEvents21){window.__kokmatchProfileEvents21=true;window.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null,el=t?.closest?.('.profileIdentity21');if(!el||!el.closest('#members,#queue'))return;if(el.dataset.photo==='1'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openModal(el)}},true);window.addEventListener('contextmenu',e=>{const t=e.target instanceof Element?e.target:null;if(t?.closest?.('.profileIdentity21,#profileModal21')){e.preventDefault();e.stopImmediatePropagation()}},true);window.addEventListener('dragstart',e=>{const t=e.target instanceof Element?e.target:null;if(t?.closest?.('.profileIdentity21,#profileModal21'))e.preventDefault()},true);window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
const mo=new MutationObserver(schedule);function boot(){css();installAvatar();for(const id of ['members','queue','settings']){const el=document.getElementById(id);if(el)mo.observe(el,{childList:true,subtree:true})}ensure();setTimeout(decorate,700);setTimeout(decorate,1800)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();