(()=>{
if(window.__kokmatchV54Fix11)return;
window.__kokmatchV54Fix11=true;
window.__kokmatchStatsPatch='11.1';
const STATS11='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-stats-v54';
let from11=businessDay11(),to11=from11,tab11='mine',sortKey11='games',sortDir11=-1;
let stats11=null,statsSig11='',statsSeq11=0,statsBusy11=false,statsGroup11='';

function esc11(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function businessDay11(ts=Date.now()){const d=new Date(ts-5*60*60*1000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function parts11(ms){if(!Number(ms))return null;const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(Number(ms)));const g=t=>p.find(x=>x.type===t)?.value||'';return{m:g('month'),d:g('day'),h:g('hour'),min:g('minute')}}
function start11(ms){const p=parts11(ms);return p?`${p.m}-${p.d} ${p.h}:${p.min}`:'-'}
function dayLabel11(v){const a=String(v||'').split('-');return a.length===3?`${Number(a[1])}월 ${Number(a[2])}일`:String(v||'-')}
function duration11(g){const n=Number(g?.durationMin);if(n>0)return n;const a=Number(g?.startedAt),b=Number(g?.endedAt);return a&&b?Math.max(0,(b-a)/60000):0}
function durText11(g){const n=duration11(g);return n>0?`${Math.round(n)}분`:'-'}
function ageText11(m){const a=String(m?.age||'').trim();if(!a)return'-';return a.includes('대')?a:`${a}대`}
function ageShort11(m){return String(m?.age||'').replace(/대/g,'').trim()||'-'}
function member11(id){return (stats11?.members||[]).find(m=>String(m.id)===String(id))||null}
function gamesFor11(id,rows=stats11?.rangeGames||[]){return (rows||[]).filter(g=>Array.isArray(g.players)&&g.players.map(String).includes(String(id)))}
function playerName11(g,i){const id=String(g?.players?.[i]||''),n=String(g?.playerNames?.[i]||'').trim();return n||member11(id)?.name||'삭제회원'}
function partnerParts11(g,id){const ps=Array.isArray(g?.players)?g.players.map(String):[];return ps.map((p,i)=>({id:p,name:playerName11(g,i)})).filter(x=>x.id!==String(id))}
function partnerHtml11(g,id){const a=partnerParts11(g,id);return a.length?a.map((x,i)=>{const f=String(member11(x.id)?.gender||'')==='여';return `<span class="${f?'femalePartner11':''}">${esc11(x.name)}</span>${i<a.length-1?', ':''}`}).join(''):'-'}
function allPlayersHtml11(g){const ps=Array.isArray(g?.players)?g.players.map(String):[];return ps.map((id,i)=>{const f=String(member11(id)?.gender||'')==='여';return `<span class="${f?'femalePartner11':''}">${esc11(playerName11(g,i))}</span>${i<ps.length-1?', ':''}`}).join('')||'-'}
function todayCount11(id){return gamesFor11(id).filter(g=>String(g.businessDay)===String(stats11?.today||businessDay11())).length}
function attendance11(m){const days=new Set(gamesFor11(m.id).map(g=>String(g.businessDay||'')).filter(Boolean));const last=String(m?.attendanceLastDay||'');if(last&&last>=from11&&last<=to11)days.add(last);const sameMonth=from11.slice(0,7)===to11.slice(0,7),fullStart=from11.endsWith('-01');if(sameMonth&&fullStart){const h=Number(m?.attendanceHistory?.[from11.slice(0,7)]);if(Number.isFinite(h)&&h>days.size&&to11>=String(stats11?.today||to11))return h}return days.size}
function rowData11(){return (stats11?.members||[]).filter(m=>String(m.type||'member')!=='guest').map(m=>{const games=gamesFor11(m.id).length,attendance=attendance11(m),avg=attendance?games/attendance:0,today=todayCount11(m.id);return{m,games,attendance,avg,today}})}
function value11(r,k){if(k==='name')return String(r.m.name||'');if(k==='age')return Number(String(r.m.age||'').replace(/\D/g,''))||0;if(k==='cls')return String(r.m.cls||'Z');if(k==='attendance')return r.attendance;if(k==='games')return r.games;if(k==='avg')return r.avg;if(k==='today')return r.today;return 0}
function sortedRows11(){const a=rowData11();a.sort((x,y)=>{const A=value11(x,sortKey11),B=value11(y,sortKey11);let c=typeof A==='number'&&typeof B==='number'?A-B:String(A).localeCompare(String(B),'ko',{numeric:true});if(!c&&sortKey11!=='games')c=y.games-x.games;if(!c)c=String(x.m.name||'').localeCompare(String(y.m.name||''),'ko');return c*sortDir11});return a}
function sortMark11(k){return sortKey11===k?`<span class="sortMark11">${sortDir11>0?'▲':'▼'}</span>`:''}
function gradeClass11(v){const c=String(v||'').toUpperCase();return ['A','B','C','D','S'].includes(c)?`g${c}`:'gEtc'}
function zcls11(n){return Number(n)===0?'zeroStat11':''}

function style11(){if(document.getElementById('v54fix11style'))return;const s=document.createElement('style');s.id='v54fix11style';s.textContent=`
#queue .composer54 .slotName .roleBadge,#queue .composer54 .slotName .roleShuttle50,#queue .pendingCard .slotName .roleBadge,#queue .pendingCard .slotName .roleShuttle50,#queue .pendingGrid .slotName .roleBadge,#queue .pendingGrid .slotName .roleShuttle50{display:none!important}
#stats{padding-bottom:92px}#stats .pollWrap90{margin-bottom:10px!important}
.statsShell11{width:100%;box-sizing:border-box}.statsPeriodBox11{background:#fff;border:1px solid #dbe2f1;border-radius:11px;padding:8px 9px;margin-bottom:8px}.statsPeriodGrid11{display:grid;grid-template-columns:auto minmax(0,1fr) 14px minmax(0,1fr);gap:5px;align-items:center}.periodLabel11{font-size:12px;font-weight:900;color:#2948b5;white-space:nowrap}.statsPeriodGrid11 input{width:100%;min-width:0;box-sizing:border-box;height:38px;border:1px solid #cbd5ef;border-radius:8px;background:#fff;font-size:12px;text-align:center;padding:5px 2px;color:#252a37}.statsPeriodGrid11 input::-webkit-date-and-time-value{text-align:center;padding:0}.periodDash11{text-align:center;color:#65718c;font-size:12px;font-weight:800;white-space:nowrap}
.statsTabs11{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:8px 0}.statsTab11{height:36px;border:1px solid #cbd4eb;border-radius:7px;background:#f5f7fb;color:#53607a;font-size:12px;font-weight:850;padding:0 2px}.statsTab11.on{background:#304bc2;color:#fff;border-color:#304bc2}.statsHint11{display:flex;align-items:center;gap:5px;background:#f5f7fb;border:1px solid #e1e6f1;color:#70798b;font-size:10.5px;padding:7px 8px;margin-bottom:4px}
.recordBox11{background:#fff;border:1px solid #dfe4ef;border-radius:5px;overflow:hidden}.recordTitle11{padding:9px 10px;background:#f7f8fc;border-bottom:1px solid #e2e6ef;font-weight:900;color:#2f374a;font-size:13px}.recordTable11{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}.recordTable11 th{background:#304bc2;color:#fff;padding:7px 4px;font-size:11px}.recordTable11 td{padding:7px 4px;border-bottom:1px solid #fff;text-align:center;color:#4a5060;vertical-align:middle}.recordTable11 tbody tr:nth-child(odd){background:#f4f4f5}.recordTable11 tbody tr:nth-child(even){background:#e7e7e8}.recordTable11 th:nth-child(1),.recordTable11 td:nth-child(1){width:31%}.recordTable11 th:nth-child(2),.recordTable11 td:nth-child(2){width:51%;text-align:left}.recordTable11 th:nth-child(3),.recordTable11 td:nth-child(3){width:18%}.recordTime11{color:#342cb1!important;font-weight:950!important}.femalePartner11{color:#ef5b91!important;font-weight:800}.emptyStats11{padding:24px 10px;text-align:center;color:#818a9b;font-size:12px;background:#fff}
.personalTable11{width:100%;border-collapse:collapse;table-layout:fixed;font-size:10.7px}.personalTable11 th{background:#304bc2;color:#fff;padding:7px 1px;white-space:nowrap;cursor:pointer;user-select:none}.personalTable11 td{padding:6px 1px;text-align:center;border-bottom:1px solid #e4e7ee;color:#183cca;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.personalTable11 tbody tr:nth-child(odd){background:#fff}.personalTable11 tbody tr:nth-child(even){background:#f7f8fb}.personalTable11 th:nth-child(1),.personalTable11 td:nth-child(1){width:9%}.personalTable11 th:nth-child(2),.personalTable11 td:nth-child(2){width:19%}.personalTable11 th:nth-child(3),.personalTable11 td:nth-child(3){width:13%}.personalTable11 th:nth-child(4),.personalTable11 td:nth-child(4){width:11%}.personalTable11 th:nth-child(5),.personalTable11 td:nth-child(5){width:12%}.personalTable11 th:nth-child(6),.personalTable11 td:nth-child(6){width:12%}.personalTable11 th:nth-child(7),.personalTable11 td:nth-child(7){width:13%}.personalTable11 th:nth-child(8),.personalTable11 td:nth-child(8){width:11%}.personLink11{border:0;background:transparent;color:#183cca;font:inherit;font-weight:850;padding:0;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rank11{display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;border-radius:50%;background:#e5e8ed;color:#69717f;font-size:10px;font-weight:950}.rank11.r1{background:#ffe16a;color:#6f5500}.rank11.r2{background:#d8dde4;color:#4f5967}.rank11.r3{background:#d78639;color:#fff}.grade11{display:inline-flex;align-items:center;justify-content:center;width:23px;height:23px;border-radius:50%;font-size:10px;font-weight:950;color:#fff}.grade11.gA{background:#b83b35}.grade11.gB{background:#3152ba}.grade11.gC{background:#38a36b}.grade11.gD{background:#fff327;color:#4d4a00}.grade11.gS{background:#c6a138;color:#fff}.grade11.gEtc{background:#6f7787}.todayBubble11{display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:22px;padding:0 3px;border-radius:999px;background:#dfe3e9;color:#8b93a1;font-size:10px;font-weight:900}.todayBubble11.has{background:#304bc2;color:#fff}.zeroStat11{color:#d62e3d!important;font-weight:950!important}.sortMark11{font-size:8px;margin-left:1px;color:#dfe6ff}
.gameTable11{width:100%;border-collapse:collapse;font-size:11px}.gameTable11 th{background:#304bc2;color:#fff;padding:7px 4px}.gameTable11 td{padding:7px 4px;border-bottom:1px solid #e4e7ee;color:#485165}.gameTable11 tbody tr:nth-child(even){background:#f5f6f9}.gameTable11 td:first-child,.gameTable11 td:last-child{text-align:center;white-space:nowrap}
.statsLoading11,.statsError11{padding:24px 10px;text-align:center;background:#fff;border:1px solid #e0e4ee;border-radius:7px;font-size:12px;color:#727c90}.statsError11{color:#b72938;background:#fff3f4}
.statsDetailOverlay11{position:fixed;z-index:10050;inset:0;background:rgba(14,18,36,.58);display:none;align-items:center;justify-content:center;padding:12px;box-sizing:border-box}.statsDetailOverlay11.on{display:flex}.statsDetailPanel11{width:min(520px,96vw);max-height:88vh;background:#f4f4f5;border-radius:10px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.3)}.statsDetailHead11{height:54px;background:#4638b8;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 11px;font-size:17px;font-weight:950}.statsDetailClose11{border:0;background:transparent;color:#fff;font-size:24px;line-height:1;padding:6px}.statsDetailBody11{padding:7px;max-height:calc(88vh - 54px);overflow:auto;-webkit-overflow-scrolling:touch}.statsDetailBody11 .recordTable11{font-size:11px}
@media(max-width:420px){.statsPeriodBox11{padding:7px 6px}.statsPeriodGrid11{grid-template-columns:auto minmax(0,1fr) 12px minmax(0,1fr);gap:3px}.periodLabel11{font-size:11px}.statsPeriodGrid11 input{height:37px;font-size:11.5px;padding:4px 1px}.statsTabs11{gap:4px}.statsTab11{font-size:11.5px}.statsDetailHead11{font-size:16px}.personalTable11{font-size:10.4px}.personalTable11 th{font-size:10.2px}}
@media(max-width:374px){.statsPeriodGrid11{grid-template-columns:auto minmax(0,1fr) 10px minmax(0,1fr);gap:2px}.periodLabel11{font-size:10px}.statsPeriodGrid11 input{font-size:10.5px}.statsTab11{font-size:10.5px}.personalTable11{font-size:9.6px}.personalTable11 th{font-size:9.4px}.rank11,.grade11,.todayBubble11{transform:scale(.92)}}
`;document.head.appendChild(s)}

function cleanupComposer11(){style11();const box=document.getElementById('queue');if(!box)return;box.querySelectorAll('.composer54 .slotName,.pendingCard .slotName,.pendingGrid .slotName').forEach(n=>{n.querySelectorAll('.roleBadge,.roleShuttle50').forEach(x=>x.remove());[...n.children].forEach(x=>{if(x.classList?.contains('compactName53')||x.classList?.contains('tag')||x.classList?.contains('nameGender58'))return;const t=String(x.textContent||'').trim();if(/^(일반|일반회원|총관리자|모임장|모임관리자|운영진|게임편성자|임시편성자)$/.test(t))x.remove()})})}
let qraf11=0;function scheduleComposer11(){if(qraf11)return;qraf11=requestAnimationFrame(()=>{qraf11=0;cleanupComposer11()})}

function period11(){return `<div class="statsPeriodBox11"><div class="statsPeriodGrid11"><span class="periodLabel11">▣ 기간</span><input id="statsFrom11" type="date" value="${esc11(from11)}" aria-label="시작일"><span class="periodDash11">~</span><input id="statsTo11" type="date" value="${esc11(to11)}" aria-label="종료일"></div></div>`}
function tabs11(){const a=[['mine','♟','내기록'],['personal','⚝','개인별'],['games','▶','게임별'],['days','▣','일자별']];return `<div class="statsTabs11">${a.map(([k,i,t])=>`<button type="button" class="statsTab11 ${tab11===k?'on':''}" data-tab11="${k}">${i} ${t}</button>`).join('')}</div>`}
function recordTable11(id,rows){const games=(rows||[]).slice().sort((a,b)=>Number(b.startedAt)-Number(a.startedAt));if(!games.length)return '<div class="emptyStats11">선택한 기간에 완료한 게임이 없습니다.</div>';return `<div class="recordBox11"><table class="recordTable11"><thead><tr><th>시작</th><th>파트너</th><th>시간</th></tr></thead><tbody>${games.map(g=>`<tr><td>${esc11(start11(g.startedAt))}</td><td>${partnerHtml11(g,id)}</td><td class="recordTime11">${esc11(durText11(g))}</td></tr>`).join('')}</tbody></table></div>`}
function mineView11(){const id=String(stats11?.selfMemberId||me?.memberId||''),m=member11(id);if(!m)return '<div class="emptyStats11">현재 모임에서 내 회원정보를 찾지 못했습니다.</div>';const title=`${esc11(m.name)}님 ${esc11(ageShort11(m))}${esc11(m.cls||'')} ${esc11(m.gender||'')} 게임기록`;return `<div class="recordTitle11">${title}</div>${recordTable11(id,gamesFor11(id))}`}
function rankClass11(i){return i===0?'r1':i===1?'r2':i===2?'r3':''}
function personalView11(){const rows=sortedRows11();return `<div class="statsHint11">ⓘ 이름 또는 나이 클릭 시 상세 내역을 확인할 수 있습니다.</div><div class="recordBox11"><table class="personalTable11"><thead><tr><th>순위</th><th data-sort11="name">이름${sortMark11('name')}</th><th data-sort11="age">나이${sortMark11('age')}</th><th data-sort11="cls">급수${sortMark11('cls')}</th><th data-sort11="attendance">출석${sortMark11('attendance')}</th><th data-sort11="games">게임${sortMark11('games')}</th><th data-sort11="avg">평균${sortMark11('avg')}</th><th data-sort11="today">오늘${sortMark11('today')}</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><span class="rank11 ${rankClass11(i)}">${i+1}</span></td><td><button class="personLink11" data-detail11="${esc11(r.m.id)}">${esc11(r.m.name)}</button></td><td><button class="personLink11" data-detail11="${esc11(r.m.id)}">${esc11(ageText11(r.m))}</button></td><td><span class="grade11 ${gradeClass11(r.m.cls)}">${esc11(r.m.cls||'-')}</span></td><td class="${zcls11(r.attendance)}">${r.attendance}</td><td class="${zcls11(r.games)}">${r.games}</td><td class="${zcls11(r.avg)}">${r.avg?Number(r.avg.toFixed(1)):0}</td><td class="${zcls11(r.today)}"><span class="todayBubble11 ${r.today?'has':''}">${r.today}</span></td></tr>`).join('')||'<tr><td colspan="8">표시할 회원이 없습니다.</td></tr>'}</tbody></table></div>`}
function gamesView11(){const rows=(stats11?.rangeGames||[]).slice().sort((a,b)=>Number(b.startedAt)-Number(a.startedAt));if(!rows.length)return '<div class="emptyStats11">선택한 기간에 완료한 게임이 없습니다.</div>';return `<div class="recordBox11"><table class="gameTable11"><thead><tr><th>시작</th><th>참가자</th><th>시간</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${esc11(start11(g.startedAt))}</td><td>${allPlayersHtml11(g)}</td><td class="recordTime11">${esc11(durText11(g))}</td></tr>`).join('')}</tbody></table></div>`}
function daysView11(){const map=new Map();for(const g of stats11?.rangeGames||[]){const d=String(g.businessDay||'');if(!map.has(d))map.set(d,{games:0,players:new Set(),mins:0});const x=map.get(d);x.games++;for(const p of g.players||[])x.players.add(String(p));x.mins+=duration11(g)}const rows=[...map.entries()].sort((a,b)=>b[0].localeCompare(a[0]));if(!rows.length)return '<div class="emptyStats11">선택한 기간에 기록이 없습니다.</div>';return `<div class="recordBox11"><table class="gameTable11"><thead><tr><th>일자</th><th>게임 / 참가</th><th>평균시간</th></tr></thead><tbody>${rows.map(([d,x])=>`<tr><td>${esc11(dayLabel11(d))}</td><td>${x.games}게임 · ${x.players.size}명</td><td class="recordTime11">${x.games?Math.round(x.mins/x.games):0}분</td></tr>`).join('')}</tbody></table></div>`}
function body11(){if(statsBusy11&&!stats11)return '<div class="statsLoading11">기록 불러오는 중…</div>';if(stats11?.error)return `<div class="statsError11">${esc11(stats11.error)}</div>`;if(!stats11)return '<div class="statsLoading11">기록 불러오는 중…</div>';if(tab11==='personal')return personalView11();if(tab11==='games')return gamesView11();if(tab11==='days')return daysView11();return mineView11()}

function paintStats11(){style11();const box=document.getElementById('stats');if(!box)return;const poll=box.querySelector('.pollWrap90');if(poll)poll.remove();box.innerHTML=`<div class="statsShell11">${period11()}${tabs11()}<div id="statsBody11">${body11()}</div></div>`;if(poll)box.insertBefore(poll,box.firstChild);bindStats11(box)}
function applyRange11(changed){const f=document.getElementById('statsFrom11')?.value||from11,t=document.getElementById('statsTo11')?.value||to11;if(!f||!t)return;if(f>t){if(changed==='from')to11=f;else from11=t}else{from11=f;to11=t}loadStats11(true)}
function bindStats11(box){box.querySelector('#statsFrom11')?.addEventListener('change',()=>applyRange11('from'));box.querySelector('#statsTo11')?.addEventListener('change',()=>applyRange11('to'));box.querySelectorAll('[data-tab11]').forEach(b=>b.addEventListener('click',()=>{tab11=String(b.dataset.tab11||'mine');paintStats11()}));box.querySelectorAll('[data-sort11]').forEach(h=>h.addEventListener('click',()=>{const k=String(h.dataset.sort11||'games');if(sortKey11===k)sortDir11*=-1;else{sortKey11=k;sortDir11=k==='name'||k==='age'||k==='cls'?1:-1}paintStats11()}));box.querySelectorAll('[data-detail11]').forEach(b=>b.addEventListener('click',()=>openDetail11(String(b.dataset.detail11||''))))}
async function reqStats11(){const u=new URL(STATS11);u.searchParams.set('groupId',String(currentGroupId||''));u.searchParams.set('from',from11);u.searchParams.set('to',to11);u.searchParams.set('month',from11.slice(0,7));u.searchParams.set('t',String(Date.now()));const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store',credentials:'omit'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`통계 조회 실패 (${r.status})`);return x}
async function loadStats11(force=false){if(!T||!currentGroupId||currentGroupId==='__global__')return;const sig=[currentGroupId,from11,to11].join('|');if(!force&&stats11&&statsSig11===sig){paintStats11();return}const seq=++statsSeq11;statsBusy11=true;if(statsGroup11!==String(currentGroupId)){stats11=null;statsGroup11=String(currentGroupId)}paintStats11();try{const x=await reqStats11();if(seq!==statsSeq11)return;stats11=x;statsSig11=sig}catch(e){if(seq!==statsSeq11)return;stats11={error:e?.message||'통계 기록을 불러오지 못했습니다.'};statsSig11=sig}finally{if(seq===statsSeq11){statsBusy11=false;paintStats11()}}}

function ensureDetail11(){let o=document.getElementById('statsDetailOverlay11');if(o)return o;o=document.createElement('div');o.id='statsDetailOverlay11';o.className='statsDetailOverlay11';o.innerHTML='<div class="statsDetailPanel11"><div class="statsDetailHead11"><span id="statsDetailTitle11">게임기록</span><button type="button" class="statsDetailClose11" aria-label="닫기">×</button></div><div class="statsDetailBody11" id="statsDetailBody11"></div></div>';document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)closeDetail11()});o.querySelector('.statsDetailClose11')?.addEventListener('click',closeDetail11);return o}
function openDetail11(id){const m=member11(id);if(!m)return;const o=ensureDetail11(),title=`${m.name}님 ${ageShort11(m)}${m.cls||''} ${m.gender||''} 게임기록`;o.querySelector('#statsDetailTitle11').textContent=title;o.querySelector('#statsDetailBody11').innerHTML=recordTable11(id,gamesFor11(id));o.classList.add('on');document.body.style.overflow='hidden'}
function closeDetail11(){document.getElementById('statsDetailOverlay11')?.classList.remove('on');document.body.style.overflow=''}
window.openStatsDetail11=openDetail11;window.closeStatsDetail11=closeDetail11;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail11()});

const prevStats11=typeof renderStats==='function'?renderStats:null;renderStats=function(){const r=prevStats11?prevStats11():undefined;paintStats11();if(currentView==='stats')queueMicrotask(()=>loadStats11(false));return r};
const prevQueue11=typeof renderQueue==='function'?renderQueue:null;if(prevQueue11)renderQueue=function(){const r=prevQueue11();scheduleComposer11();return r};
const prevAll11=typeof renderAll==='function'?renderAll:null;if(prevAll11)renderAll=function(){const before=statsGroup11,r=prevAll11();scheduleComposer11();if(before&&before!==String(currentGroupId||'')){stats11=null;statsSig11='';statsGroup11=String(currentGroupId||'')}if(currentView==='stats')paintStats11();return r};
const prevGo11=typeof goView==='function'?goView:null;if(prevGo11)goView=function(id){const r=prevGo11(id);if(id==='stats'){paintStats11();loadStats11(false)}return r};
try{window.renderStats=renderStats;window.renderQueue=renderQueue;window.renderAll=renderAll;window.goView=goView}catch{}
const mo11=new MutationObserver(scheduleComposer11);function boot11(){style11();const q=document.getElementById('queue');if(q)mo11.observe(q,{childList:true,subtree:true});scheduleComposer11();if(me&&currentView==='stats'){renderStats();loadStats11(true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot11,{once:true});else boot11();
})();