(()=>{
if(window.__kokmatchV54Fix9)return;
window.__kokmatchV54Fix9=true;
window.__kokmatchProfileUiPatch='9.0';

function style9(){if(document.getElementById('profileUi90Style'))return;const s=document.createElement('style');s.id='profileUi90Style';s.textContent='.profileIdentity80 .profileGender70{display:none!important}';document.head.appendChild(s)}
function parsed9(m){try{const d=document.createElement('div');d.innerHTML=typeof avatar==='function'?String(avatar(m)||''):'';return d.firstElementChild}catch{return null}}
function src9(m){const x=parsed9(m)?.querySelector?.('img');return x?String(x.getAttribute('src')||x.src||''):''}
function identity9(m,queue=false){const src=src9(m),female=String(m?.gender||'')==='여',d=document.createElement('div');d.className=`avatar profileIdentity80 ${src?'profileTap80 profileAvatar53':'genderFallback80'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.gender=female?'여':'남';d.dataset.photo=src?'1':'0';if(src){d.setAttribute('role','button');d.setAttribute('tabindex','0');d.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);const im=document.createElement('img');im.src=src;im.alt=`${String(m?.name||'프로필')} 프로필`;const b=document.createElement('span');b.className=`profileGender80 ${female?'female':'male'}`;b.textContent=female?'여':'남';d.append(im,b)}else{d.setAttribute('aria-label',female?'여성':'남성');d.textContent=female?'여':'남'}return d}
function member9(card){let id=String(card?.dataset?.memberId80||'');if(!id){const on=card?.querySelector('.pairBtn')?.getAttribute('onclick')||'',m=on.match(/openPairs\(['"]([^'"]+)['"]\)/);if(m)id=m[1]}const x=id&&typeof M==='function'?M(id):null;if(x&&card)card.dataset.memberId80=id;return x||null}
function queueMember9(card){let id=String(card?.dataset?.memberId80||'');if(id&&typeof M==='function'&&M(id))return M(id);const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return null;const cards=[...box.querySelectorAll('.queueCard')],i=cards.indexOf(card),ids=sortedQueue();id=String(ids[i]||'');const m=id&&typeof M==='function'?M(id):null;if(m)card.dataset.memberId80=id;return m||null}
function same9(el,m){if(!el?.classList?.contains('profileIdentity80'))return false;const s=src9(m),gender=String(m?.gender||'')==='여'?'여':'남';if(el.dataset.memberId!==String(m?.id||'')||el.dataset.gender!==gender||el.dataset.photo!==(s?'1':'0'))return false;if(s)return String(el.querySelector('img')?.getAttribute('src')||'')===s;return true}
function clearDirect9(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove()}
function isIdentityTarget9(t,card){if(!(t instanceof Element)||!card)return false;const hit=t.closest('.profileIdentity80,.avatar,.profileAvatar53,.queueProfile53,.genderAvatar39,.genderPerson54,.genderPerson57,.genderMini39,.genderMark53,.v54genderText');return !!(hit&&card.contains(hit))}
function canSelect9(){return !!me&&(me?.globalAdmin===true||me?.role==='admin'||me?.role==='manager'||me?.role==='organizer'||me?.tempOrganizer===true)}
function saveDraft9(){try{if(!currentGroupId||!Array.isArray(draft))return;localStorage.setItem('kokmatch_draft_v54_'+String(currentGroupId),JSON.stringify(draft.slice(0,4)))}catch{}}
function selectDraft9(id){if(!canSelect9()||!Array.isArray(draft)||!id)return;const idx=draft.indexOf(id);if(idx>=0)draft[idx]=null;else{const e=draft.findIndex(x=>!x);if(e>=0)draft[e]=id}saveDraft9();try{renderQueue()}catch{}}
function fixMember9(card,m){const cur=[...(card.children||[])].find(x=>x.classList?.contains('profileIdentity80'));if(!same9(cur,m)){clearDirect9(card);card.insertBefore(identity9(m,false),card.firstChild)}card.classList.add('memberIdentityCard80')}
function fixQueue9(card,m){const cur=[...(card.children||[])].find(x=>x.classList?.contains('profileIdentity80'));if(!same9(cur,m)){clearDirect9(card);const ord=card.querySelector('.ord'),d=identity9(m,true);if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.dataset.memberId80=String(m.id||'');card.classList.add('queueIdentityCard80');card.removeAttribute('onclick');card.onclick=null}
function stabilize9(){style9();try{const mb=typeof $==='function'?$('members'):document.getElementById('members');if(mb)[...mb.querySelectorAll('.memberCard')].forEach(c=>{const m=member9(c);if(m)fixMember9(c,m)});const qb=typeof $==='function'?$('queue'):document.getElementById('queue');if(qb)[...qb.querySelectorAll('.queueCard')].forEach(c=>{const m=queueMember9(c);if(m)fixQueue9(c,m)})}catch(e){console.warn('profile stable9',e)}}
let raf9=0,t9a=0,t9b=0;function settle9(){stabilize9();if(!raf9)raf9=requestAnimationFrame(()=>{raf9=0;stabilize9()});clearTimeout(t9a);clearTimeout(t9b);t9a=setTimeout(stabilize9,60);t9b=setTimeout(stabilize9,180)}
const rm9=renderMembers;renderMembers=function(){const r=rm9();settle9();return r};const rq9=renderQueue;renderQueue=function(){const r=rq9();settle9();return r};const ra9=renderAll;renderAll=function(){const r=ra9();settle9();return r};
const mo9=new MutationObserver(()=>settle9());function start9(){style9();const mb=typeof $==='function'?$('members'):document.getElementById('members'),qb=typeof $==='function'?$('queue'):document.getElementById('queue');if(mb)mo9.observe(mb,{childList:true,subtree:true});if(qb)mo9.observe(qb,{childList:true,subtree:true});settle9()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start9,{once:true});else start9();

function routeClick9(e){const t=e.target instanceof Element?e.target:null;if(!t)return;const queue=t.closest('#queue .queueCard');if(queue){const m=queueMember9(queue);e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(!m)return;fixQueue9(queue,m);if(isIdentityTarget9(t,queue)){const id=queue.querySelector('.profileIdentity80');if(id?.dataset.photo==='1'&&typeof window.openProfilePhoto80==='function')window.openProfilePhoto80(id);return}selectDraft9(String(m.id));return}const member=t.closest('#members .memberCard');if(member){const hit=t.closest('.profileIdentity80,.avatar,.profileAvatar53');if(hit&&member.contains(hit)){const m=member9(member);if(!m)return;fixMember9(member,m);const id=member.querySelector('.profileIdentity80');if(id?.dataset.photo==='1'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(typeof window.openProfilePhoto80==='function')window.openProfilePhoto80(id)}}}}
if(!window.__kokmatchAvatarWindowCapture9){window.__kokmatchAvatarWindowCapture9=true;window.addEventListener('click',routeClick9,true)}
if(!window.__kokmatchFix10Bridge9){window.__kokmatchFix10Bridge9=true;const s=document.createElement('script');s.src='/app-v5.4-fix10.js?v=10.0&t='+Date.now();s.async=false;s.onerror=()=>console.error('콕매치 fix10 로드 실패');document.body.appendChild(s)}
})();