(()=>{
'use strict';
if(window.__kokmatchV54Fix19)return;
window.__kokmatchV54Fix19=true;
window.__kokmatchProfileIsolationPatch='19.0';
const PROFILE19='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const photos19=new Map();
let photoGroup19='',photoToken19='',loadSeq19=0,loadBusy19=null,raf19=0,timer19=0;

function esc19(v){return String(v??'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function gender19(m){const g=String(m?.gender||'').trim().toLowerCase();if(g==='여'||g==='여성'||g==='female'||g==='f')return'여';if(g==='남'||g==='남성'||g==='male'||g==='m')return'남';return String(m?.gender||'').includes('여')?'여':'남'}
function member19(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function photo19(m){return String(photos19.get(String(m?.id||''))||'')}
function safeAvatar19(m){const g=gender19(m),female=g==='여',src=photo19(m),name=esc19(m?.name||'프로필');if(src)return `<div class="avatar profileAvatar53 ${female?'female':'male'}"><img src="${esc19(src)}" alt="${name} 프로필" draggable="false"></div>`;return `<div class="avatar genderAvatar39 ${female?'female':'male'}" aria-label="${female?'여성':'남성'}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg></div>`}
function installAvatar19(){try{avatar=safeAvatar19}catch{}try{window.avatar=safeAvatar19}catch{}}

function style19(){if(document.getElementById('v54fix19style'))return;const s=document.createElement('style');s.id='v54fix19style';s.textContent=`
#members .profileIdentity80,#queue .profileIdentity80{position:relative!important;overflow:visible!important;border-radius:50%!important;display:grid!important;place-items:center!important;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
#members .profileIdentity80 img,#queue .profileIdentity80 img{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:50%!important;display:block!important;pointer-events:none!important;-webkit-user-drag:none!important}
#members .profileIdentity80.genderFallback80 svg,#queue .profileIdentity80.genderFallback80 svg{width:24px!important;height:24px!important;display:block!important;fill:currentColor!important}
#members .profileIdentity80.genderFallback80.male,#queue .profileIdentity80.genderFallback80.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}
#members .profileIdentity80.genderFallback80.female,#queue .profileIdentity80.genderFallback80.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
`;document.head.appendChild(s)}
function identity19(m,queue=false){const g=gender19(m),female=g==='여',src=photo19(m),d=document.createElement('div');d.className=`avatar profileIdentity80 genderVisual10 ${src?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.gender=g;d.dataset.photo=src?'1':'0';d.dataset.visual10=`${g}|${src?'1':'0'}|${src}`;if(src){d.setAttribute('role','button');d.setAttribute('tabindex','0');d.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);d.innerHTML=`<img src="${esc19(src)}" alt="${esc19(m?.name||'프로필')} 프로필" draggable="false">`}else{d.setAttribute('aria-label',female?'여성':'남성');d.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg>'}return d}
function clearIdentity19(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove()}
function visibleMembers19(){const all=Array.isArray(S?.members)?S.members:[],q=String(document.getElementById('memberSearchInput46')?.value||'').trim().toLowerCase();const rows=!q?all:all.filter(m=>{let role='';try{role=typeof roleLabel==='function'&&typeof roleOf==='function'?roleLabel(roleOf(m)):''}catch{}return[m?.name,m?.cls,m?.gender,m?.inviter,role,m?.type==='guest'?'게스트':'일반회원'].some(v=>String(v||'').toLowerCase().includes(q))});const p=Math.max(1,Number(document.querySelector('#members .memberPager46 b')?.textContent)||1);return rows.slice((p-1)*10,p*10)}
function decorateMembers19(){const box=document.getElementById('members');if(!box)return;const rows=visibleMembers19(),cards=[...box.querySelectorAll('.memberCard')];cards.forEach((card,i)=>{const m=rows[i];if(!m)return;const id=String(m.id||''),g=gender19(m),src=photo19(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity80'));const good=cur&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0')&&(src?String(cur.querySelector('img')?.getAttribute('src')||'')===src:!!cur.querySelector('svg'));card.dataset.memberId80=id;if(!good){clearIdentity19(card);card.insertBefore(identity19(m,false),card.firstChild)}card.classList.add('memberIdentityCard80')})}
function decorateQueue19(){const box=document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((card,i)=>{const m=member19(ids[i]);if(!m)return;const id=String(m.id||''),g=gender19(m),src=photo19(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity80'));const good=cur&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0')&&(src?String(cur.querySelector('img')?.getAttribute('src')||'')===src:!!cur.querySelector('svg'));card.dataset.memberId80=id;if(!good){clearIdentity19(card);const d=identity19(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.classList.add('queueIdentityCard80')})}
function decorate19(){style19();installAvatar19();decorateMembers19();decorateQueue19()}
function schedule19(){if(!raf19)raf19=requestAnimationFrame(()=>{raf19=0;decorate19()});clearTimeout(timer19);timer19=setTimeout(decorate19,120)}

async function loadProfiles19(force=false){const gid=String(currentGroupId||''),tok=String(T||'');if(!gid||gid==='__global__'||!tok){photos19.clear();photoGroup19='';photoToken19='';schedule19();return}if(!force&&photoGroup19===gid&&photoToken19===tok&&loadBusy19)return loadBusy19;if(!force&&photoGroup19===gid&&photoToken19===tok&&window.__kokmatchProfilesLoaded19===gid)return;const seq=++loadSeq19;photoGroup19=gid;photoToken19=tok;photos19.clear();window.__kokmatchProfilesLoaded19='';schedule19();loadBusy19=(async()=>{try{const u=new URL(PROFILE19);u.searchParams.set('groupId',gid);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+tok},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 사진 조회 실패');if(seq!==loadSeq19||String(currentGroupId||'')!==gid||String(T||'')!==tok)return;const p=x?.profiles&&typeof x.profiles==='object'?x.profiles:{};for(const [id,v] of Object.entries(p)){const src=String(v?.image||'');if(src)photos19.set(String(id),src)}window.__kokmatchProfilesLoaded19=gid;schedule19()}catch(e){console.warn('profile isolation19',e);if(seq===loadSeq19){photos19.clear();window.__kokmatchProfilesLoaded19=gid;schedule19()}}finally{if(seq===loadSeq19)loadBusy19=null}})();return loadBusy19}
function ensure19(){const gid=String(currentGroupId||''),tok=String(T||'');if(gid!==photoGroup19||tok!==photoToken19||window.__kokmatchProfilesLoaded19!==gid)loadProfiles19(false);schedule19()}
window.refreshProfiles19=()=>loadProfiles19(true);

try{const rm=renderMembers;renderMembers=function(){const r=rm();ensure19();return r};const rq=renderQueue;renderQueue=function(){const r=rq();ensure19();return r};const ra=renderAll;renderAll=function(){const r=ra();ensure19();return r}}catch{}
const changePrev19=window.changeProfile53;if(typeof changePrev19==='function')window.changeProfile53=async function(...a){const r=await changePrev19.apply(this,a);await loadProfiles19(true);return r};
const deletePrev19=window.deleteProfile53;if(typeof deletePrev19==='function')window.deleteProfile53=async function(...a){const r=await deletePrev19.apply(this,a);await loadProfiles19(true);return r};
try{changeProfile53=window.changeProfile53;deleteProfile53=window.deleteProfile53}catch{}

const mo19=new MutationObserver(schedule19);function boot19(){style19();installAvatar19();for(const id of ['members','queue']){const el=document.getElementById(id);if(el)mo19.observe(el,{childList:true,subtree:true})}ensure19()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot19,{once:true});else boot19();
})();