(()=>{
if(window.__kokmatchV55Fix2)return;
window.__kokmatchV55Fix2=true;window.__kokmatchVersionLock='5.5';window.__kokmatchV55Patch='2.0';window.__kokmatchFeedbackPatch='5.5.2';window.__kokmatchProfilePatch='5.5.2';
const FEEDBACK='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-feedback-v54';
const PROFILE='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const profileLocal=new Map();let profileBusy=false,lastPrivileged=false,reconcileBusy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function version(){window.__kokmatchVersionLock='5.5';document.documentElement.dataset.kokmatchVersion='5.5';document.title='콕매치 v5.5';const x=document.getElementById('currentVersion52');if(x)x.textContent='v5.5'}
function css(){if(document.getElementById('v552style'))return;const s=document.createElement('style');s.id='v552style';s.textContent=`
.feedbackBtn16,.feedbackSend55,.feedbackInbox55{display:none!important}.topActions552{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:5px!important;flex:0 0 auto!important}.topActions552 .logout,.feedbackSend552,.feedbackInbox552{width:100%;min-width:78px;white-space:nowrap;text-align:center}.feedbackSend552,.feedbackInbox552{border:1px solid #ffffff55;background:#ffffff18;color:#fff;border-radius:999px;padding:7px 10px;font-weight:850;font-size:12px;cursor:pointer}.feedbackInbox552{background:#ffffff2a}.feedbackArea552{width:100%;min-height:112px;padding:12px;border:1px solid var(--line);border-radius:12px;box-sizing:border-box;font:inherit;line-height:1.5;resize:vertical}.feedbackCount552{text-align:right;font-size:11px;color:var(--mut);margin-top:4px}.feedbackItem552{padding:11px 0;border-bottom:1px solid var(--line)}.feedbackMeta552{display:flex;justify-content:space-between;gap:8px;font-size:11px;color:var(--mut)}.feedbackText552{margin-top:6px;white-space:pre-wrap;word-break:break-word;line-height:1.5}.profileStatus552{font-size:12px;font-weight:800;margin-top:7px;color:#667085}.profileStatus552.bad{color:#b42318}@media(max-width:359px){.topActions552{gap:4px!important}.topActions552 .logout,.feedbackSend552,.feedbackInbox552{min-width:68px;padding:6px 7px;font-size:11px}}
`;document.head.appendChild(s)}
function privilege(){const r=String(window.me?.role||'');const yes=!!window.me?.globalAdmin||r==='admin'||r==='manager'||r==='organizer';const low=r==='member'||r==='guest'||r==='scheduler';if(yes)lastPrivileged=true;else if(low)lastPrivileged=false;return yes||(!r&&!!window.T&&lastPrivileged)}
function roleName(r){return ({admin:'개발자',manager:'모임장',organizer:'운영진',member:'일반',guest:'게스트',scheduler:'편성자'})[String(r||'')]||String(r||'-')}
function reconcileFeedback(){css();const row=document.querySelector('.toprow');if(!row)return;const logout=row.querySelector('.logout');if(!logout)return;let a=row.querySelector('.topActions552,.topActions55,.topActions16');if(!a){a=document.createElement('div');logout.replaceWith(a);a.appendChild(logout)}a.classList.add('topActions552');let send=a.querySelector('.feedbackSend552');if(!send){send=document.createElement('button');send.type='button';send.className='feedbackSend552';send.textContent='건의사항';a.appendChild(send)}send.onclick=()=>window.openFeedback552();let inbox=a.querySelector('.feedbackInbox552');if(privilege()){if(!inbox){inbox=document.createElement('button');inbox.type='button';inbox.className='feedbackInbox552';inbox.textContent='받은 건의사항';a.appendChild(inbox)}inbox.onclick=()=>window.openFeedbackInbox552()}else if(inbox)inbox.remove()}
window.__kokmatchReconcileFeedback552=reconcileFeedback;
window.feedbackCount552=function(){const ta=document.getElementById('feedbackContent552'),c=document.getElementById('feedbackCount552');if(!ta||!c)return;let a=Array.from(ta.value||'');if(a.length>100){a=a.slice(0,100);ta.value=a.join('')}c.textContent=`${a.length} / 100`};
window.openFeedback552=function(){if(typeof openModal!=='function')return;openModal(`<h3>건의사항</h3><div class="note">받는 대상을 선택하고 100자 이내로 작성해주세요.</div><div class="field"><label>받는 대상</label><select id="feedbackTarget552"><option value="">수신 대상 선택</option><option value="developer">개발자</option><option value="manager">모임장</option><option value="organizer">운영진</option></select></div><div class="field"><label>건의내용</label><textarea id="feedbackContent552" class="feedbackArea552" maxlength="100" placeholder="불편한 점이나 추가되었으면 하는 기능을 적어주세요." oninput="feedbackCount552()"></textarea><div id="feedbackCount552" class="feedbackCount552">0 / 100</div></div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">취소</button><button id="feedbackSendBtn552" class="btn pri" type="button" onclick="sendFeedback552()">보내기</button></div>`)};
window.sendFeedback552=async function(){const target=document.getElementById('feedbackTarget552')?.value||'',content=String(document.getElementById('feedbackContent552')?.value||'').trim(),btn=document.getElementById('feedbackSendBtn552');if(!target)return alert('받는 대상을 선택해주세요.');if(!content)return alert('건의내용을 입력해주세요.');if(Array.from(content).length>100)return alert('건의내용은 100자 이내로 입력해주세요.');if(!window.T)return alert('로그인이 필요합니다.');if(btn){btn.disabled=true;btn.textContent='보내는 중…'}try{const r=await fetch(FEEDBACK,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({groupId:String(window.currentGroupId||''),targetRole:target,content}),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'건의사항 전송에 실패했습니다.');closeModal();alert('건의사항을 전송했습니다.')}catch(e){if(typeof showError==='function')showError(e);else alert(e?.message||String(e))}finally{if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent='보내기'}}};
window.openFeedbackInbox552=async function(){if(!privilege())return alert('받은 건의사항을 볼 권한이 없습니다.');if(typeof openModal!=='function')return;openModal('<h3>받은 건의사항</h3><div class="note">불러오는 중…</div>');try{const r=await fetch(FEEDBACK,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({action:'list',groupId:String(window.currentGroupId||'')}),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'건의사항을 불러오지 못했습니다.');const items=Array.isArray(x.items)?x.items:[],html=items.length?items.map(i=>`<div class="feedbackItem552"><div class="feedbackMeta552"><b>${esc(i.sender_name||'이름 없음')} · ${esc(roleName(i.sender_role))}</b><span>${esc(new Date(i.created_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</span></div><div class="feedbackText552">${esc(i.content)}</div></div>`).join(''):'<div class="note">받은 건의사항이 없습니다.</div>';openModal(`<h3>받은 건의사항</h3><div style="max-height:58vh;overflow:auto">${html}</div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>`)}catch(e){if(typeof showError==='function')showError(e);else alert(e?.message||String(e))}};
function installLoginGuard(){const box=document.getElementById('loginBox');if(!box||box.dataset.v552guard==='1')return;box.dataset.v552guard='1';const d=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');if(d?.get&&d?.set){Object.defineProperty(box,'innerHTML',{configurable:true,get(){return d.get.call(this)},set(v){const a=document.activeElement,typing=a instanceof HTMLInputElement&&this.contains(a);if(typing&&Date.now()>(window.__kokmatchLoginRenderAllow552||0))return;d.set.call(this,v)}})}const rep=box.replaceChildren.bind(box);box.replaceChildren=function(...args){const a=document.activeElement,typing=a instanceof HTMLInputElement&&box.contains(a);if(typing&&Date.now()>(window.__kokmatchLoginRenderAllow552||0))return;return rep(...args)};box.addEventListener('pointerdown',e=>{if(e.target instanceof Element&&e.target.closest('button'))window.__kokmatchLoginRenderAllow552=Date.now()+2500},true);box.addEventListener('keydown',e=>{if(e.key==='Enter')window.__kokmatchLoginRenderAllow552=Date.now()+2500},true);box.addEventListener('focusin',e=>{if(e.target instanceof HTMLInputElement)e.target.style.fontSize='16px'})}
function timeout(p,ms,msg){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(msg)),ms))])}
function imageFromFile(file){return new Promise((res,rej)=>{const url=URL.createObjectURL(file),im=new Image();im.onload=()=>res({src:im,cleanup:()=>URL.revokeObjectURL(url)});im.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('선택한 사진을 읽지 못했습니다. 다른 사진으로 다시 시도해주세요.'))};im.src=url})}
async function imageSource(file){if(typeof createImageBitmap==='function')try{const b=await timeout(createImageBitmap(file),6000,'사진 처리 시간이 초과되었습니다.');return{src:b,cleanup:()=>{try{b.close()}catch{}}}}catch{}return timeout(imageFromFile(file),8000,'사진 처리 시간이 초과되었습니다.')}
function canvasJpeg(src,maxSide,q,square=false){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)throw new Error('사진 크기를 확인하지 못했습니다.');let cw,ch,sx=0,sy=0,sw=w,sh=h;if(square){const n=Math.min(w,h);sx=(w-n)/2;sy=(h-n)/2;sw=sh=n;cw=ch=maxSide}else{const sc=Math.min(1,maxSide/Math.max(w,h));cw=Math.max(1,Math.round(w*sc));ch=Math.max(1,Math.round(h*sc))}const c=document.createElement('canvas');c.width=cw;c.height=ch;const g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');g.fillStyle='#fff';g.fillRect(0,0,cw,ch);g.drawImage(src,sx,sy,sw,sh,0,0,cw,ch);return c.toDataURL('image/jpeg',q)}
function thumb(src){let d=canvasJpeg(src,256,.82,true);for(const q of [.72,.62,.52,.44]){if(d.length<=210000)break;d=canvasJpeg(src,256,q,true)}if(d.length>220000)throw new Error('프로필 사진 용량을 줄이지 못했습니다.');return d}
function full(src){let d=canvasJpeg(src,1800,.86,false);for(const q of [.8,.74,.68,.62]){if(d.length<=2350000)break;d=canvasJpeg(src,1800,q,false)}if(d.length>2450000)d=canvasJpeg(src,1400,.72,false);return d.length<=2500000?d:''}
function status(text,bad=false){const card=document.getElementById('profileCard53');if(!card)return;let s=card.querySelector('.profileStatus552');if(!s){s=document.createElement('div');s.className='profileStatus552';card.appendChild(s)}s.textContent=text;s.classList.toggle('bad',bad)}
async function postProfile(body){const r=await fetch(PROFILE,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`프로필 저장 실패 (${r.status})`);return x}
async function verifyProfile(gid,id){for(let n=0;n<2;n++){const u=new URL(PROFILE);u.searchParams.set('groupId',gid);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store'}),x=await r.json().catch(()=>({}));if(r.ok&&String(x.profiles?.[id]?.image||'').startsWith('data:image/'))return String(x.profiles[id].image);await new Promise(r=>setTimeout(r,120))}throw new Error('프로필 사진 저장 확인에 실패했습니다. 다시 시도해주세요.')}
const avatarPrev=typeof window.avatar==='function'?window.avatar:(typeof avatar==='function'?avatar:null);
function avatar552(m){const id=String(m?.id||''),key=String(window.currentGroupId||'')+'|'+id,img=profileLocal.get(key);if(img)return `<div class="avatar profileAvatar53"><img src="${img}" alt="${esc(m?.name||'프로필')} 프로필"></div>`;return avatarPrev?String(avatarPrev(m)||''):''}
window.avatar=avatar552;try{avatar=avatar552}catch{}
function applyProfile(id,img){const key=String(window.currentGroupId||'')+'|'+id;profileLocal.set(key,img);try{if(typeof renderMembers==='function')renderMembers();if(typeof renderQueue==='function')renderQueue();if(window.currentView==='settings'&&typeof renderSettings==='function')renderSettings()}catch{}setTimeout(()=>{const p=document.querySelector('#profileCard53 .profilePreview53');if(p)p.innerHTML=`<img src="${img}" alt="내 프로필 사진">`;status('프로필 사진 저장 완료')},0)}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file||profileBusy)return;if(!window.T)return alert('로그인이 필요합니다.');const gid=String(window.currentGroupId||'').trim();if(!gid||gid==='__global__')return alert('프로필 사진을 적용할 모임을 선택해주세요.');if(file.size>30*1024*1024)return alert('사진은 30MB 이하만 선택할 수 있습니다.');profileBusy=true;const label=document.querySelector('label[for="profileFile53"]');if(label){label.textContent='저장 중…';label.style.pointerEvents='none'}status('사진 변환 중…');try{const obj=await imageSource(file);let t='',f='';try{t=thumb(obj.src);try{f=full(obj.src)}catch{f=''}}finally{obj.cleanup()}status('서버에 저장 중…');const saved=await postProfile({action:'save_profile',groupId:gid,image:t,fullImage:f});const id=String(saved.memberId||'').trim();if(!id)throw new Error('저장된 회원정보를 확인하지 못했습니다.');const persisted=await verifyProfile(gid,id);applyProfile(id,persisted||t);status(f&&saved.fullSaved?'프로필 사진 저장 완료 · 고화질 원본 저장됨':'프로필 사진 저장 완료');if(label)label.textContent='저장됨';setTimeout(()=>{const l=document.querySelector('label[for="profileFile53"]');if(l){l.textContent='사진 변경';l.style.pointerEvents=''}},900)}catch(e){status(e?.message||'프로필 사진 저장 실패',true);if(typeof showError==='function')showError(e);else alert(e?.message||String(e));if(label){label.textContent='사진 변경';label.style.pointerEvents=''}}finally{profileBusy=false;if(input)input.value=''}};
try{changeProfile53=window.changeProfile53}catch{}
if(!window.__kokmatchProfileCapture552){window.__kokmatchProfileCapture552=true;document.addEventListener('change',e=>{const t=e.target;if(!(t instanceof HTMLInputElement)||t.id!=='profileFile53')return;e.stopImmediatePropagation();window.changeProfile53(t)},true)}
function reconcile(){if(reconcileBusy)return;reconcileBusy=true;requestAnimationFrame(()=>{try{version();css();installLoginGuard();reconcileFeedback()}finally{reconcileBusy=false}})}
const oldRH=typeof window.renderHeader==='function'?window.renderHeader:null;if(oldRH)window.renderHeader=function(){const r=oldRH.apply(this,arguments);reconcile();return r};
const oldRA=typeof window.renderAll==='function'?window.renderAll:null;if(oldRA)window.renderAll=function(){const r=oldRA.apply(this,arguments);reconcile();return r};
function boot(){version();css();installLoginGuard();reconcileFeedback();const mo=new MutationObserver(reconcile);mo.observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{version();reconcileFeedback();installLoginGuard()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();