(()=>{
if(window.__kokmatchV56)return;window.__kokmatchV56=true;window.__kokmatchV56Patch='1.2';
const VERSION='5.6',PROFILE='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53',AUTH='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-auth-v38';
let cacheGroup='',profiles={},loadSeq=0,lastGroup='',versionGuardBusy=false,switchBusy56=false;
const token=()=>String(window.T||'');const gid=()=>String(window.currentGroupId||'');
const esc56=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function gender56(m){const g=String(m?.gender||'').trim().toLowerCase();return ['여','여자','여성','f','female'].includes(g)?'여':'남'}
function photo56(m){const g=gid(),id=String(m?.id||'');return cacheGroup===g?String(profiles?.[id]?.image||''):''}
function avatar56(m){const p=photo56(m),female=gender56(m)==='여';return p?`<div class="avatar profileAvatar53 ${female?'female':'male'}"><img src="${p}" alt="${esc56(m?.name||'프로필')} 프로필"></div>`:`<div class="avatar ${female?'female':'male'}">●</div>`}
function lockAvatar56(){try{Object.defineProperty(window,'avatar',{configurable:true,enumerable:true,get:()=>avatar56,set:()=>{}})}catch{try{window.avatar=avatar56;avatar=avatar56}catch{}}}
function writeVersion56(){if(versionGuardBusy)return;versionGuardBusy=true;try{if(document.documentElement.dataset.kokmatchVersion!==VERSION)document.documentElement.dataset.kokmatchVersion=VERSION;if(document.title!=='콕매치 v'+VERSION)document.title='콕매치 v'+VERSION;for(const id of ['currentVersion51','currentVersion52']){const e=document.getElementById(id);if(e&&e.textContent!=='v'+VERSION)e.textContent='v'+VERSION}}finally{versionGuardBusy=false}}
function lockVersion56(){try{Object.defineProperty(window,'__kokmatchVersionLock',{configurable:true,enumerable:true,get:()=>VERSION,set:()=>{}})}catch{window.__kokmatchVersionLock=VERSION}writeVersion56()}
const versionMo56=new MutationObserver(()=>queueMicrotask(writeVersion56));function startVersionGuard56(){lockVersion56();try{versionMo56.observe(document.documentElement,{attributes:true,attributeFilter:['data-kokmatch-version']});const t=document.querySelector('title');if(t)versionMo56.observe(t,{childList:true,subtree:true,characterData:true})}catch{}}
function memberById56(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function memberForCard56(card){let id='';const p=card?.querySelector?.('.pairBtn')?.getAttribute('onclick')||'';const hit=p.match(/openPairs\(['"]([^'"]+)['"]\)/);if(hit)id=hit[1];if(!id)id=String(card?.dataset?.memberId80||card?.dataset?.memberId56||'');const m=memberById56(id);if(m){card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}return m}
function queueMembers56(){try{return typeof sortedQueue==='function'?sortedQueue().map(id=>memberById56(id)):[]}catch{return []}}
function makeIdentity56(m,queue=false){const p=photo56(m),female=gender56(m)==='여',d=document.createElement('div');d.className=`avatar profileIdentity80 genderVisual10 ${p?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.memberId56=String(m?.id||'');d.dataset.gender=female?'여':'남';d.dataset.photo=p?'1':'0';d.setAttribute('aria-label',p?`${String(m?.name||'회원')} 프로필 사진 크게 보기`:(female?'여성':'남성'));if(p){d.setAttribute('role','button');d.setAttribute('tabindex','0');const im=document.createElement('img');im.src=p;im.alt=`${String(m?.name||'프로필')} 프로필`;d.appendChild(im)}else d.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg>';return d}
function directIdentity56(card){return [...(card?.children||[])].find(x=>x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('queueProfile53'))}
function sameIdentity56(el,m){if(!el||!m)return false;const p=photo56(m),g=gender56(m);return String(el.dataset?.memberId||el.dataset?.memberId56||'')===String(m.id)&&String(el.dataset?.gender||'')===g&&String(el.dataset?.photo||'0')===(p?'1':'0')&&(!p||String(el.querySelector?.('img')?.getAttribute('src')||'')===p)}
function clearDirect56(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText')||x.classList?.contains('queueProfile53'))x.remove()}
function fixMemberCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);card.insertBefore(makeIdentity56(m,false),card.firstChild)}card.dataset.memberId56=String(m.id)}
function fixQueueCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);const d=makeIdentity56(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}
function patchSettingsPhoto56(){try{const card=document.getElementById('profileCard53');if(!card)return;const id=String(window.me?.memberId||''),p=cacheGroup===gid()?String(profiles?.[id]?.image||''):'';const prev=card.querySelector('.profilePreview53');if(prev){if(p){const cur=prev.querySelector('img')?.getAttribute('src')||'';if(cur!==p)prev.innerHTML=`<img src="${p}" alt="내 프로필 사진">`}else if(prev.querySelector('img')){const m=memberById56(id);prev.innerHTML=m?avatar56(m):''}}const del=card.querySelector('.profileBtns53 .btn.ghost');if(p&&!del){const box=card.querySelector('.profileBtns53');if(box)box.insertAdjacentHTML('beforeend','<button class="btn ghost" type="button" onclick="deleteProfile53()">기본 사진으로</button>')}else if(!p&&del)del.remove()}catch(e){console.warn('v5.6 settings photo',e)}}
function canonicalize56(){lockVersion56();lockAvatar56();try{document.querySelectorAll('#members .memberCard').forEach(card=>fixMemberCard56(card,memberForCard56(card)));const ms=queueMembers56(),cards=[...document.querySelectorAll('#queue .queueCard')];cards.forEach((card,i)=>fixQueueCard56(card,ms[i]||null));patchSettingsPhoto56();decorateLogin56()}catch(e){console.warn('v5.6 identity',e)}}
async function loadProfiles56(group=gid(),force=false){const g=String(group||'');if(!g||g==='__global__'||!token())return;if(g!==cacheGroup){cacheGroup=g;profiles={};canonicalize56()}else if(!force&&Object.keys(profiles).length)return;const seq=++loadSeq;const before=profiles;try{const u=new URL(PROFILE);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+token()},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 조회 실패');if(seq!==loadSeq||g!==gid())return;const incoming=x&&typeof x.profiles==='object'&&x.profiles?x.profiles:{};cacheGroup=g;profiles=Object.keys(incoming).length?incoming:before;canonicalize56();try{renderMembers();renderQueue();if(window.currentView==='settings'&&typeof renderSettings==='function')renderSettings()}catch{};requestAnimationFrame(canonicalize56)}catch(e){profiles=before;console.warn('v5.6 profiles',e);canonicalize56()}}
function watch56(){const g=gid();if(g!==lastGroup){lastGroup=g;cacheGroup=g;profiles={};loadSeq++;lockAvatar56();canonicalize56();if(g&&g!=='__global__'&&token())loadProfiles56(g,true)}else if(g&&g!=='__global__'&&token()&&cacheGroup===g&&!Object.keys(profiles).length)loadProfiles56(g,true)}
function wrap56(name){try{const f=window[name];if(typeof f!=='function'||f.__v56)return;const w=function(){const r=f.apply(this,arguments);queueMicrotask(()=>{watch56();canonicalize56()});return r};w.__v56=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}catch{}}
['renderMembers','renderQueue','renderAll','renderHeader','renderSettings'].forEach(wrap56);
function seedOwnPhoto56(){try{const id=String(window.me?.memberId||''),g=gid(),src=document.querySelector('#profileCard53 .profilePreview53 img')?.getAttribute('src')||'';if(id&&g&&src&&!src.startsWith('blob:')){if(cacheGroup!==g){cacheGroup=g;profiles={}}profiles[id]={...(profiles[id]||{}),image:src,updatedAt:new Date().toISOString()}}}catch{}}
for(const n of ['changeProfile53','deleteProfile53']){try{const f=window[n];if(typeof f==='function'&&!f.__v56){const w=async function(){const id=String(window.me?.memberId||''),g=gid();const r=await f.apply(this,arguments);if(n==='changeProfile53')seedOwnPhoto56();else if(cacheGroup===g&&id)delete profiles[id];canonicalize56();await loadProfiles56(g,true);canonicalize56();return r};w.__v56=true;window[n]=w;try{eval(`${n}=window[n]`)}catch{}}}catch{}}
function decorateLogin56(){try{const box=document.getElementById('loginBox');if(!box)return;const h=String(box.querySelector('h2')?.textContent||'');if(h==='회원 선택'){const note=box.querySelector('.note');if(note)note.textContent='같은 이름의 회원이 있습니다. 이름과 출생연도를 확인하고 본인을 선택해주세요.';box.querySelectorAll('.choiceList .choiceBtn').forEach(b=>{b.querySelector('small')?.remove();const s=b.querySelector('span');if(s){const year=(String(s.textContent||'').match(/\d{4}년생|출생연도 미등록/)||[])[0]||'';s.textContent=year}})}else if(/모임 PIN/.test(h)){box.querySelectorAll('.loginMember33 small').forEach(x=>x.remove())}}catch{}}
function wait56(ms){return new Promise(r=>setTimeout(r,ms))}
async function postAuth56(body,tok=token()){const r=await fetch(AUTH,{method:'POST',headers:{'content-type':'application/json',...(tok?{authorization:'Bearer '+tok}:{})},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'모임 전환에 실패했습니다.');return x}
function switchUi56(on){const b=document.getElementById('groupBtn');if(!b)return;b.disabled=!!on;b.classList.toggle('groupSwitching12',!!on);if(on){b.dataset.v56old=b.textContent||'';b.textContent='모임 변경 중…'}else{try{if(typeof renderHeader==='function')renderHeader()}catch{};if(b.textContent==='모임 변경 중…'&&b.dataset.v56old)b.textContent=b.dataset.v56old;delete b.dataset.v56old}}
async function loadTarget56(target){let last=null;for(let i=0;i<2;i++){try{await loadState(true);if(String(window.currentGroupId||'')===target&&String(window.group?.groupId||'')===target)return true;last=new Error('선택한 모임 정보를 불러오지 못했습니다.')}catch(e){last=e}if(i===0)await wait56(280)}throw last||new Error('모임 정보를 불러오지 못했습니다.')}
async function switchStable56(target,isAdmin=false,view){target=String(target||'');if(!target||switchBusy56)return;if(target===gid()){try{closeModal()}catch{};return}const oldG=gid(),oldT=token(),oldView=String(view||window.currentView||'members');switchBusy56=true;window.__kokmatchGroupSwitching12=true;switchUi56(true);try{if(!isAdmin){const x=await postAuth56({action:'switch_group',groupId:target},oldT);if(x.token){window.T=x.token;try{T=x.token}catch{};localStorage.setItem(typeof TOKEN_KEY!=='undefined'?TOKEN_KEY:'kokmatch_token',x.token)}target=String(x.groupId||target)}window.currentGroupId=target;try{currentGroupId=target}catch{};localStorage.setItem(typeof GROUP_KEY!=='undefined'?GROUP_KEY:'kokmatch_group',target);try{closeModal()}catch{};cacheGroup=target;profiles={};lastGroup='';loadSeq++;await loadTarget56(target);await loadProfiles56(target,true).catch(()=>{});try{if(oldView&&oldView!=='members'&&typeof goView==='function')goView(oldView);else if(typeof goView==='function')goView('members')}catch{};try{if(oldView==='members'&&typeof window.memberPageGo46==='function')window.memberPageGo46(1)}catch{};window.scrollTo?.(0,0);canonicalize56();return true}catch(e){console.warn('v5.6 group switch',e);try{window.T=oldT;T=oldT}catch{};window.currentGroupId=oldG;try{currentGroupId=oldG}catch{};if(oldT)localStorage.setItem(typeof TOKEN_KEY!=='undefined'?TOKEN_KEY:'kokmatch_token',oldT);if(oldG)localStorage.setItem(typeof GROUP_KEY!=='undefined'?GROUP_KEY:'kokmatch_group',oldG);cacheGroup=oldG;profiles={};lastGroup='';loadSeq++;try{await loadState(true)}catch{};try{if(oldView&&typeof goView==='function')goView(oldView)}catch{};if(typeof showError==='function')showError(e);else alert(e?.message||String(e));return false}finally{switchBusy56=false;window.__kokmatchGroupSwitching12=false;switchUi56(false);watch56();canonicalize56()}}
function installSwitch56(){try{if(window.switchOwnGroup38?.__v56stable)return;const own=async id=>switchStable56(id,false);own.__v56stable=true;window.switchOwnGroup38=own;try{switchOwnGroup38=own}catch{};const adm=async(id,view='members')=>switchStable56(id,true,view);adm.__v56stable=true;window.adminSwitchGroup38=adm;try{adminSwitchGroup38=adm}catch{};const sg=(id,view='members')=>window.me?.globalAdmin===true?adm(id,view):own(id);sg.__v56stable=true;window.switchGroup=sg;try{switchGroup=sg}catch{}}catch(e){console.warn('v5.6 switch install',e)}}
let raf=0;const mo=new MutationObserver(()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;canonicalize56()})});function start56(){startVersionGuard56();lockAvatar56();installSwitch56();const m=document.getElementById('members'),q=document.getElementById('queue'),l=document.getElementById('loginBox');if(m)mo.observe(m,{childList:true,subtree:true});if(q)mo.observe(q,{childList:true,subtree:true});if(l)mo.observe(l,{childList:true,subtree:true});watch56();canonicalize56()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start56,{once:true});else start56();
setInterval(()=>{lockVersion56();lockAvatar56();installSwitch56();watch56();decorateLogin56()},200);
})();