(()=>{
if(window.__kokmatchV55Fix1)return;window.__kokmatchV55Fix1=true;window.__kokmatchVersionLock='5.5';window.__kokmatchV55Patch='1.0';
const FEEDBACK55='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-feedback-v54';
const PROFILE55='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const profileOverride55=new Map();let profileBusy55=false;
function esc55(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function enforceVersion55(){window.__kokmatchVersionLock='5.5';document.documentElement.dataset.kokmatchVersion='5.5';if(document.title!=='콕매치 v5.5')document.title='콕매치 v5.5';const v=document.getElementById('currentVersion52');if(v&&v.textContent!=='v5.5')v.textContent='v5.5'}
function style55(){if(document.getElementById('v55fix1style'))return;const s=document.createElement('style');s.id='v55fix1style';s.textContent=`
.topActions55{display:flex;flex-direction:column;align-items:stretch;gap:5px;flex:0 0 auto}.topActions55 .logout,.feedbackSend55,.feedbackInbox55{white-space:nowrap;width:100%;min-width:76px;text-align:center}.feedbackSend55,.feedbackInbox55{border:1px solid #ffffff55;background:#ffffff18;color:#fff;border-radius:999px;padding:7px 10px;font-weight:850;font-size:12px;cursor:pointer}.feedbackInbox55{background:#ffffff2a}.feedback55area{width:100%;min-height:112px;padding:12px;border:1px solid var(--line);border-radius:12px;box-sizing:border-box;font:inherit;line-height:1.5;resize:vertical}.feedback55count{text-align:right;font-size:11px;color:var(--mut);margin-top:4px}.feedback55item{padding:11px 0;border-bottom:1px solid var(--line)}.feedback55meta{display:flex;justify-content:space-between;gap:8px;font-size:11px;color:var(--mut)}.feedback55content{margin-top:6px;white-space:pre-wrap;word-break:break-word;line-height:1.5}.profileStatus55{font-size:12px;font-weight:800;margin-top:7px;color:#667085}@media(max-width:359px){.topActions55{gap:4px}.topActions55 .logout,.feedbackSend55,.feedbackInbox55{min-width:68px;padding:6px 7px;font-size:11px}}
`;document.head.appendChild(s)}
function canInbox55(){const r=String(me?.role||'');return !!me?.globalAdmin||r==='admin'||r==='manager'||r==='organizer'}
function role55(r){return ({admin:'개발자',manager:'모임장',organizer:'운영진',member:'일반',guest:'게스트',scheduler:'편성자'})[String(r||'')]||String(r||'-')}
function ensureFeedback55(){style55();const row=document.querySelector('.toprow');if(!row)return;const logout=row.querySelector('.logout');if(!logout)return;let actions=row.querySelector('.topActions55,.topActions16');if(!actions){actions=document.createElement('div');actions.className='topActions55';logout.replaceWith(actions);actions.appendChild(logout)}else actions.classList.add('topActions55');let send=actions.querySelector('.feedbackSend55');if(!send){send=actions.querySelector('.feedbackBtn16:not(.feedbackInbox17)');if(!send){send=document.createElement('button');actions.appendChild(send)}send.className='feedbackSend55';send.type='button';send.textContent='건의사항'}send.onclick=()=>window.openFeedback55();let inbox=actions.querySelector('.feedbackInbox55,.feedbackInbox17');if(canInbox55()){if(!inbox){inbox=document.createElement('button');actions.appendChild(inbox)}inbox.className='feedbackInbox55';inbox.type='button';inbox.textContent='받은 건의사항';inbox.onclick=()=>window.openFeedbackInbox55()}else inbox?.remove()}
window.feedbackCount55=function(){const ta=document.getElementById('feedbackContent55'),c=document.getElementById('feedbackCount55');if(!ta||!c)return;let a=Array.from(ta.value||'');if(a.length>100){a=a.slice(0,100);ta.value=a.join('')}c.textContent=`${a.length} / 100`};
window.openFeedback55=function(){if(typeof openModal!=='function')return;openModal(`<h3>건의사항</h3><div class="note">받는 대상을 선택하고 100자 이내로 작성해주세요.</div><div class="field"><label>받는 대상</label><select id="feedbackTarget55"><option value="">수신 대상 선택</option><option value="developer">개발자</option><option value="manager">모임장</option><option value="organizer">운영진</option></select></div><div class="field"><label>건의내용</label><textarea id="feedbackContent55" class="feedback55area" maxlength="100" placeholder="불편한 점이나 추가되었으면 하는 기능을 적어주세요." oninput="feedbackCount55()"></textarea><div id="feedbackCount55" class="feedback55count">0 / 100</div></div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">취소</button><button id="feedbackSendBtn55" class="btn pri" type="button" onclick="sendFeedback55()">보내기</button></div>`)};
window.sendFeedback55=async function(){const target=document.getElementById('feedbackTarget55')?.value||'',content=String(document.getElementById('feedbackContent55')?.value||'').trim(),btn=document.getElementById('feedbackSendBtn55');if(!target)return alert('받는 대상을 선택해주세요.');if(!content)return alert('건의내용을 입력해주세요.');if(Array.from(content).length>100)return alert('건의내용은 100자 이내로 입력해주세요.');if(!T)return alert('로그인이 필요합니다.');if(btn){btn.disabled=true;btn.textContent='보내는 중…'}try{const r=await fetch(FEEDBACK55,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({groupId:String(currentGroupId||''),targetRole:target,content}),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'건의사항 전송에 실패했습니다.');closeModal();alert('건의사항을 전송했습니다.')}catch(e){if(typeof showError==='function')showError(e);else alert(e?.message||String(e))}finally{if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent='보내기'}}};
window.openFeedbackInbox55=async function(){if(!canInbox55())return alert('받은 건의사항을 볼 권한이 없습니다.');if(typeof openModal!=='function')return;openModal('<h3>받은 건의사항</h3><div class="note">불러오는 중…</div>');try{const r=await fetch(FEEDBACK55,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({action:'list',groupId:String(currentGroupId||'')}),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'건의사항을 불러오지 못했습니다.');const items=Array.isArray(x.items)?x.items:[],html=items.length?items.map(i=>`<div class="feedback55item"><div class="feedback55meta"><b>${esc55(i.sender_name||'이름 없음')} · ${esc55(role55(i.sender_role))}</b><span>${esc55(new Date(i.created_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</span></div><div class="feedback55content">${esc55(i.content)}</div></div>`).join(''):'<div class="note">받은 건의사항이 없습니다.</div>';openModal(`<h3>받은 건의사항</h3><div style="max-height:58vh;overflow:auto">${html}</div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>`)}catch(e){if(typeof showError==='function')showError(e);else alert(e?.message||String(e))}};
function installLoginGuard55(){const box=document.getElementById('loginBox');if(!box||box.dataset.v55guard==='1')return;box.dataset.v55guard='1';const desc=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');if(desc?.get&&desc?.set){Object.defineProperty(box,'innerHTML',{configurable:true,get(){return desc.get.call(this)},set(v){const active=document.activeElement,typing=active instanceof HTMLInputElement&&this.contains(active);if(typing&&Date.now()>(window.__kokmatchLoginRenderAllow55||0))return;desc.set.call(this,v)}})}const rep=box.replaceChildren.bind(box);box.replaceChildren=function(...a){const active=document.activeElement,typing=active instanceof HTMLInputElement&&box.contains(active);if(typing&&Date.now()>(window.__kokmatchLoginRenderAllow55||0))return;return rep(...a)};box.addEventListener('pointerdown',e=>{if((e.target instanceof Element)&&e.target.closest('button'))window.__kokmatchLoginRenderAllow55=Date.now()+2500},true);box.addEventListener('keydown',e=>{if(e.key==='Enter')window.__kokmatchLoginRenderAllow55=Date.now()+2500},true);box.addEventListener('focusin',e=>{if(e.target instanceof HTMLInputElement){e.target.style.fontSize='16px';window.__kokmatchLoginTyping55=true}});box.addEventListener('focusout',()=>setTimeout(()=>{const a=document.activeElement;window.__kokmatchLoginTyping55=!!(a instanceof HTMLInputElement&&box.contains(a))},0))}
function resolveId55(){const x=typeof window.resolveProfileMemberId54==='function'?String(window.resolveProfileMemberId54()||''):String(me?.memberId||'');return x.trim()}
const avatarPrev55=typeof avatar==='function'?avatar:null;function avatar55(m){const img=profileOverride55.get(String(m?.id||''));if(img)return `<div class="avatar profileAvatar53"><img src="${img}" alt="${esc55(m?.name||'프로필')} 프로필"></div>`;return avatarPrev55?String(avatarPrev55(m)||''):''}try{avatar=avatar55}catch{}window.avatar=avatar55;
function fileData55(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error('사진 파일을 읽지 못했습니다.'));r.onload=()=>res(String(r.result||''));r.readAsDataURL(file)})}
function img55(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('사진 형식을 읽지 못했습니다.'));i.src=src})}
function timeout55(p,ms){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('사진 처리 시간이 초과되었습니다.')),ms))])}
async function source55(file){if(typeof createImageBitmap==='function')try{const s=await timeout55(createImageBitmap(file),4500);return{src:s,clean:()=>{try{s.close()}catch{}}}}catch{}const d=await timeout55(fileData55(file),7000),s=await timeout55(img55(d),7000);return{src:s,clean:()=>{}}}
function thumb55(src){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight,n=Math.min(w,h);if(!n)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');g.fillStyle='#fff';g.fillRect(0,0,256,256);g.drawImage(src,(w-n)/2,(h-n)/2,n,n,0,0,256,256);let d=c.toDataURL('image/jpeg',.82);for(const q of [.7,.58,.48]){if(d.length<=210000)break;d=c.toDataURL('image/jpeg',q)}if(d.length>220000)throw new Error('프로필 사진 용량을 줄이지 못했습니다.');return d}
function full55(src){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)return'';let side=2048,scale=Math.min(1,side/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale));const make=q=>{const c=document.createElement('canvas');c.width=cw;c.height=ch;const g=c.getContext('2d');if(!g)return'';g.fillStyle='#fff';g.fillRect(0,0,cw,ch);g.drawImage(src,0,0,w,h,0,0,cw,ch);return c.toDataURL('image/jpeg',q)};let d=make(.9);for(const q of [.82,.75,.68]){if(d.length<=2350000)break;d=make(q)}if(d.length>2450000){side=1600;scale=Math.min(1,side/Math.max(w,h));cw=Math.max(1,Math.round(w*scale));ch=Math.max(1,Math.round(h*scale));d=make(.76)}return d.length<=2500000?d:''}
function profileStatus55(text,bad=false){const card=document.getElementById('profileCard53');if(!card)return;let s=card.querySelector('.profileStatus55');if(!s){s=document.createElement('div');s.className='profileStatus55';card.appendChild(s)}s.textContent=text;s.style.color=bad?'#b42318':'#667085'}
async function profilePost55(body){const r=await fetch(PROFILE55,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`프로필 저장 실패 (${r.status})`);return x}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file||profileBusy55)return;if(!T)return alert('로그인이 필요합니다.');if(!currentGroupId||String(currentGroupId)==='__global__')return alert('프로필 사진을 적용할 모임을 선택해주세요.');const id=resolveId55();if(!id)return alert('현재 계정과 회원명부 연결정보를 찾지 못했습니다.');if(file.size>30*1024*1024)return alert('사진은 30MB 이하만 선택할 수 있습니다.');profileBusy55=true;const label=document.querySelector('label[for="profileFile53"]'),preview=document.querySelector('#profileCard53 .profilePreview53');let temp='';if(label){label.textContent='저장 중…';label.style.pointerEvents='none'}profileStatus55('사진 변환 중…');try{temp=URL.createObjectURL(file);if(preview)preview.innerHTML=`<img src="${temp}" alt="선택한 프로필 사진">`;const obj=await source55(file);let thumb='',full='';try{thumb=thumb55(obj.src);full=full55(obj.src)}finally{obj.clean()}profileStatus55('서버에 저장 중…');const x=await profilePost55({action:'save_profile',groupId:String(currentGroupId),image:thumb,fullImage:full});const savedId=String(x.memberId||id);profileOverride55.set(savedId,thumb);try{if(typeof renderMembers==='function')renderMembers();if(typeof renderQueue==='function')renderQueue();if(currentView==='settings'&&typeof renderSettings==='function')renderSettings()}catch{}const p=document.querySelector('#profileCard53 .profilePreview53');if(p)p.innerHTML=`<img src="${thumb}" alt="내 프로필 사진">`;profileStatus55(full?'프로필 사진 저장 완료 · 고화질 원본 저장됨':'프로필 사진 저장 완료');if(label)label.textContent='저장됨';setTimeout(()=>{const l=document.querySelector('label[for="profileFile53"]');if(l){l.textContent='사진 변경';l.style.pointerEvents=''}},1000)}catch(e){profileStatus55(e?.message||'프로필 사진 저장 실패',true);if(typeof showError==='function')showError(e);else alert(e?.message||String(e));if(label){label.textContent='사진 변경';label.style.pointerEvents=''}}finally{profileBusy55=false;if(temp)try{URL.revokeObjectURL(temp)}catch{};if(input)input.value=''}};
const oldRH55=typeof renderHeader==='function'?renderHeader:null;if(oldRH55){renderHeader=function(){const r=oldRH55.apply(this,arguments);enforceVersion55();ensureFeedback55();return r};window.renderHeader=renderHeader}
const oldRA55=typeof renderAll==='function'?renderAll:null;if(oldRA55){renderAll=function(){const r=oldRA55.apply(this,arguments);enforceVersion55();ensureFeedback55();installLoginGuard55();return r};window.renderAll=renderAll}
function boot55(){style55();enforceVersion55();ensureFeedback55();installLoginGuard55()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot55,{once:true});else boot55();
const mo55=new MutationObserver(()=>{enforceVersion55();ensureFeedback55();installLoginGuard55()});mo55.observe(document.documentElement,{childList:true,subtree:true,characterData:true});setInterval(()=>{enforceVersion55();ensureFeedback55();installLoginGuard55()},3000);
})();