(()=>{
'use strict';
if(window.__kokmatchV54Fix20)return;
window.__kokmatchV54Fix20=true;
window.__kokmatchProfileCanonical='20.1';
const PROFILE20='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const photos20=new Map();
let gid20='',tok20='',seq20=0,busy20=null,raf20=0,t20a=0,t20b=0;

function esc20(v){return String(v??'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function member20(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function gender20(m){return String(m?.gender||'').trim()==='여'?'여':'남'}
function src20(m){return String(photos20.get(String(m?.id||''))||'')}
function mine20(){const direct=member20(me?.memberId);if(direct)return direct;const name=String(me?.displayName||me?.name||'').trim();if(!name||!Array.isArray(S?.members))return null;const same=S.members.filter(m=>String(m?.name||'').trim()===name);return same.length===1?same[0]:null}
function pageRows20(){const all=Array.isArray(S?.members)?S.members:[],q=String(document.getElementById('memberSearchInput46')?.value||'').trim().toLowerCase();const filtered=!q?all:all.filter(m=>{let role='';try{role=typeof roleLabel==='function'&&typeof roleOf==='function'?roleLabel(roleOf(m)):''}catch{}return[m?.name,m?.cls,m?.gender,m?.inviter,role,m?.type==='guest'?'게스트':'일반회원'].some(v=>String(v||'').toLowerCase().includes(q))});const page=Math.max(1,Number(document.querySelector('#members .memberPager46 b')?.textContent)||1);return filtered.slice((page-1)*10,page*10)}
function visibleName20(card){return String(card?.querySelector('.memberName45')?.textContent||'').trim()||String(card?.querySelector('.name')?.textContent||'').replace(/\d{2,3}[A-E].*$/,'').trim()}
function cardMember20(card,index,rows){if(!card)return null;rows=Array.isArray(rows)?rows:pageRows20();const name=visibleName20(card),meta=String(card.querySelector('.meta')?.textContent||'');const g=(meta.match(/(?:년생\s*·\s*|^|\s)(남|여)(?:\s|·|$)/)||[])[1]||'';const y=(meta.match(/(\d{4})년생/)||[])[1]||'';const gradeText=String(card.querySelector('.gradeBadge50,.tag')?.textContent||'').trim(),grade=(gradeText.match(/([A-E])$/i)||[])[1]?.toUpperCase()||'';let c=rows.filter(m=>!name||String(m?.name||'').trim()===name);if(g)c=c.filter(m=>String(m?.gender||'').trim()===g);if(y)c=c.filter(m=>String(m?.year||'')===y);if(grade)c=c.filter(m=>String(m?.cls||'').trim().toUpperCase()===grade);if(c.length===1)return c[0];const byIndex=rows[index];if(byIndex)return byIndex;return c[0]||null}
function queueMember20(card){if(!card)return null;try{const box=document.getElementById('queue'),i=[...(box?.querySelectorAll('.queueCard')||[])].indexOf(card),ids=typeof sortedQueue==='function'?sortedQueue():[];return member20(ids[i])}catch{return null}}
function style20(){if(document.getElementById('v54fix20style'))return;const s=document.createElement('style');s.id='v54fix20style';s.textContent=`
.profileIdentity80.canonical20{position:relative!important;display:grid!important;place-items:center!important;border-radius:50%!important;overflow:visible!important;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
.profileIdentity80.canonical20 img{width:100%!important;height:100%!important;display:block!important;object-fit:cover!important;border-radius:50%!important;pointer-events:none!important;-webkit-user-drag:none!important}
.profileIdentity80.canonical20.genderFallback80{font-size:14px!important;font-weight:950!important;line-height:1!important}
.profileIdentity80.canonical20.genderFallback80.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}
.profileIdentity80.canonical20.genderFallback80.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
.profileIdentity80.canonical20.genderFallback80::after{display:none!important;content:none!important}
.profilePreview53 .profilePreviewFallback20{width:100%!important;height:100%!important;min-height:64px!important;border-radius:50%!important;display:grid!important;place-items:center!important;font-size:18px!important;font-weight:950!important}
.profilePreview53 .profilePreviewFallback20.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}
.profilePreview53 .profilePreviewFallback20.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
`;document.head.appendChild(s)}
function identity20(m,queue=false){const g=gender20(m),female=g==='여',src=src20(m),d=document.createElement('div');d.className=`avatar profileIdentity80 canonical20 ${src?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.gender=g;d.dataset.photo=src?'1':'0';if(src){d.setAttribute('role','button');d.setAttribute('tabindex','0');d.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);d.innerHTML=`<img src="${esc20(src)}" alt="${esc20(m?.name||'프로필')} 프로필" draggable="false">`}else{d.setAttribute('aria-label',female?'여성':'남성');d.textContent=g}return d}
function canonicalAvatar20(m){const g=gender20(m),female=g==='여',src=src20(m);if(src)return `<div class="avatar profileAvatar53 ${female?'female':'male'}"><img src="${esc20(src)}" alt="${esc20(m?.name||'프로필')} 프로필" draggable="false"></div>`;return `<div class="avatar genderAvatar39 ${female?'female':'male'}" aria-label="${female?'여성':'남성'}">${g}</div>`}
function installAvatar20(){try{avatar=canonicalAvatar20}catch{}try{window.avatar=canonicalAvatar20}catch{}}
function wipe20(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove()}
function fixActions20(card,id){if(!card||!id)return;for(const el of card.querySelectorAll('[onclick]')){let code=String(el.getAttribute('onclick')||''),next=code;next=next.replace(/openPairs\(\s*['\"][^'\"]+['\"]\s*\)/g,`openPairs('${id}')`);next=next.replace(/openEditMember\(\s*['\"][^'\"]+['\"]\s*\)/g,`openEditMember('${id}')`);next=next.replace(/setOther\(\s*['\"][^'\"]+['\"]\s*,/g,`setOther('${id}',`);if(next!==code)el.setAttribute('onclick',next)}}
function decorateMembers20(){const box=document.getElementById('members');if(!box)return;const cards=[...box.querySelectorAll('.memberCard')],rows=pageRows20();cards.forEach((card,i)=>{const m=cardMember20(card,i,rows);if(!m)return;const id=String(m.id||''),g=gender20(m),src=src20(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity80'));const good=cur?.classList?.contains('canonical20')&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0')&&(src?String(cur.querySelector('img')?.getAttribute('src')||'')===src:String(cur.textContent||'').trim()===g);card.dataset.memberId80=id;fixActions20(card,id);if(!good){wipe20(card);card.insertBefore(identity20(m,false),card.firstChild)}card.classList.add('memberIdentityCard80')})}
function decorateQueue20(){const box=document.getElementById('queue');if(!box)return;for(const card of box.querySelectorAll('.queueCard')){const m=queueMember20(card);if(!m)continue;const id=String(m.id||''),g=gender20(m),src=src20(m),cur=[...card.children].find(x=>x.classList?.contains('profileIdentity80'));const good=cur?.classList?.contains('canonical20')&&String(cur.dataset.memberId||'')===id&&String(cur.dataset.gender||'')===g&&String(cur.dataset.photo||'')===(src?'1':'0')&&(src?String(cur.querySelector('img')?.getAttribute('src')||'')===src:String(cur.textContent||'').trim()===g);card.dataset.memberId80=id;if(!good){wipe20(card);const d=identity20(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.classList.add('queueIdentityCard80')}}
function decorateSettings20(){const preview=document.querySelector('#settings #profileCard53 .profilePreview53,#profileCard53 .profilePreview53');if(!preview)return;const m=mine20();if(!m){preview.innerHTML='';preview.dataset.canonical20='';return}const g=gender20(m),female=g==='여',src=src20(m),sig=`${String(m.id||'')}|${g}|${src}`;if(preview.dataset.canonical20===sig)return;preview.dataset.canonical20=sig;if(src)preview.innerHTML=`<img src="${esc20(src)}" alt="내 프로필 사진" draggable="false">`;else preview.innerHTML=`<div class="profilePreviewFallback20 ${female?'female':'male'}" aria-label="${female?'여성':'남성'}">${g}</div>`}
function decorate20(){style20();installAvatar20();decorateMembers20();decorateQueue20();decorateSettings20()}
function schedule20(){if(!raf20)raf20=requestAnimationFrame(()=>{raf20=0;decorate20()});clearTimeout(t20a);clearTimeout(t20b);t20a=setTimeout(decorate20,70);t20b=setTimeout(decorate20,320)}
async function load20(force=false){const g=String(currentGroupId||''),t=String(T||'');if(!g||g==='__global__'||!t){gid20='';tok20='';photos20.clear();schedule20();return}if(!force&&g===gid20&&t===tok20&&window.__kokmatchProfilesLoaded20===g)return;if(busy20&&!force&&g===gid20&&t===tok20)return busy20;gid20=g;tok20=t;photos20.clear();window.__kokmatchProfilesLoaded20='';schedule20();const my=++seq20;busy20=(async()=>{try{const u=new URL(PROFILE20);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+t},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 사진 조회 실패');if(my!==seq20||String(currentGroupId||'')!==g||String(T||'')!==t)return;for(const [id,v] of Object.entries(x?.profiles||{})){const src=String(v?.image||'');if(src)photos20.set(String(id),src)}window.__kokmatchProfilesLoaded20=g;schedule20()}catch(e){console.warn('canonical profile20',e);if(my===seq20){photos20.clear();window.__kokmatchProfilesLoaded20=g;schedule20()}}finally{if(my===seq20)busy20=null}})();return busy20}
function ensure20(){const g=String(currentGroupId||''),t=String(T||'');if(g!==gid20||t!==tok20||window.__kokmatchProfilesLoaded20!==g)load20(false);schedule20()}
window.refreshProfiles20=()=>load20(true);
try{const rm=renderMembers;renderMembers=function(){const r=rm();ensure20();return r};const rq=renderQueue;renderQueue=function(){const r=rq();ensure20();return r};const rs=renderSettings;renderSettings=function(){const r=rs();ensure20();return r};const ra=renderAll;renderAll=function(){const r=ra();ensure20();return r}}catch{}
const prevChange20=window.changeProfile53;if(typeof prevChange20==='function')window.changeProfile53=async function(...a){const r=await prevChange20.apply(this,a);await load20(true);schedule20();return r};const prevDelete20=window.deleteProfile53;if(typeof prevDelete20==='function')window.deleteProfile53=async function(...a){const r=await prevDelete20.apply(this,a);await load20(true);schedule20();return r};try{changeProfile53=window.changeProfile53;deleteProfile53=window.deleteProfile53}catch{}
const mo20=new MutationObserver(schedule20);function boot20(){style20();installAvatar20();for(const id of ['members','queue','settings']){const el=document.getElementById(id);if(el)mo20.observe(el,{childList:true,subtree:true})}ensure20();setTimeout(decorate20,700);setTimeout(decorate20,1800)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot20,{once:true});else boot20();
})();