(()=>{
const LOGIN35_API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-login-v33';
let loginCandidates35=[],selectedLogin35=null,loginBusy35=false,loginFinalizing35=false;
async function loginReq35(action,body={}){const r=await fetch(LOGIN35_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(x.error||'로그인 처리에 실패했습니다.');e.payload=x;throw e}return x}
function candidateInfo35(c){const year=c.year?`${esc(c.year)}년생`:'출생연도 미등록',gender=String(c.gender||'').trim(),cls=c.cls?`${esc(c.cls)}급`:'급수 미등록',role=esc(c.roleLabel||'회원');return[year,gender?esc(gender):'',cls,role].filter(Boolean).join(' · ')}
function candidateHtml35(c,i){return`<button type="button" class="choiceBtn loginChoice33" onclick="chooseLoginMember35(${i})"><b>${esc(pendingLoginName)}</b><span>${candidateInfo35(c)}</span><small>${esc(c.groupName||'모임')}</small></button>`}
function renderLoginCandidates35(){if(!loginCandidates35.length)return renderLoginName();$('loginBox').innerHTML=`<h2>${loginCandidates35.length>1?'동명이인 회원 선택':'회원 확인'}</h2><div class="authName">${esc(pendingLoginName)}</div><div class="note loginGuide33">${loginCandidates35.length>1?'같은 이름으로 등록된 회원이 있습니다. 본인의 출생연도·성별·급수·역할을 확인하고 선택해주세요.':'회원정보를 확인해주세요.'}</div><div class="choiceList loginChoices33">${loginCandidates35.map((c,i)=>candidateHtml35(c,i)).join('')}</div><div id="loginErr" class="error"></div><button class="btn ghost" style="width:100%;margin-top:9px" onclick="renderLoginName()">← 이름 다시 입력</button>`}
window.chooseLoginMember35=function(i){const c=loginCandidates35[Number(i)];if(!c)return;selectedLogin35=c;renderLoginPin35()};
function renderLoginPin35(){const c=selectedLogin35;if(!c)return renderLoginCandidates35();const adminOnly=!!c.globalAdminOnly;const title=adminOnly?'총관리자 PIN':'모임 PIN';$('loginBox').innerHTML=`<h2>${title} 입력</h2><div class="loginMember33"><b>${esc(pendingLoginName)}</b><span>${adminOnly?'총관리자':candidateInfo35(c)}</span><small>${adminOnly?'':esc(c.groupName||'모임')}</small></div><div class="note" style="margin-bottom:12px">${adminOnly?'총관리자 PIN을 입력해주세요.':'선택한 모임의 모임 PIN을 입력해주세요.'}</div><div class="field"><label>${title}</label><input id="loginPin" type="password" inputmode="numeric" autocomplete="current-password" placeholder="${title} 입력"></div><button id="loginSubmit35" class="btn pri" style="width:100%" onclick="submitLogin()">로그인</button><div id="loginErr" class="error"></div><button class="btn ghost" style="width:100%;margin-top:8px" onclick="${loginCandidates35.length>1?'renderLoginCandidates35()':'renderLoginName()'}">← ${loginCandidates35.length>1?'회원 다시 선택':'이름 다시 입력'}</button>`;const p=$('loginPin');if(p){p.addEventListener('keydown',e=>{if(e.key==='Enter')submitLogin()});setTimeout(()=>p.focus(),30)}}
renderLoginName=function(){loginCandidates35=[];selectedLogin35=null;pendingLoginPin='';$('loginBox').innerHTML=`<h1>🏸 콕매치</h1><div class="meta" style="font-size:14px;margin-bottom:18px">모임 회원 로그인</div><div class="field"><label>등록된 이름</label><input id="loginName" autocomplete="username" placeholder="이름"></div><button class="btn pri" style="width:100%" onclick="startLogin()">다음</button><div id="loginErr" class="error"></div><div class="note" style="margin-top:12px">동명이인이 있으면 <b>이름 · 출생연도 · 성별 · 급수 · 역할</b>을 확인해 본인을 선택한 뒤 모임 PIN으로 로그인합니다.</div>`;const n=$('loginName');if(n){n.addEventListener('keydown',e=>{if(e.key==='Enter')startLogin()});setTimeout(()=>n.focus(),30)}};
startLogin=async function(){if(loginBusy35)return;const name=$('loginName')?.value.trim()||'',err=$('loginErr');if(err)err.textContent='';if(!name){if(err)err.textContent='이름을 입력해주세요.';return}loginBusy35=true;try{const x=await loginReq35('probe',{name});pendingLoginName=name;loginCandidates35=(Array.isArray(x.memberships)?x.memberships:[]).map(c=>({...c}));if(!loginCandidates35.length&&x.globalAdmin)loginCandidates35.push({globalAdminOnly:true,groupId:'',groupName:'',memberId:'',year:'',gender:'',cls:'',roleLabel:'총관리자'});if(loginCandidates35.length===1){selectedLogin35=loginCandidates35[0];renderLoginPin35()}else renderLoginCandidates35()}catch(e){if(err)err.textContent=e.message}finally{loginBusy35=false}};
async function finalizeLogin35(x,c){T=x.token;localStorage.setItem(TOKEN_KEY,T);const gid=x.groupId||c?.groupId||'';if(gid){currentGroupId=gid;localStorage.setItem(GROUP_KEY,currentGroupId)}$('login').classList.add('hide');pendingLoginPin='';await loadState(true);const mine=me?.memberId?M(me.memberId):null;if(mine?.state==='out')openEntry()}
submitLogin=async function(){if(loginBusy35)return;const c=selectedLogin35||loginCandidates35[0];if(!c){renderLoginCandidates35();return}const pin=$('loginPin')?.value.trim()||pendingLoginPin;if(!pin){const e=$('loginErr');if(e)e.textContent='모임 PIN을 입력해주세요.';return}pendingLoginPin=pin;loginBusy35=true;loginFinalizing35=true;const btn=$('loginSubmit35');if(btn)btn.disabled=true;try{let x=await loginReq35('login',{name:pendingLoginName,pin,groupId:c.groupId||'',memberId:c.memberId||''});try{await finalizeLogin35(x,c)}catch(e){if(!/로그인이 만료|로그인이 필요|401/i.test(String(e?.message||e)))throw e;await new Promise(r=>setTimeout(r,120));x=await loginReq35('login',{name:pendingLoginName,pin,groupId:c.groupId||'',memberId:c.memberId||''});await finalizeLogin35(x,c)}}catch(e){$('login')?.classList.remove('hide');const el=$('loginErr');if(el)el.textContent=e.message;else alert(e.message)}finally{loginFinalizing35=false;loginBusy35=false;if(btn)btn.disabled=false}};
function memberSig35(x){const type=String(x?.type||'member')==='guest'?'guest':'member',role=type==='guest'?'member':String(x?.role||'member');return[String(x?.name||'').trim(),String(Number(x?.year)||''),String(x?.gender||'남'),String(x?.cls||'C').toUpperCase(),type,role].join('|')}
function formMember35(){const cur=editMemberId?M(editMemberId):null,type=$('fmType')?.value==='guest'?'guest':'member';let role=$('fmRole')?.value||(cur?roleOf(cur):'member');if(type==='guest')role='member';return{name:$('fmName')?.value.trim()||'',year:Number($('fmYear')?.value),gender:$('fmGender')?.value||'남',cls:($('fmCls')?.value||'C').toUpperCase(),type,role}}
const saveMemberNow35=saveMemberNow;saveMemberNow=async function(){const f=formMember35();if(f.name){const dup=(S?.members||[]).find(m=>String(m?.id)!==String(editMemberId||'')&&memberSig35(m)===memberSig35(f));if(dup){const kind=f.type==='guest'?'게스트':f.role==='manager'?'모임장':f.role==='organizer'?'운영진':'일반회원';return alert(`동일한 회원 정보가 이미 등록되어 있습니다.\n\n${f.name} · ${f.year}년생 · ${f.gender} · ${f.cls}급 · ${kind}\n\n출생연도·성별·급수·구분·역할 중 하나라도 다르면 동명이인으로 등록할 수 있습니다.`)}}return saveMemberNow35()};
const openMemberModal35=openMemberModal;openMemberModal=function(m){const r=openMemberModal35(m);if(!m)setTimeout(()=>{if($('sameNameGuide35'))return;const field=$('fmName')?.closest('.field');field?.insertAdjacentHTML('afterend','<div id="sameNameGuide35" class="meta" style="margin:-2px 0 8px">동명이인은 출생연도·성별·급수·구분·역할 중 하나라도 다르면 등록할 수 있습니다.</div>')},0);return r};
const renderSettings34=renderSettings;renderSettings=function(){renderSettings34();const b=$('settings');if(!b)return;[...b.querySelectorAll('.meta')].forEach(el=>{if(/콕매치 v(?:\d+|\d+\.\d+)/.test(el.textContent||''))el.textContent='콕매치 v3.5 · 동명이인 개별등록 허용 · 완전일치만 중복차단 · 로그인 성별 구분'})};
if(!T)renderLoginName();
})();
