(()=>{
const CUR45='4.5';
try{sessionStorage.setItem('kokmatch_auto_update_target_v39',CUR45);sessionStorage.setItem('kokmatch_auto_update_target_v40',CUR45)}catch{}
let latest45=CUR45,refreshBusy45=false;
function cmp45(a,b){const A=String(a||'0').replace(/^v/i,'').split('.').map(Number),B=String(b||'0').replace(/^v/i,'').split('.').map(Number);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x!==y)return x>y?1:-1}return 0}
function updateTop45(){const v=document.getElementById('currentVersion45'),b=document.getElementById('headerRefresh45');if(v)v.textContent='v'+CUR45;if(!b)return;const newer=cmp45(latest45,CUR45)>0;b.textContent=refreshBusy45?'불러오는 중…':newer?`v${latest45} 업데이트 · 새로고침`:'↻ 새로고침'}
function ensureTop45(){const row=document.querySelector('.toprow');if(!row)return;document.querySelectorAll('#topActions37,#topActions39,#topActions40,#topActions41,#topActions42,#topActions43,#topActions44').forEach(x=>x.style.setProperty('display','none','important'));let a=document.getElementById('topActions45');if(!a){a=document.createElement('div');a.id='topActions45';a.style.cssText='margin-left:auto;display:flex;align-items:center;justify-content:flex-end;gap:4px;position:relative;z-index:90;pointer-events:auto';a.innerHTML='<span id="currentVersion45" style="font-size:10px;font-weight:900;padding:6px 5px;border-radius:8px;background:rgba(255,255,255,.18);white-space:nowrap">v4.5</span><button id="headerRefresh45" class="btn ghost" type="button" style="max-width:170px;min-height:30px;padding:6px 8px;font-size:10.5px;font-weight:800;line-height:1.15;white-space:normal">↻ 새로고침</button><button id="logout45" type="button" style="flex:0 0 64px;width:64px;min-width:64px;max-width:64px;min-height:30px;padding:6px 4px;font-size:11px;white-space:nowrap">로그아웃</button>';row.appendChild(a);a.querySelector('#headerRefresh45')?.addEventListener('click',()=>refreshApp45());a.querySelector('#logout45')?.addEventListener('click',()=>logout())}updateTop45()}
async function latestCheck45(){try{const r=await fetch('/latest-version.json?t='+Date.now(),{cache:'no-store'});if(r.ok){const x=await r.json();latest45=String(x.semanticVersion||x.label||CUR45).replace(/^v/i,'')||CUR45}}catch{}updateTop45();return latest45}
window.refreshApp45=async function(target=''){if(refreshBusy45)return;refreshBusy45=true;updateTop45();try{const v=String(target||await latestCheck45()||CUR45).replace(/^v/i,'');try{sessionStorage.setItem('kokmatch_auto_update_target_v39',v);sessionStorage.setItem('kokmatch_auto_update_target_v40',v)}catch{}location.replace('/?v='+encodeURIComponent(v)+'&refresh='+Date.now())}catch(e){refreshBusy45=false;updateTop45();showError(e)}};
window.refreshApp44=window.refreshApp45;window.refreshApp43=window.refreshApp45;window.refreshApp42=window.refreshApp45;window.refreshApp41=window.refreshApp45;window.refreshApp40=window.refreshApp45;window.refreshApp39=window.refreshApp45;window.refreshApp37=window.refreshApp45;
const renderHeaderPrev45=renderHeader;renderHeader=function(){const r=renderHeaderPrev45();ensureTop45();return r};
setTimeout(()=>{ensureTop45();latestCheck45()},0);setInterval(()=>latestCheck45(),60000);
})();
