(()=>{
if(window.__kokmatchV54Fix6)return;window.__kokmatchV54Fix6=true;window.__kokmatchVersionLock='5.4';window.__kokmatchProfileFixReady='6.4';window.__kokmatchProfilePatch='6.5';window.__kokmatchProfileSaveState='idle';
const PROFILE6='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53',override6=new Map();
const baseAvatar6=typeof avatar==='function'?avatar:null;
function resolveMemberId6(){const direct=String(me?.memberId||'').trim();if(direct)return direct;const display=String(me?.displayName||me?.name||'').trim();if(!display||!Array.isArray(S?.members))return'';const same=S.members.filter(m=>String(m?.name||'').trim()===display&&String(m?.id||'').trim());let pick=same.length===1?same[0]:null;if(!pick){const admins=same.filter(m=>String(m?.role||'')==='admin');if(admins.length===1)pick=admins[0]}if(!pick&&me?.globalAdmin===true){const admins=S.members.filter(m=>String(m?.role||'')==='admin'&&String(m?.id||'').trim());if(admins.length===1)pick=admins[0]}const id=String(pick?.id||'').trim();if(id){try{if(me)me.memberId=id}catch{}}return id}
window.resolveProfileMemberId54=resolveMemberId6;
function fallback6(m){return baseAvatar6?String(baseAvatar6(m)||''):`<div class="avatar ${m?.gender==='여'?'female':'male'}">●</div>`}
function avatar6(m){const image=override6.get(String(m?.id||''));return image?`<div class="avatar profileAvatar53"><img src="${image}" alt="${esc(m?.name||'프로필')} 프로필"></div>`:fallback6(m)}
try{avatar=function(m){return avatar6(m)}}catch{window.avatar=avatar6}
function genderText6(m){const f=m?.gender==='여';return `<span class="v54genderText ${f?'female':'male'}">${f?'여':'남'}</span>`}
function refreshMembers6(){const box=typeof $==='function'?$('members'):document.getElementById('members');if(!box||!Array.isArray(S?.members))return;const cards=[...box.querySelectorAll('.memberCard')];cards.forEach((card,i)=>{const m=S.members[i];if(!m)return;[...card.children].filter(el=>el?.classList?.contains('avatar')).forEach(el=>el.remove());card.insertAdjacentHTML('afterbegin',avatar6(m))})}
function refreshQueue6(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((card,i)=>{const m=ids[i]&&typeof M==='function'?M(ids[i]):null;if(!m)return;card.querySelectorAll('.avatar,.profileAvatar53,.queueProfile53,.genderAvatar39,.genderPerson54,.genderMini39,.v54genderText').forEach(x=>x.remove());const ord=card.querySelector('.ord');if(!ord)return;let h=avatar6(m);h=h.replace('class="avatar ','class="avatar queueProfile53 ');ord.insertAdjacentHTML('afterend',h);const photo=card.querySelector('.profileAvatar53 img');if(photo)photo.closest('.profileAvatar53')?.insertAdjacentHTML('afterend',genderText6(m))})}
function ensureDeveloperControls6(card){if(!card||document.getElementById('profileFile53'))return;const id=resolveMemberId6();if(!id||!T||!currentGroupId||String(currentGroupId)==='__global__')return;const head=card.querySelector('.profileHead53');const right=head?.lastElementChild;if(!right)return;[...right.querySelectorAll('.profileHelp53')].forEach(el=>{if(String(el.textContent||'').includes('회원으로 연결된 계정'))el.remove()});const meta=right.querySelector('.meta');const has=!!override6.get(id)||!!card.querySelector('.profilePreview53 img');const html=`<div class="profileBtns53"><label class="btn pri" for="profileFile53">사진 변경</label><input id="profileFile53" type="file" accept="image/*" style="display:none" onchange="changeProfile53(this)">${has?'<button class="btn ghost" onclick="deleteProfile53()">기본 사진으로</button>':''}</div>`;if(meta)meta.insertAdjacentHTML('afterend',html);else right.insertAdjacentHTML('beforeend',html)}
function ensureStatus6(){const card=document.getElementById('profileCard53');if(!card)return null;let s=card.querySelector('#profileStatus65');if(!s){s=document.createElement('div');s.id='profileStatus65';s.className='profileHelp53';s.style.fontWeight='700';s.style.marginTop='8px';card.appendChild(s)}return s}
function setStatus6(text,bad=false){const s=ensureStatus6();if(s){s.textContent=text||'';s.style.color=bad?'#b42318':'#667085'}}
function refreshSettings6(){const card=document.getElementById('profileCard53');if(!card)return;ensureDeveloperControls6(card);ensureStatus6();const id=resolveMemberId6(),image=override6.get(id);if(image){const p=card.querySelector('.profilePreview53');if(p)p.innerHTML=`<img src="${image}" alt="내 프로필 사진">`}}
function refreshAll6(){try{refreshMembers6();refreshQueue6();refreshSettings6()}catch(e){console.warn('profile refresh6',e)}}
function currentLabel6(){return document.querySelector('label[for="profileFile53"]')}
function setLabel6(text,disabled=true){const l=currentLabel6();if(l){l.textContent=text;l.style.pointerEvents=disabled?'none':''}return l}
function profileError6(message){setStatus6(message,true);const e=new Error(message);if(typeof showError==='function')showError(e);else alert(message)}
function safeStage6(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_-]+/g,'_').slice(0,48)||'unknown'}
function trace6(stage){try{if(!T||!currentGroupId||String(currentGroupId)==='__global__')return;const u=new URL(PROFILE6);u.searchParams.set('groupId',String(currentGroupId));u.searchParams.set('diag','p65_'+safeStage6(stage));u.searchParams.set('t',Date.now());fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store'}).catch(()=>{})}catch{}}
function timeout6(p,ms,label){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label||'사진 처리 시간이 초과되었습니다.')),ms))])}
function readData6(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('사진 파일을 읽지 못했습니다.'));r.onload=()=>resolve(String(r.result||''));r.readAsDataURL(file)})}
function imageFromSrc6(src,label='사진'){return new Promise((resolve,reject)=>{const im=new Image();let done=false;const timer=setTimeout(()=>{if(done)return;done=true;reject(new Error(`${label} 불러오기가 지연되어 다른 방식으로 재시도합니다.`))},7000);im.onload=()=>{if(done)return;done=true;clearTimeout(timer);resolve(im)};im.onerror=()=>{if(done)return;done=true;clearTimeout(timer);reject(new Error(`${label} 형식을 브라우저에서 읽지 못했습니다.`))};im.src=src})}
function imageObject6(file){return new Promise((resolve,reject)=>{let u='';try{u=URL.createObjectURL(file)}catch(e){reject(e);return}const im=new Image();let done=false;const finish=()=>{try{URL.revokeObjectURL(u)}catch{}};const timer=setTimeout(()=>{if(done)return;done=true;finish();reject(new Error('사진 Blob 디코딩 시간이 초과되었습니다.'))},7000);im.onload=()=>{if(done)return;done=true;clearTimeout(timer);resolve({source:im,cleanup:finish})};im.onerror=()=>{if(done)return;done=true;clearTimeout(timer);finish();reject(new Error('사진 Blob 형식을 읽지 못했습니다.'))};im.src=u})}
async function decode6(file){if(!file)throw new Error('사진을 선택해주세요.');if(file.size>30*1024*1024)throw new Error('원본 사진은 30MB 이하만 사용할 수 있습니다.');let source=null,cleanup=()=>{},err=[];try{if(typeof createImageBitmap==='function'){try{source=await timeout6(createImageBitmap(file),4500,'기본 사진 디코딩이 지연되었습니다.');cleanup=()=>{try{source.close()}catch{}}}catch(e){err.push(e?.message||'bitmap');source=null}}if(!source){try{const data=await timeout6(readData6(file),6000,'사진 읽기 시간이 초과되었습니다.');source=await imageFromSrc6(data,'사진 데이터');cleanup=()=>{}}catch(e){err.push(e?.message||'dataurl');source=null}}if(!source){try{const x=await imageObject6(file);source=x.source;cleanup=x.cleanup}catch(e){err.push(e?.message||'blob');source=null}}if(!source){const type=String(file.type||'알 수 없음'),name=String(file.name||'').split('.').pop()||'';throw new Error(`사진을 변환하지 못했습니다. 형식 ${type}${name?` (.${name})`:''}. JPG/PNG 또는 사진 캡처본으로 다시 시도해주세요.`)}const w=source.width||source.naturalWidth,h=source.height||source.naturalHeight,size=Math.min(w,h);if(!size)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');g.drawImage(source,(w-size)/2,(h-size)/2,size,size,0,0,256,256);let d=c.toDataURL('image/jpeg',.82);if(!d||d==='data:,')throw new Error('사진 변환 결과를 만들지 못했습니다.');if(d.length>210000)d=c.toDataURL('image/jpeg',.65);if(d.length>210000)d=c.toDataURL('image/jpeg',.5);if(d.length>220000)throw new Error('사진 용량을 줄인 뒤 다시 선택해주세요.');return d}finally{cleanup()}}
async function post6(body){const r=await fetch(PROFILE6,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`프로필 저장 실패 (${r.status})`);return x}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file)return;trace6('selected');setStatus6(`사진 선택됨 · ${file.type||'형식 미확인'} · ${Math.max(1,Math.round(file.size/1024))}KB`);if(!T){trace6('no_token');profileError6('로그인 정보가 없어 프로필 사진을 저장할 수 없습니다. 다시 로그인해주세요.');return}if(!currentGroupId||String(currentGroupId)==='__global__'){trace6('no_group');profileError6('프로필 사진을 적용할 모임을 먼저 선택해주세요.');return}const id=resolveMemberId6();if(!id){trace6('no_member');profileError6('현재 계정과 회원명부의 연결 정보를 찾지 못했습니다. 모임을 다시 선택한 뒤 시도해주세요.');return}trace6('identity_ok');const had=override6.has(id),before=override6.get(id),card=document.getElementById('profileCard53'),preview=card?.querySelector('.profilePreview53');let temp='';window.__kokmatchProfileSaveState='processing';setLabel6('사진 적용 중…');setStatus6('사진을 프로필 크기로 변환하는 중…');try{try{temp=URL.createObjectURL(file);if(preview)preview.innerHTML=`<img src="${temp}" alt="선택한 프로필 사진">`}catch{}const image=await decode6(file);trace6('decoded');override6.set(id,image);try{renderMembers();renderQueue()}catch{}refreshAll6();window.__kokmatchProfileSaveState='saving';setLabel6('저장 중…');setStatus6('사진 변환 완료 · 서버에 저장 중…');trace6('post_start');await post6({action:'save_profile',groupId:String(currentGroupId||''),image});refreshAll6();window.__kokmatchProfileSaveState='saved';setLabel6('저장됨');setStatus6('프로필 사진 저장 완료');trace6('saved');setTimeout(()=>{setLabel6('사진 변경',false);if(window.__kokmatchProfileSaveState==='saved')window.__kokmatchProfileSaveState='idle'},1200)}catch(e){window.__kokmatchProfileSaveState='error';trace6('error_'+safeStage6(e?.name||'decode'));if(had)override6.set(id,before);else override6.delete(id);try{renderMembers();renderQueue()}catch{}refreshAll6();setLabel6('사진 변경',false);profileError6(e?.message||'프로필 사진 처리에 실패했습니다.')}finally{if(temp)try{URL.revokeObjectURL(temp)}catch{};if(input)input.value='';if(window.__kokmatchProfileSaveState!=='saved'&&window.__kokmatchProfileSaveState!=='saving')setLabel6('사진 변경',false)}};
window.deleteProfile53=async function(){if(!T||!currentGroupId||String(currentGroupId)==='__global__')return;const id=resolveMemberId6();if(!id){profileError6('현재 계정과 회원명부의 연결 정보를 찾지 못했습니다.');return}window.__kokmatchProfileSaveState='saving';setLabel6('삭제 중…');setStatus6('프로필 사진 삭제 중…');try{await post6({action:'delete_profile',groupId:String(currentGroupId||'')});override6.delete(id);try{renderMembers();renderQueue()}catch{}refreshAll6();window.__kokmatchProfileSaveState='saved';setLabel6('삭제됨');setStatus6('기본 프로필로 변경 완료');setTimeout(()=>{setLabel6('사진 변경',false);window.__kokmatchProfileSaveState='idle'},800)}catch(e){window.__kokmatchProfileSaveState='error';setLabel6('사진 변경',false);profileError6(e?.message||'프로필 삭제에 실패했습니다.')}};
const rq6=renderQueue;renderQueue=function(){const r=rq6();refreshQueue6();return r};const rm6=renderMembers;renderMembers=function(){const r=rm6();refreshMembers6();return r};const rs6=renderSettings;renderSettings=function(){const r=rs6();refreshSettings6();return r};const ra6=renderAll;renderAll=function(){const r=ra6();refreshAll6();return r};refreshAll6();
})();