(()=>{
if(window.__kokmatchV54Fix17)return;window.__kokmatchV54Fix17=true;window.__kokmatchFeedbackInboxPatch='17.0';
const URL17='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-feedback-v54';
function canInbox17(){const r=String(me?.role||'');return !!me?.globalAdmin||r==='admin'||r==='manager'||r==='organizer'}
function ensure17(){const a=document.querySelector('.topActions16');if(!a)return;let b=a.querySelector('.feedbackInbox17');if(!canInbox17()){b?.remove();return}if(b)return;b=document.createElement('button');b.type='button';b.className='feedbackBtn16 feedbackInbox17';b.textContent='받은 건의사항';b.onclick=()=>window.openFeedbackInbox17();a.appendChild(b)}
function esc17(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function role17(v){return ({admin:'개발자',manager:'모임장',organizer:'운영진',scheduler:'편성자',member:'일반',guest:'게스트'})[v]||v||'-'}
window.openFeedbackInbox17=async function(){if(typeof openModal!=='function')return;if(!canInbox17())return alert('받은 건의사항을 볼 권한이 없습니다.');openModal('<h3>받은 건의사항</h3><div class="note">건의사항을 불러오는 중입니다.</div>');try{const r=await fetch(URL17,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+T},body:JSON.stringify({action:'list',groupId:String(currentGroupId||'')}),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'건의사항을 불러오지 못했습니다.');const items=Array.isArray(x.items)?x.items:[];const html=items.length?items.map(i=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between;gap:8px;font-size:12px;color:var(--mut)"><b>${esc17(i.sender_name||'이름 없음')} · ${esc17(role17(i.sender_role))}</b><span>${esc17(new Date(i.created_at).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</span></div><div style="margin-top:7px;white-space:pre-wrap;word-break:break-word;line-height:1.5">${esc17(i.content)}</div></div>`).join(''):'<div class="note">받은 건의사항이 없습니다.</div>';openModal(`<h3>받은 건의사항</h3><div style="max-height:55vh;overflow:auto">${html}</div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>`)}catch(e){if(typeof showError==='function')showError(e);else alert(e?.message||String(e))}};
const oldRA=window.renderAll;if(typeof oldRA==='function')window.renderAll=function(){const r=oldRA.apply(this,arguments);setTimeout(ensure17,0);return r};const oldRH=window.renderHeader;if(typeof oldRH==='function')window.renderHeader=function(){const r=oldRH.apply(this,arguments);setTimeout(ensure17,0);return r};setTimeout(ensure17,0);
})();