(()=>{
'use strict';
if(window.__kokmatchV54Fix18)return;
window.__kokmatchV54Fix18=true;
window.__kokmatchRosterIdentityPatch='18.1';

function style18(){if(document.getElementById('v54fix18style'))return;const s=document.createElement('style');s.id='v54fix18style';s.textContent=`
#members .profileIdentity80,#queue .profileIdentity80{touch-action:manipulation!important;-webkit-tap-highlight-color:transparent!important;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
#members .profileIdentity80 img,#queue .profileIdentity80 img,#profilePhotoModal80 img{-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important;-webkit-user-drag:none!important;pointer-events:none!important}
`;document.head.appendChild(s)}
function member18(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function realId18(card){if(!card)return'';for(const el of card.querySelectorAll('[onclick]')){const code=String(el.getAttribute('onclick')||''),re=/['\"]([^'\"]+)['\"]/g;let m;while((m=re.exec(code))){const id=String(m[1]||'');if(id&&member18(id))return id}}for(const attr of ['data-member-id','data-memberid','data-id']){const id=String(card.getAttribute(attr)||'');if(id&&member18(id))return id}return''}
function avatarSrc18(m){try{const d=document.createElement('div');d.innerHTML=typeof avatar==='function'?String(avatar(m)||''):'';const im=d.querySelector('img');return im?String(im.getAttribute('src')||im.src||''):''}catch{return''}}
function esc18(v){return String(v??'').replace(/[&\"<>]/g,c=>({'&':'&amp;','\"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function identity18(m){const female=String(m?.gender||'')==='여',gender=female?'여':'남',src=avatarSrc18(m),d=document.createElement('div');d.className=`avatar profileIdentity80 genderVisual10 ${src?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}`;d.dataset.memberId=String(m?.id||'');d.dataset.gender=gender;d.dataset.photo=src?'1':'0';d.dataset.visual10=`${gender}|${src?'1':'0'}|${src}`;if(src){d.setAttribute('role','button');d.setAttribute('tabindex','0');d.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);d.innerHTML=`<img src="${esc18(src)}" alt="${esc18(m?.name||'프로필')} 프로필" draggable="false">`}else{d.setAttribute('aria-label',female?'여성':'남성');d.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg>'}return d}
function directIdentity18(card){return [...(card?.children||[])].find(x=>x.classList?.contains('profileIdentity80')||x.classList?.contains('avatar')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57'))||null}
function correctCard18(card){const id=realId18(card),m=member18(id);if(!id||!m)return false;card.dataset.memberId80=id;const old=directIdentity18(card),src=avatarSrc18(m),gender=String(m.gender||'')==='여'?'여':'남',good=old?.classList?.contains('profileIdentity80')&&String(old.dataset.memberId||'')===id&&String(old.dataset.gender||'')===gender&&String(old.dataset.photo||'')===(src?'1':'0')&&(src?String(old.querySelector('img')?.getAttribute('src')||'')===src:!!old.querySelector('svg'));if(!good){for(const x of [...card.children])if(x.classList?.contains('profileIdentity80')||x.classList?.contains('avatar')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove();card.insertBefore(identity18(m),card.firstChild)}card.classList.add('memberIdentityCard80');return true}
function correctMembers18(){style18();const box=document.getElementById('members');if(!box)return;box.querySelectorAll('.memberCard').forEach(correctCard18)}
let raf18=0,t18a=0,t18b=0;function settle18(){if(!raf18)raf18=requestAnimationFrame(()=>{raf18=0;correctMembers18()});clearTimeout(t18a);clearTimeout(t18b);t18a=setTimeout(correctMembers18,60);t18b=setTimeout(correctMembers18,220)}
try{const rm18=renderMembers;renderMembers=function(){const r=rm18();settle18();return r};const ra18=renderAll;renderAll=function(){const r=ra18();settle18();return r}}catch{}
if(!window.__kokmatchProfileCallout18){window.__kokmatchProfileCallout18=true;const hit=e=>{const t=e.target instanceof Element?e.target:null;return t?.closest?.('#members .profileIdentity80,#queue .profileIdentity80,#profilePhotoModal80')||null};window.addEventListener('contextmenu',e=>{if(hit(e)){e.preventDefault();e.stopImmediatePropagation()}},true);window.addEventListener('dragstart',e=>{if(hit(e))e.preventDefault()},true)}
const mo18=new MutationObserver(settle18);function boot18(){style18();const box=document.getElementById('members');if(box)mo18.observe(box,{childList:true,subtree:true});settle18()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot18,{once:true});else boot18();
})();