(()=>{
if(window.__kokmatchV54Fix8)return;
window.__kokmatchV54Fix8=true;
window.__kokmatchProfileUiPatch='8.0';
const PROFILE80='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const fullCache80=new Map();

function style80(){
 if(document.getElementById('profileUi80Style'))return;
 const s=document.createElement('style');s.id='profileUi80Style';s.textContent=`
.profileIdentity80{position:relative!important;overflow:visible!important;display:grid!important;place-items:center!important;border-radius:50%!important;flex:0 0 auto!important}
.profileIdentity80 img{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:50%!important;display:block!important}
.profileTap80{cursor:pointer!important;touch-action:manipulation!important;-webkit-tap-highlight-color:transparent}
.profileGender80{position:absolute!important;right:-2px!important;bottom:-2px!important;width:17px!important;height:17px!important;border-radius:50%!important;display:grid!important;place-items:center!important;border:2px solid #fff!important;font-size:7.5px!important;font-weight:950!important;line-height:1!important;z-index:2!important;box-shadow:0 1px 5px #1720332b!important;pointer-events:none!important}
.profileGender80.male{background:#edf4ff!important;color:#2768e8!important}.profileGender80.female{background:#fff0f3!important;color:#e34e67!important}
.genderFallback80{font-size:11px!important;font-weight:950!important;border:1px solid transparent!important;cursor:default!important;user-select:none!important}
.genderFallback80.male{background:#edf4ff!important;color:#2768e8!important;border-color:#d5e4ff!important}.genderFallback80.female{background:#fff0f3!important;color:#e34e67!important;border-color:#ffd7df!important}
.memberCard.memberIdentityCard80{grid-template-columns:50px minmax(0,1fr) auto!important;column-gap:10px!important}.memberCard.memberIdentityCard80>.profileIdentity80{width:50px!important;height:50px!important;min-width:50px!important}
.queueCard.queueIdentityCard80{grid-template-columns:29px 44px minmax(0,1fr) 18px!important;column-gap:7px!important;align-items:center!important}.queueCard.queueIdentityCard80>.profileIdentity80{width:44px!important;height:44px!important;min-width:44px!important;margin:0!important;justify-self:center!important}.queueCard.queueIdentityCard80>.v54genderText,.queueCard.queueIdentityCard80>.genderPerson54,.queueCard.queueIdentityCard80>.genderPerson57,.queueCard.queueIdentityCard80>.genderMark53{display:none!important}
#profilePhotoModal80{position:fixed;inset:0;z-index:1100;display:none;align-items:center;justify-content:center;background:#080d19e8;padding:18px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}#profilePhotoModal80.on{display:flex}.profilePhotoSheet80{position:relative;width:min(720px,96vw);max-height:94vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:9px}.profilePhotoImg80{display:block;max-width:94vw;max-height:84vh;width:auto;height:auto;object-fit:contain;border-radius:16px;background:#fff;box-shadow:0 18px 56px #0008}.profilePhotoName80{color:#fff;font-size:14px;font-weight:900;text-align:center}.profilePhotoState80{color:#dfe6f3;font-size:11px;text-align:center;min-height:16px}.profilePhotoClose80{position:absolute;right:0;top:-5px;width:38px;height:38px;border:0;border-radius:50%;background:#fffffff0;color:#172033;font-size:24px;font-weight:900;display:grid;place-items:center;box-shadow:0 3px 14px #0005;cursor:pointer}
@media(max-width:599px){.memberCard57.memberIdentityCard80{grid-template-columns:46px minmax(0,1fr)!important;column-gap:10px!important}.memberCard57.memberIdentityCard80>.profileIdentity80{width:46px!important;height:46px!important;min-width:46px!important}.queueCard.queueIdentityCard80{grid-template-columns:27px 42px minmax(0,1fr) 16px!important;column-gap:6px!important}.queueCard.queueIdentityCard80>.profileIdentity80{width:42px!important;height:42px!important;min-width:42px!important}.profilePhotoImg80{max-width:95vw;max-height:80vh;border-radius:14px}}
@media(max-width:374px){.memberCard57.memberIdentityCard80{grid-template-columns:43px minmax(0,1fr)!important;column-gap:8px!important}.memberCard57.memberIdentityCard80>.profileIdentity80{width:43px!important;height:43px!important;min-width:43px!important}.queueCard.queueIdentityCard80{grid-template-columns:24px 39px minmax(0,1fr) 14px!important;column-gap:5px!important}.queueCard.queueIdentityCard80>.profileIdentity80{width:39px!important;height:39px!important;min-width:39px!important}}
@media(min-width:768px){.queueCard.queueIdentityCard80{grid-template-columns:34px 46px minmax(0,1fr) 22px!important;column-gap:8px!important}.queueCard.queueIdentityCard80>.profileIdentity80{width:46px!important;height:46px!important;min-width:46px!important}}
`;
 document.head.appendChild(s);
}
function escAttr80(v){return String(v??'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function parsedAvatar80(m){try{const box=document.createElement('div');box.innerHTML=typeof avatar==='function'?String(avatar(m)||''):'';return box.firstElementChild}catch{return null}}
function profileSrc80(m){const el=parsedAvatar80(m);const img=el?.querySelector?.('img');return img?String(img.getAttribute('src')||img.src||''):''}
function makeIdentity80(m,kind){
 const id=String(m?.id||''),female=String(m?.gender||'')==='여',src=profileSrc80(m),el=document.createElement('div');
 el.className=`avatar profileIdentity80 ${src?'profileTap80 profileAvatar53':'genderFallback80'} ${female?'female':'male'}${kind==='queue'?' queueProfile53':''}`;
 el.dataset.memberId=id;el.dataset.gender=female?'여':'남';el.dataset.photo=src?'1':'0';
 if(src){el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`${String(m?.name||'회원')} 프로필 사진 크게 보기`);el.innerHTML=`<img src="${escAttr80(src)}" alt="${escAttr80(m?.name||'프로필')} 프로필"><span class="profileGender80 ${female?'female':'male'}">${female?'여':'남'}</span>`}
 else{el.setAttribute('aria-label',female?'여성':'남성');el.textContent=female?'여':'남'}
 return el;
}
function memberFromCard80(card){
 let id=String(card?.dataset?.memberId80||'');
 if(!id){const on=card?.querySelector('.pairBtn')?.getAttribute('onclick')||'';const mm=on.match(/openPairs\(['"]([^'"]+)['"]\)/);if(mm)id=mm[1]}
 if(!id){const on=card?.querySelector('[onclick*="openEditMember"]')?.getAttribute('onclick')||'';const mm=on.match(/openEditMember\(['"]([^'"]+)['"]\)/);if(mm)id=mm[1]}
 const m=id&&typeof M==='function'?M(id):null;if(m&&card)card.dataset.memberId80=id;return m||null;
}
function directIdentity80(card){return [...(card?.children||[])].find(x=>x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMark53'))||null}
function sameIdentity80(el,m){if(!el?.classList?.contains('profileIdentity80'))return false;const src=profileSrc80(m),photo=src?'1':'0',gender=String(m?.gender||'')==='여'?'여':'남';if(el.dataset.memberId!==String(m?.id||'')||el.dataset.gender!==gender||el.dataset.photo!==photo)return false;if(photo){const cur=el.querySelector('img')?.getAttribute('src')||'';return cur===src}return true}
function setMemberIdentity80(card,m){if(!card||!m)return;const current=directIdentity80(card);if(sameIdentity80(current,m)){card.classList.add('memberIdentityCard80');return}for(const x of [...card.children])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMark53'))x.remove();card.insertBefore(makeIdentity80(m,'member'),card.firstChild);card.classList.add('memberIdentityCard80')}
function setQueueIdentity80(card,m){if(!card||!m)return;const direct=[...card.children];let current=direct.find(x=>x.classList?.contains('profileIdentity80'))||null;if(!sameIdentity80(current,m)){for(const x of direct)if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText'))x.remove();const ord=card.querySelector('.ord'),el=makeIdentity80(m,'queue');if(ord)ord.insertAdjacentElement('afterend',el);else card.insertBefore(el,card.firstChild)}card.dataset.memberId80=String(m.id||'');card.classList.add('queueIdentityCard80')}
function decorateMembers80(){style80();const box=typeof $==='function'?$('members'):document.getElementById('members');if(!box)return;[...box.querySelectorAll('.memberCard')].forEach(card=>{const m=memberFromCard80(card);if(m)setMemberIdentity80(card,m)})}
function decorateQueue80(){style80();const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue(),cards=[...box.querySelectorAll('.queueCard')];cards.forEach((card,i)=>{const m=ids[i]&&typeof M==='function'?M(ids[i]):null;if(m)setQueueIdentity80(card,m)})}
function decorate80(){decorateMembers80();decorateQueue80()}

function closePopup80(){const modal=document.getElementById('profilePhotoModal80');if(!modal)return;modal.classList.remove('on');try{document.body.style.overflow=modal.dataset.prevOverflow||''}catch{}}
function modal80(){let modal=document.getElementById('profilePhotoModal80');if(modal)return modal;modal=document.createElement('div');modal.id='profilePhotoModal80';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="profilePhotoSheet80"><button type="button" class="profilePhotoClose80" aria-label="닫기">×</button><img class="profilePhotoImg80" alt="프로필 사진 크게 보기"><div class="profilePhotoName80"></div><div class="profilePhotoState80"></div></div>';modal.addEventListener('click',e=>{if(e.target===modal)closePopup80()});modal.querySelector('.profilePhotoClose80')?.addEventListener('click',closePopup80);document.body.appendChild(modal);return modal}
async function fullImage80(memberId,thumb){const gid=String(currentGroupId||''),key=gid+'|'+memberId;if(fullCache80.has(key))return fullCache80.get(key)||thumb;try{const u=new URL(PROFILE80);u.searchParams.set('groupId',gid);u.searchParams.set('memberId',String(memberId));u.searchParams.set('full','1');u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'고화질 사진을 불러오지 못했습니다.');const src=String(x.fullImage||x.image||thumb||'');fullCache80.set(key,src);return src}catch{return thumb}}
async function openPopup80(identity){if(!identity?.dataset?.memberId||identity.dataset.photo!=='1')return;const img0=identity.querySelector('img'),thumb=String(img0?.getAttribute('src')||img0?.src||'');if(!thumb)return;const memberId=identity.dataset.memberId,m=typeof M==='function'?M(memberId):null,name=String(m?.name||'');const modal=modal80(),img=modal.querySelector('.profilePhotoImg80'),title=modal.querySelector('.profilePhotoName80'),state=modal.querySelector('.profilePhotoState80');if(img)img.src=thumb;if(title)title.textContent=name;if(state)state.textContent='고화질 사진 불러오는 중…';modal.classList.add('on');try{modal.dataset.prevOverflow=document.body.style.overflow||'';document.body.style.overflow='hidden'}catch{}const full=await fullImage80(memberId,thumb);if(modal.classList.contains('on')&&img&&full)img.src=full;if(state)state.textContent=full&&full!==thumb?'고화질 보기':'저장된 프로필 사진 보기';setTimeout(()=>modal.querySelector('.profilePhotoClose80')?.focus(),0)}
window.openProfilePhoto80=openPopup80;window.closeProfilePhoto80=closePopup80;
if(!window.__kokmatchProfileEsc80){window.__kokmatchProfileEsc80=true;document.addEventListener('keydown',e=>{if(e.key==='Escape')closePopup80()})}
if(!window.__kokmatchProfileCapture80){window.__kokmatchProfileCapture80=true;document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const identity=t.closest('.profileIdentity80');if(!identity)return;const queue=identity.closest('#queue .queueCard'),member=identity.closest('#members .memberCard');if(!queue&&!member)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(identity.dataset.photo==='1')openPopup80(identity)},true)}

function timeout80(p,ms){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),ms))])}
function dataUrl80(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error('read'));r.onload=()=>res(String(r.result||''));r.readAsDataURL(file)})}
function imageSrc80(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(new Error('decode'));im.src=src})}
async function source80(file){if(typeof createImageBitmap==='function')try{return{source:await timeout80(createImageBitmap(file),6000),cleanup:s=>{try{s.close()}catch{}}}}catch{}const data=await timeout80(dataUrl80(file),7000);return{source:await timeout80(imageSrc80(data),7000),cleanup:()=>{}}}
function jpeg80(source,maxSide,q){const w=source.width||source.naturalWidth,h=source.height||source.naturalHeight;if(!w||!h)throw new Error('size');const scale=Math.min(1,maxSide/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),c=document.createElement('canvas');c.width=cw;c.height=ch;const g=c.getContext('2d');if(!g)throw new Error('canvas');g.fillStyle='#fff';g.fillRect(0,0,cw,ch);g.drawImage(source,0,0,w,h,0,0,cw,ch);return c.toDataURL('image/jpeg',q)}
async function encodeFull80(file){if(!file||file.size>30*1024*1024)return'';let obj=null;try{obj=await source80(file);let d=jpeg80(obj.source,2048,.9);for(const q of [.84,.78,.72,.66]){if(d.length<=2350000)break;d=jpeg80(obj.source,2048,q)}if(d.length>2350000)d=jpeg80(obj.source,1600,.8);if(d.length>2450000)d=jpeg80(obj.source,1400,.72);return d.length<=2500000?d:''}catch{return''}finally{if(obj)try{obj.cleanup(obj.source)}catch{}}}
async function saveFull80(memberId,full){if(!memberId||!full||!T||!currentGroupId)return false;let thumb=profileSrc80(typeof M==='function'?M(memberId):null);if(!thumb){try{const u=new URL(PROFILE80);u.searchParams.set('groupId',String(currentGroupId));u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store'}),x=await r.json().catch(()=>({}));thumb=String(x.profiles?.[memberId]?.image||'')}catch{}}if(!thumb)return false;const r=await fetch(PROFILE80,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+T},body:JSON.stringify({action:'save_profile',groupId:String(currentGroupId),image:thumb,fullImage:full}),cache:'no-store'});if(!r.ok)return false;fullCache80.set(String(currentGroupId)+'|'+memberId,full);return true}
const changePrev80=window.changeProfile53;
if(typeof changePrev80==='function'&&!changePrev80.__full80){const wrapped=async function(input){const file=input?.files?.[0]||null,fullPromise=file?encodeFull80(file):Promise.resolve('');await changePrev80(input);if(!file)return;const id=String(window.resolveProfileMemberId54?.()||me?.memberId||'');if(!id)return;const full=await fullPromise;if(!full)return;const ok=await saveFull80(id,full);const status=document.getElementById('profileStatus65');if(status&&ok)status.textContent='프로필 사진 저장 완료 · 고화질 크게보기 준비됨'};wrapped.__full80=true;window.changeProfile53=wrapped;try{changeProfile53=wrapped}catch{}}

let raf80=0;function schedule80(){if(raf80)return;raf80=requestAnimationFrame(()=>{raf80=0;try{decorate80()}catch(e){console.warn('profile ui80',e)}})}
const rm80=renderMembers;renderMembers=function(){const r=rm80();schedule80();return r};const rq80=renderQueue;renderQueue=function(){const r=rq80();schedule80();return r};const ra80=renderAll;renderAll=function(){const r=ra80();schedule80();return r};
const observer80=new MutationObserver(schedule80);function start80(){style80();const members=typeof $==='function'?$('members'):document.getElementById('members'),queue=typeof $==='function'?$('queue'):document.getElementById('queue');if(members)observer80.observe(members,{childList:true,subtree:true});if(queue)observer80.observe(queue,{childList:true,subtree:true});schedule80()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start80,{once:true});else start80();
})();