(()=>{
if(window.__kokmatchV55Fix4)return;
window.__kokmatchV55Fix4=true;window.__kokmatchVersionLock='5.5';window.__kokmatchV55Patch='4.0';
const LOGIN55='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-login-v55';
const PROFILE55='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const TOKEN_KEY55='kokmatch_token',GROUP_KEY55='kokmatch_group_id';
let loginCandidates55=[],selectedCandidate55=null,pendingPin55='',loginSearchTimer55=0,loginSearchSeq55=0;
const profileByGroup55=new Map();let profileGroupSeen55='',profileLoadSeq55=0;
const esc55=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css55(){if(document.getElementById('v554style'))return;const s=document.createElement('style');s.id='v554style';s.textContent=`
.loginResults554{margin-top:10px;display:flex;flex-direction:column;gap:8px}.loginCandidate554{width:100%;border:1px solid var(--line,#d7dce5);background:#fff;border-radius:14px;padding:12px;text-align:left;cursor:pointer}.loginCandidate554:active{transform:scale(.99)}.loginCandidateTop554{display:flex;align-items:center;justify-content:space-between;gap:8px}.loginCandidateName554{font-size:16px;font-weight:950;color:#182230}.loginCandidateRole554{font-size:11px;font-weight:900;border-radius:999px;padding:4px 7px;background:#eef3ff;color:#2453d4;white-space:nowrap}.loginCandidateInfo554{margin-top:4px;font-size:13px;color:#566176;font-weight:750}.loginCandidateGroups554{margin-top:7px;font-size:12px;color:#697386;line-height:1.5}.loginSearchHint554{margin-top:10px;padding:11px;border-radius:12px;background:#f6f7f9;color:#667085;font-size:12px;line-height:1.45}.loginBack554{margin-top:8px;width:100%}.profileAvatar53 img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}
`;document.head.appendChild(s)}
function currentToken55(){return String(window.T||'')}
function currentGroup55(){return String(window.currentGroupId||'')}
function genderAvatar55(m){return `<div class="avatar ${m?.gender==='여'?'female':'male'}">●</div>`}
function safeAvatar55(m){const g=currentGroup55(),id=String(m?.id||''),p=profileByGroup55.get(g),img=p?.[id]?.image||'';return img?`<div class="avatar profileAvatar53"><img src="${img}" alt="${esc55(m?.name||'프로필')} 프로필"></div>`:genderAvatar55(m)}
function installAvatar55(){window.avatar=safeAvatar55;try{avatar=safeAvatar55}catch{}}
async function loadSafeProfiles55(groupId=currentGroup55(),force=false){const g=String(groupId||'');if(!g||g==='__global__'||!currentToken55())return;if(!force&&profileByGroup55.has(g))return;const seq=++profileLoadSeq55;try{const u=new URL(PROFILE55);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+currentToken55()},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필을 불러오지 못했습니다.');if(seq!==profileLoadSeq55||g!==currentGroup55())return;profileByGroup55.set(g,x.profiles||{});profileGroupSeen55=g;installAvatar55();try{renderMembers();renderQueue();if(window.currentView==='settings')renderSettings()}catch{}}catch(e){console.warn('safe profile load',e)}}
function watchGroup55(){const g=currentGroup55();if(g&&g!=='__global__'&&g!==profileGroupSeen55){profileGroupSeen55=g;installAvatar55();loadSafeProfiles55(g,true)}}
async function loginPost55(body){const r=await fetch(LOGIN55,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'로그인 처리에 실패했습니다.');return x}
function birthGrade55(c){const a=[];if(c.year)a.push(`${esc55(c.year)}년생`);if(c.grade)a.push(`${esc55(c.grade)}${String(c.grade).includes('급')?'':'급'}`);if(c.gender)a.push(esc55(c.gender));return a.join(' · ')||'회원정보 확인'}
function groupsText55(c){const ms=Array.isArray(c.memberships)?c.memberships:[];if(!ms.length)return c.isDeveloper?'전체 모임 관리 계정':'가입 모임 정보 없음';return ms.map(m=>`${esc55(m.groupName)}${m.roleLabel?` (${esc55(m.roleLabel)})`:''}`).join(' · ')}
function renderCandidateResults55(items){const box=document.getElementById('loginResults554');if(!box)return;loginCandidates55=Array.isArray(items)?items:[];if(!loginCandidates55.length){box.innerHTML='<div class="loginSearchHint554">일치하는 회원이 없습니다.</div>';return}box.innerHTML=loginCandidates55.map((c,i)=>`<button class="loginCandidate554" type="button" onclick="selectLoginCandidate554(${i})"><div class="loginCandidateTop554"><span class="loginCandidateName554">${esc55(c.name)}</span><span class="loginCandidateRole554">${c.isDeveloper?'개발자':esc55(c.memberships?.[0]?.roleLabel||'회원')}</span></div><div class="loginCandidateInfo554">${birthGrade55(c)}</div><div class="loginCandidateGroups554"><b>가입 모임</b> · ${groupsText55(c)}</div></button>`).join('')}
window.lookupLoginCandidates554=async function(){const input=document.getElementById('loginName'),box=document.getElementById('loginResults554');if(!input||!box)return;const name=input.value.trim(),seq=++loginSearchSeq55;if(!name){loginCandidates55=[];box.innerHTML='<div class="loginSearchHint554">이름을 입력하면 등록된 회원정보와 가입 모임이 표시됩니다.</div>';return}box.innerHTML='<div class="loginSearchHint554">회원정보를 찾는 중…</div>';try{const x=await loginPost55({action:'probe',name});if(seq!==loginSearchSeq55)return;renderCandidateResults55(x.candidates||[])}catch(e){if(seq!==loginSearchSeq55)return;loginCandidates55=[];box.innerHTML=`<div class="loginSearchHint554">${esc55(e.message)}</div>`}};
window.scheduleLoginLookup554=function(){clearTimeout(loginSearchTimer55);loginSearchTimer55=setTimeout(()=>window.lookupLoginCandidates554(),220)};
window.selectLoginCandidate554=function(i){const c=loginCandidates55[Number(i)];if(!c)return;selectedCandidate55=c;pendingPin55='';const b=document.getElementById('loginBox');if(!b)return;b.innerHTML=`<h2>PIN 인증</h2><div class="authName">${esc55(c.name)}</div><div class="loginSearchHint554" style="margin-bottom:10px"><b>${birthGrade55(c)}</b><br>가입 모임 · ${groupsText55(c)}</div><div class="field"><label>PIN</label><input id="loginPin" type="password" inputmode="numeric" autocomplete="current-password" placeholder="PIN 입력"></div><button class="btn pri" style="width:100%" type="button" onclick="submitSelectedLogin554()">로그인</button><div id="loginErr" class="error"></div><button class="btn ghost loginBack554" type="button" onclick="renderLoginName()">← 회원 다시 선택</button>`;setTimeout(()=>document.getElementById('loginPin')?.focus(),50)};
async function finishLogin55(x){window.T=x.token;try{T=x.token}catch{}localStorage.setItem(TOKEN_KEY55,x.token);if(x.groupId){window.currentGroupId=x.groupId;try{currentGroupId=x.groupId}catch{}localStorage.setItem(GROUP_KEY55,x.groupId)}document.getElementById('login')?.classList.add('hide');pendingPin55='';await loadState();watchGroup55()}
window.submitSelectedLogin554=async function(groupId=''){if(!selectedCandidate55)return;const pin=document.getElementById('loginPin')?.value.trim()||pendingPin55,err=document.getElementById('loginErr');if(err)err.textContent='';if(!pin){if(err)err.textContent='PIN을 입력해주세요.';return}pendingPin55=pin;try{const x=await loginPost55({action:'login',name:selectedCandidate55.name,pin,candidateId:selectedCandidate55.candidateId,groupId});if(x.groupChoiceRequired){const b=document.getElementById('loginBox');b.innerHTML=`<h2>접속할 모임 선택</h2><div class="authName">${esc55(selectedCandidate55.name)}</div><div class="note">PIN 인증이 확인된 모임이 여러 개입니다.</div><div class="choiceList">${(x.choices||[]).map(c=>`<button class="choiceBtn" type="button" onclick="submitSelectedLogin554('${esc55(c.groupId)}')"><b>${esc55(c.groupName)}</b><span class="meta">${esc55(c.roleLabel)}</span></button>`).join('')}</div><div id="loginErr" class="error"></div><button class="btn ghost loginBack554" type="button" onclick="renderLoginName()">처음으로</button>`;return}await finishLogin55(x)}catch(e){const el=document.getElementById('loginErr');if(el)el.textContent=e.message;else alert(e.message)}};
window.renderLoginName=function(){css55();selectedCandidate55=null;pendingPin55='';loginCandidates55=[];const b=document.getElementById('loginBox');if(!b)return;window.__kokmatchLoginRenderAllow552=Date.now()+1500;b.innerHTML=`<h1>🏸 콕매치</h1><div class="meta" style="font-size:14px;margin-bottom:18px">모임 회원 로그인</div><div class="field"><label>등록된 이름</label><input id="loginName" autocomplete="username" placeholder="이름 입력" oninput="scheduleLoginLookup554()"></div><div id="loginResults554" class="loginResults554"><div class="loginSearchHint554">이름을 입력하면 <b>이름 · 년생 · 급수 · 가입된 모임</b>을 확인하고 회원을 선택할 수 있습니다.</div></div><div id="loginErr" class="error"></div>`;setTimeout(()=>document.getElementById('loginName')?.focus(),50)};
window.startLogin=function(){window.lookupLoginCandidates554()};
window.submitLogin=function(groupId=''){return window.submitSelectedLogin554(groupId)};
try{renderLoginName=window.renderLoginName;startLogin=window.startLogin;submitLogin=window.submitLogin}catch{}
const oldChange=window.changeProfile53;if(typeof oldChange==='function'&&!oldChange.__v554){const w=async function(input){const r=await oldChange.call(this,input);const g=currentGroup55();if(g&&g!=='__global__')await loadSafeProfiles55(g,true);return r};w.__v554=true;window.changeProfile53=w;try{changeProfile53=w}catch{}}
const oldDelete=window.deleteProfile53;if(typeof oldDelete==='function'&&!oldDelete.__v554){const w=async function(){const r=await oldDelete.call(this);const g=currentGroup55();if(g&&g!=='__global__')await loadSafeProfiles55(g,true);return r};w.__v554=true;window.deleteProfile53=w;try{deleteProfile53=w}catch{}}
function enforce55(){window.__kokmatchVersionLock='5.5';document.documentElement.dataset.kokmatchVersion='5.5';document.title='콕매치 v5.5';installAvatar55();watchGroup55()}
css55();installAvatar55();setTimeout(()=>{enforce55();if(!currentToken55())window.renderLoginName();else watchGroup55()},0);setInterval(enforce55,500);
})();