(()=>{
'use strict';
if(window.__kokmatchV56Fix4)return;
window.__kokmatchV56Fix4=true;
window.__kokmatchV56Fix4Patch='1.0';
window.__kokmatchV56Fix4Build='2026.08.28.7';
const AUTH='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-auth-v38';
const LOGIN='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-login-v55';
const MULTI='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-multi-api';
const PROFILE='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const TOKEN_KEY='kokmatch_token',GROUP_KEY='kokmatch_group_id';
let membershipsBusy=false,loginBusy=false,loginName='',selectedCandidate=null,photoSeq=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){try{return String((typeof T!=='undefined'&&T)||window.T||localStorage.getItem(TOKEN_KEY)||'')}catch{return String(window.T||'')}}
function gid(){try{return String((typeof currentGroupId!=='undefined'&&currentGroupId)||window.currentGroupId||localStorage.getItem(GROUP_KEY)||'')}catch{return String(window.currentGroupId||'')}}
function mine(){try{return (typeof me!=='undefined'&&me)||window.me||null}catch{return window.me||null}}
function grp(){try{return (typeof group!=='undefined'&&group)||window.group||null}catch{return window.group||null}}
function setToken(v){v=String(v||'');try{T=v}catch{};window.T=v;try{localStorage.setItem(TOKEN_KEY,v)}catch{}}
function setGid(v){v=String(v||'');try{currentGroupId=v}catch{};window.currentGroupId=v;try{if(v)localStorage.setItem(GROUP_KEY,v);else localStorage.removeItem(GROUP_KEY)}catch{}}
function err(e){return e?.message||String(e||'처리 중 오류가 발생했습니다.')}
async function json(url,opt={}){const r=await fetch(url,{cache:'no-store',...opt}),x=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(x.error||x.message||`요청 실패 (${r.status})`);e.status=r.status;throw e}return x}
function css(){if(document.getElementById('v56fix4style'))return;const s=document.createElement('style');s.id='v56fix4style';s.textContent=`
#groupBtn:not(:disabled){cursor:pointer}.groupChoice56{display:flex;flex-direction:column;gap:8px;margin-top:12px}.groupChoice56 button{width:100%;text-align:left;padding:12px 13px;border:1px solid var(--line);border-radius:12px;background:#fff;color:inherit}.groupChoice56 button.current{border-color:#2453d4;background:#f3f6ff}.groupChoice56 b{display:block;font-size:14px}.groupChoice56 small{display:block;margin-top:3px;color:var(--mut);font-size:12px}
#members .profileIdentity80 img,#queue .profileIdentity80 img,.profileViewer56 img{-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important;-webkit-user-drag:none!important}.profileViewer56{position:fixed;inset:0;z-index:2147483000;background:rgba(0,0,0,.92);display:flex;align-items:center;justify-content:center;padding:16px;box-sizing:border-box}.profileViewer56.hide{display:none}.profileViewer56 img{display:block;max-width:100%;max-height:86vh;object-fit:contain;border-radius:12px;background:#111}.profileViewerClose56{position:absolute;top:max(14px,env(safe-area-inset-top));right:14px;width:42px;height:42px;border:0;border-radius:999px;background:rgba(255,255,255,.18);color:#fff;font-size:28px;line-height:42px;padding:0}.profileViewerStatus56{position:absolute;left:0;right:0;bottom:max(22px,env(safe-area-inset-bottom));text-align:center;color:#fff;font-size:13px;font-weight:800;text-shadow:0 1px 3px #000}
.loginCandidate56{display:flex;flex-direction:column;gap:8px;margin:12px 0}.loginCandidate56 button{width:100%;text-align:left;padding:13px;border:1px solid var(--line);border-radius:12px;background:#fff;color:inherit}.loginCandidate56 button:active{background:#f3f6ff}.loginCandidate56 b{display:block;font-size:15px}.loginCandidate56 span{display:block;margin-top:4px;color:var(--mut);font-size:12px;line-height:1.35}.loginBusy56{opacity:.65;pointer-events:none}
`;document.head.appendChild(s)}

/* 1) Group button: legacy renderHeader disables it for non-global users. Keep it enabled and use memberships. */
function ensureGroupButton(){const b=document.getElementById('groupBtn');if(!b||!mine())return;if(window.__kokmatchGroupSwitching12===true)return;if(b.disabled)b.disabled=false;b.classList.remove('groupSwitching12','switching52');const name=String(grp()?.name||'모임');if(!/▾/.test(b.textContent||''))b.textContent=name+' ▾';b.onclick=e=>{e?.preventDefault?.();e?.stopPropagation?.();window.openGroupSwitch56()}}
async function memberships(){const m=mine();if(!m)return[];if(m.globalAdmin){try{return ((typeof groups!=='undefined'&&groups)||window.groups||[]).map(g=>({groupId:String(g.groupId||g.group_id||''),groupName:String(g.name||g.groupName||'모임'),role:'admin',roleLabel:'개발자'})).filter(x=>x.groupId)}catch{return[]}}
 const x=await json(AUTH,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token()},body:JSON.stringify({action:'my_memberships',currentGroupId:gid()})});return Array.isArray(x.memberships)?x.memberships:[]}
window.openGroupSwitch56=async function(){if(membershipsBusy||!mine())return;membershipsBusy=true;try{if(typeof openModal!=='function')return;openModal('<h3>모임 변경</h3><div class="note">가입된 모임을 불러오는 중…</div>');const list=await memberships();if(!list.length){openModal('<h3>모임 변경</h3><div class="note">변경할 수 있는 가입 모임이 없습니다.</div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>');return}openModal('<h3>모임 변경</h3><div class="note">이동할 모임을 선택해주세요.</div><div id="groupChoice56" class="groupChoice56"></div><div id="groupChoiceErr56" class="error"></div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>');const box=document.getElementById('groupChoice56');for(const x of list){const b=document.createElement('button');b.type='button';const current=String(x.groupId)===gid();b.className=current?'current':'';b.innerHTML=`<b>${esc(x.groupName||'모임')}${current?' · 현재':''}</b><small>${esc(x.roleLabel||'')}</small>`;b.onclick=async()=>{if(current){try{closeModal()}catch{};return}box?.querySelectorAll('button').forEach(y=>y.disabled=true);try{const fn=mine()?.globalAdmin?window.adminSwitchGroup38:window.switchOwnGroup38;if(typeof fn!=='function')throw new Error('모임 전환 기능을 불러오지 못했습니다.');const ok=await fn(String(x.groupId),mine()?.globalAdmin?'members':undefined);if(ok!==true)throw new Error('모임을 변경하지 못했습니다.');try{closeModal()}catch{};ensureGroupButton()}catch(e){const er=document.getElementById('groupChoiceErr56');if(er)er.textContent=err(e);box?.querySelectorAll('button').forEach(y=>y.disabled=false)}};box?.appendChild(b)}}catch(e){try{openModal(`<h3>모임 변경</h3><div class="error">${esc(err(e))}</div><div class="acts"><button class="btn ghost" type="button" onclick="closeModal()">닫기</button></div>`)}catch{}}finally{membershipsBusy=false;setTimeout(ensureGroupButton,0)}};
window.openGroupSwitch=window.openGroupSwitch56;try{openGroupSwitch=window.openGroupSwitch56}catch{}

/* 2) High-resolution in-app profile viewer. */
function viewer(){let v=document.getElementById('profileViewer56');if(v)return v;v=document.createElement('div');v.id='profileViewer56';v.className='profileViewer56 hide';v.innerHTML='<button class="profileViewerClose56" type="button" aria-label="닫기">×</button><img alt="프로필 고화질 사진"><div class="profileViewerStatus56"></div>';v.addEventListener('click',e=>{if(e.target===v||e.target.closest('.profileViewerClose56'))closePhoto()});v.addEventListener('contextmenu',e=>e.preventDefault(),true);document.body.appendChild(v);return v}
function closePhoto(){photoSeq++;const v=document.getElementById('profileViewer56');if(v)v.classList.add('hide')}
window.closeProfilePhoto56=closePhoto;
window.openProfilePhoto80=async function(el){css();const node=el instanceof Element?el:null,id=String(node?.dataset?.memberId||node?.dataset?.memberId56||node?.closest?.('[data-member-id56],[data-member-id80]')?.dataset?.memberId56||node?.closest?.('[data-member-id56],[data-member-id80]')?.dataset?.memberId80||'');if(!id||!token()||!gid())return;const seq=++photoSeq,v=viewer(),im=v.querySelector('img'),st=v.querySelector('.profileViewerStatus56'),thumb=String(node?.querySelector?.('img')?.getAttribute('src')||'');if(im&&thumb)im.src=thumb;if(st)st.textContent='고화질 사진 불러오는 중…';v.classList.remove('hide');try{const u=new URL(PROFILE);u.searchParams.set('groupId',gid());u.searchParams.set('memberId',id);u.searchParams.set('full','1');u.searchParams.set('t',Date.now());const x=await json(u.toString(),{headers:{authorization:'Bearer '+token()}});if(seq!==photoSeq)return;const full=String(x.fullImage||x.image||thumb||'');if(im&&full)im.src=full;if(st)st.textContent=full?'고화질 프로필 사진':'프로필 사진을 불러오지 못했습니다.'}catch(e){if(seq!==photoSeq)return;if(st)st.textContent='고화질 사진을 불러오지 못했습니다.'}}
window.addEventListener('contextmenu',e=>{const t=e.target instanceof Element?e.target:null;if(t?.closest?.('#members .profileIdentity80 img,#queue .profileIdentity80 img,#profileViewer56 img'))e.preventDefault()},true);

/* 3) Name -> exact candidate -> PIN login. Same-name rows are never collapsed. */
function box(){return document.getElementById('loginBox')}
function root(){return document.getElementById('login')}
function prep(i){if(!i)return;i.style.fontSize='16px';i.setAttribute('autocapitalize','off');i.setAttribute('spellcheck','false')}
function busy(on){const b=box();b?.classList.toggle('loginBusy56',!!on);b?.querySelectorAll('button,input').forEach(x=>x.disabled=!!on)}
function ageText(c){const a=String(c?.age||'').trim(),y=String(c?.year||'').trim();if(a)return /^\d+$/.test(a)?`${a}세`:a;if(y)return `${y}년생`;return '나이 미등록'}
function gradeText(c){const g=String(c?.grade||'').trim();return g?`${g}급`:'급수 미등록'}
function renderName(message=''){css();loginName='';selectedCandidate=null;const b=box();if(!b)return;b.innerHTML=`<h1>🏸 콕매치</h1><div class="meta" style="font-size:14px;margin-bottom:18px">모임 회원 로그인</div><div class="field"><label>등록된 이름</label><input id="loginName" type="text" autocomplete="username" enterkeyhint="go" placeholder="이름"></div><button id="loginNext56" class="btn pri" type="button" style="width:100%">로그인하기</button><div id="loginErr" class="error">${esc(message)}</div>`;const i=document.getElementById('loginName');prep(i);document.getElementById('loginNext56')?.addEventListener('click',probe);i?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();probe()}});root()?.classList.remove('hide')}
function renderCandidates(list){const b=box();if(!b)return;b.innerHTML=`<h2>회원 선택</h2><div class="authName">${esc(loginName)}</div><div class="note">본인의 나이, 모임, 급수를 확인하고 선택해주세요.</div><div id="loginCandidate56" class="loginCandidate56"></div><div id="loginErr" class="error"></div><button id="loginBack56" class="btn ghost" type="button" style="width:100%;margin-top:8px">← 이름 다시 입력</button>`;const out=document.getElementById('loginCandidate56');for(const c of list){const bt=document.createElement('button');bt.type='button';const detail=c.isDeveloper?'개발자 · 전체 모임':`${ageText(c)} · ${String(c.groupName||'모임')} · ${gradeText(c)}`;bt.innerHTML=`<b>${esc(c.name||loginName)}</b><span>${esc(detail)}</span>`;bt.addEventListener('click',()=>{selectedCandidate=c;renderPin(c)});out?.appendChild(bt)}document.getElementById('loginBack56')?.addEventListener('click',()=>renderName())}
function renderPin(c,message=''){const b=box();if(!b)return;const detail=c?.isDeveloper?'개발자 · 전체 모임':`${ageText(c)} · ${String(c?.groupName||'모임')} · ${gradeText(c)}`;b.innerHTML=`<h2>PIN 입력</h2><div class="authName">${esc(c?.name||loginName)}</div><div class="note">${esc(detail)}</div><div class="field"><label>PIN 번호</label><input id="loginPin56" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="12" autocomplete="off" enterkeyhint="done" placeholder="PIN 입력"></div><button id="loginSubmit56" class="btn pri" type="button" style="width:100%">로그인</button><div id="loginErr" class="error">${esc(message)}</div><button id="loginBack56" class="btn ghost" type="button" style="width:100%;margin-top:8px">← 회원 다시 선택</button>`;const p=document.getElementById('loginPin56');prep(p);p?.addEventListener('input',()=>{p.value=p.value.replace(/\D/g,'').slice(0,12)});p?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();submit()}});document.getElementById('loginSubmit56')?.addEventListener('click',submit);document.getElementById('loginBack56')?.addEventListener('click',()=>probe(true));setTimeout(()=>p?.focus(),30)}
async function probe(reuse=false){if(loginBusy)return;const raw=reuse?loginName:String(document.getElementById('loginName')?.value||'').trim(),name=typeof raw.normalize==='function'?raw.normalize('NFC'):raw;if(!name){const e=document.getElementById('loginErr');if(e)e.textContent='이름을 입력해주세요.';return}loginName=name;loginBusy=true;busy(true);try{const x=await json(LOGIN,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'probe',name})});const list=Array.isArray(x.candidates)?x.candidates:[];if(!list.length)throw new Error('등록된 회원 이름이 없습니다.');renderCandidates(list)}catch(e){if(reuse)renderName(err(e));else{busy(false);const x=document.getElementById('loginErr');if(x)x.textContent=err(e)}}finally{loginBusy=false;busy(false)}}
async function stateAfterLogin(tok,target,isGlobal){const u=new URL(MULTI);u.searchParams.set('api','state');if(target&&!isGlobal)u.searchParams.set('groupId',target);u.searchParams.set('t',Date.now());return json(u.toString(),{headers:{authorization:'Bearer '+tok}})}
function applyState(x){if(!x?.data||!x?.user||!x?.group)throw new Error('로그인 후 모임정보를 불러오지 못했습니다.');try{S=x.data;me=x.user;group=x.group;if(Array.isArray(x.groups))groups=x.groups;currentGroupId=String(x.group.groupId||'')}catch(e){throw e}try{window.S=S;window.me=me;window.group=group;window.groups=typeof groups!=='undefined'?groups:window.groups;window.currentGroupId=currentGroupId}catch{};setGid(String(x.group.groupId||''));try{if(typeof normalizeClient==='function')normalizeClient();if(typeof renderAll==='function')renderAll()}catch{};root()?.classList.add('hide');requestAnimationFrame(()=>{root()?.classList.add('hide');ensureGroupButton()});setTimeout(ensureGroupButton,80)}
async function submit(){if(loginBusy||!selectedCandidate)return;const pin=String(document.getElementById('loginPin56')?.value||'').replace(/\D/g,'').trim();if(!pin){const e=document.getElementById('loginErr');if(e)e.textContent='PIN을 입력해주세요.';return}loginBusy=true;busy(true);let newToken='';try{const x=await json(LOGIN,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',name:loginName,candidateId:selectedCandidate.candidateId,pin})});newToken=String(x.token||'');if(!newToken)throw new Error('로그인 토큰을 받지 못했습니다.');setToken(newToken);if(x.groupId)setGid(String(x.groupId));const st=await stateAfterLogin(newToken,String(x.groupId||''),x.globalAdmin===true);applyState(st)}catch(e){if(newToken){setToken('');setGid('')}busy(false);renderPin(selectedCandidate,err(e))}finally{loginBusy=false;busy(false)}}
function installLogin(){window.renderLoginName=renderName;window.startLogin=probe;window.submitLogin=submit;try{renderLoginName=renderName;startLogin=probe;submitLogin=submit}catch{};if(!token()&&!mine()&&!loginBusy){const b=box();if(b&&!b.querySelector('#loginName,#loginCandidate56,#loginPin56'))renderName()}}

function install(){css();window.openGroupSwitch=window.openGroupSwitch56;try{openGroupSwitch=window.openGroupSwitch56}catch{};installLogin();ensureGroupButton()}
install();
const mo=new MutationObserver(()=>{ensureGroupButton()});
try{mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled']})}catch{}
setInterval(()=>{installLogin();ensureGroupButton();if(window.openGroupSwitch!==window.openGroupSwitch56)window.openGroupSwitch=window.openGroupSwitch56},250);
})();