(()=>{
if(window.__kokmatchV56Core)return;
window.__kokmatchV56Core=true;
window.__kokmatchV56=true;
window.__kokmatchV56Patch='1.3';

const VERSION='5.6';
const PROFILE='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const AUTH='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-auth-v38';
let cacheGroup='', profiles={}, profileLoadedGroup='', profileBusy=null, profileBusyGroup='', profileGeneration=0, profileRetryAt=0;
let lastGroup='', switchBusy56=false, versionGuardBusy=false, raf56=0;

function appToken(){try{return String(typeof T!=='undefined'?(T||''):'')}catch{return''}}
function appGroupId(){try{return String(typeof currentGroupId!=='undefined'?(currentGroupId||''):'')}catch{return''}}
function appMe(){try{return typeof me!=='undefined'?me:null}catch{return null}}
function appGroup(){try{return typeof group!=='undefined'?group:null}catch{return null}}
function appView(){try{return String(typeof currentView!=='undefined'?(currentView||'members'):'members')}catch{return'members'}}
function setToken56(v){v=String(v||'');try{T=v}catch{};try{window.T=v}catch{};try{localStorage.setItem(typeof TOKEN_KEY!=='undefined'?TOKEN_KEY:'kokmatch_token',v)}catch{}}
function setGroupId56(v){v=String(v||'');try{currentGroupId=v}catch{};try{window.currentGroupId=v}catch{};try{localStorage.setItem(typeof GROUP_KEY!=='undefined'?GROUP_KEY:'kokmatch_group_id',v)}catch{}}
function mirrorState56(){try{window.T=appToken();window.currentGroupId=appGroupId();window.me=appMe();window.group=appGroup();window.currentView=appView()}catch{}}

const esc56=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gender56(m){const g=String(m?.gender||'').trim().toLowerCase();return ['여','여자','여성','f','female'].includes(g)?'여':'남'}
function photo56(m){const g=appGroupId(),id=String(m?.id||'');return cacheGroup===g?String(profiles?.[id]?.image||''):''}
function avatar56(m){const p=photo56(m),female=gender56(m)==='여';return p?`<div class="avatar profileAvatar53 ${female?'female':'male'}"><img src="${p}" alt="${esc56(m?.name||'프로필')} 프로필"></div>`:`<div class="avatar ${female?'female':'male'}">●</div>`}
function installAvatar56(){try{avatar=avatar56}catch{try{window.avatar=avatar56}catch{}}}

function writeVersion56(){if(versionGuardBusy)return;versionGuardBusy=true;try{document.documentElement.dataset.kokmatchVersion=VERSION;document.title='콕매치 v'+VERSION;for(const id of ['currentVersion51','currentVersion52']){const e=document.getElementById(id);if(e)e.textContent='v'+VERSION}}finally{versionGuardBusy=false}}
function lockVersion56(){try{window.__kokmatchVersionLock=VERSION}catch{};writeVersion56()}

function memberById56(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function memberForCard56(card){let id='';const p=card?.querySelector?.('.pairBtn')?.getAttribute('onclick')||'';const hit=p.match(/openPairs\(['"]([^'"]+)['"]\)/);if(hit)id=hit[1];if(!id)id=String(card?.dataset?.memberId80||card?.dataset?.memberId56||'');const m=memberById56(id);if(m){card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}return m}
function queueMembers56(){try{return typeof sortedQueue==='function'?sortedQueue().map(id=>memberById56(id)):[]}catch{return[]}}
function makeIdentity56(m,queue=false){const p=photo56(m),female=gender56(m)==='여',d=document.createElement('div');d.className=`avatar profileIdentity80 genderVisual10 ${p?'profileTap80 profileAvatar53':'genderFallback80 genderAvatar39'} ${female?'female':'male'}${queue?' queueProfile53':''}`;d.dataset.memberId=String(m?.id||'');d.dataset.memberId56=String(m?.id||'');d.dataset.gender=female?'여':'남';d.dataset.photo=p?'1':'0';d.setAttribute('aria-label',p?`${String(m?.name||'회원')} 프로필 사진 크게 보기`:(female?'여성':'남성'));if(p){d.setAttribute('role','button');d.setAttribute('tabindex','0');const im=document.createElement('img');im.src=p;im.alt=`${String(m?.name||'프로필')} 프로필`;d.appendChild(im)}else d.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.5-5 3.2-8 7.5-8s7 3 7.5 8z"></path></svg>';return d}
function directIdentity56(card){return [...(card?.children||[])].find(x=>x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('queueProfile53'))}
function sameIdentity56(el,m){if(!el||!m)return false;const p=photo56(m),g=gender56(m);return String(el.dataset?.memberId||el.dataset?.memberId56||'')===String(m.id)&&String(el.dataset?.gender||'')===g&&String(el.dataset?.photo||'0')===(p?'1':'0')&&(!p||String(el.querySelector?.('img')?.getAttribute('src')||'')===p)}
function clearDirect56(card){for(const x of [...(card?.children||[])])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderPerson57')||x.classList?.contains('genderMini39')||x.classList?.contains('genderMark53')||x.classList?.contains('v54genderText')||x.classList?.contains('queueProfile53'))x.remove()}
function fixMemberCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);card.insertBefore(makeIdentity56(m,false),card.firstChild)}card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}
function fixQueueCard56(card,m){if(!m)return;const cur=directIdentity56(card);if(!sameIdentity56(cur,m)){clearDirect56(card);const d=makeIdentity56(m,true),ord=card.querySelector('.ord');if(ord)ord.insertAdjacentElement('afterend',d);else card.insertBefore(d,card.firstChild)}card.dataset.memberId56=String(m.id);card.dataset.memberId80=String(m.id)}
function patchSettingsPhoto56(){try{const card=document.getElementById('profileCard53');if(!card)return;const id=String(appMe()?.memberId||''),p=cacheGroup===appGroupId()?String(profiles?.[id]?.image||''):'';const prev=card.querySelector('.profilePreview53');if(prev){if(p){const cur=prev.querySelector('img')?.getAttribute('src')||'';if(cur!==p)prev.innerHTML=`<img src="${p}" alt="내 프로필 사진">`}else if(prev.querySelector('img')){const m=memberById56(id);prev.innerHTML=m?avatar56(m):''}}const del=card.querySelector('.profileBtns53 .btn.ghost');if(p&&!del){const box=card.querySelector('.profileBtns53');if(box)box.insertAdjacentHTML('beforeend','<button class="btn ghost" type="button" onclick="deleteProfile53()">기본 사진으로</button>')}else if(!p&&del)del.remove()}catch(e){console.warn('v5.6 settings photo',e)}}
function decorateLogin56(){try{const box=document.getElementById('loginBox');if(!box)return;const h=String(box.querySelector('h2')?.textContent||'');if(h==='회원 선택'){const note=box.querySelector('.note');if(note)note.textContent='같은 이름의 회원이 있습니다. 이름과 출생연도를 확인하고 본인을 선택해주세요.';box.querySelectorAll('.choiceList .choiceBtn').forEach(b=>{b.querySelector('small')?.remove();const s=b.querySelector('span');if(s){const year=(String(s.textContent||'').match(/\d{4}년생|출생연도 미등록/)||[])[0]||'';s.textContent=year}})}else if(/모임 PIN/.test(h)){box.querySelectorAll('.loginMember33 small').forEach(x=>x.remove())}}catch{}}
function canonicalize56(){lockVersion56();installAvatar56();mirrorState56();try{document.querySelectorAll('#members .memberCard').forEach(card=>fixMemberCard56(card,memberForCard56(card)));const ms=queueMembers56(),cards=[...document.querySelectorAll('#queue .queueCard')];cards.forEach((card,i)=>fixQueueCard56(card,ms[i]||null));patchSettingsPhoto56();decorateLogin56()}catch(e){console.warn('v5.6 identity',e)}}

function resetProfiles56(g=''){profileGeneration++;cacheGroup=String(g||'');profiles={};profileLoadedGroup='';profileRetryAt=0}
async function fetchProfiles56(g,generation){const u=new URL(PROFILE);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+appToken()},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 조회 실패');if(generation!==profileGeneration||g!==appGroupId())return profiles;profiles=x&&typeof x.profiles==='object'&&x.profiles?x.profiles:{};cacheGroup=g;profileLoadedGroup=g;profileRetryAt=0;canonicalize56();try{if(typeof renderMembers==='function')renderMembers();if(typeof renderQueue==='function')renderQueue();if(appView()==='settings'&&typeof renderSettings==='function')renderSettings()}catch{};requestAnimationFrame(canonicalize56);return profiles}
function loadProfiles56(group=appGroupId(),force=false){const g=String(group||'');if(!g||g==='__global__'||!appToken())return Promise.resolve(profiles);if(g!==cacheGroup)resetProfiles56(g);if(profileBusy&&profileBusyGroup===g)return profileBusy;if(!force&&profileLoadedGroup===g)return Promise.resolve(profiles);if(!force&&Date.now()<profileRetryAt)return Promise.resolve(profiles);const generation=profileGeneration;profileBusyGroup=g;const p=fetchProfiles56(g,generation).catch(e=>{if(generation===profileGeneration&&g===appGroupId())profileRetryAt=Date.now()+3000;console.warn('v5.6 profiles',e);canonicalize56();return profiles}).finally(()=>{if(profileBusy===p){profileBusy=null;profileBusyGroup=''}});profileBusy=p;return p}
function watch56(){const g=appGroupId();if(g!==lastGroup){lastGroup=g;resetProfiles56(g);canonicalize56();if(g&&g!=='__global__'&&appToken())loadProfiles56(g,false);return}if(g&&g!=='__global__'&&appToken()&&profileLoadedGroup!==g&&!profileBusy&&Date.now()>=profileRetryAt)loadProfiles56(g,false)}

function wrapRender56(name){try{const f=window[name]||eval(name);if(typeof f!=='function'||f.__v56core)return;const w=function(){const r=f.apply(this,arguments);queueMicrotask(()=>{watch56();canonicalize56()});return r};w.__v56core=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}catch{}}
function wrapProfileAction56(name){try{const f=window[name];if(typeof f!=='function'||f.__v56core)return;const w=async function(){const g=appGroupId();const r=await f.apply(this,arguments);if(g===appGroupId()){resetProfiles56(g);await loadProfiles56(g,true);canonicalize56()}return r};w.__v56core=true;window[name]=w;try{eval(`${name}=window[name]`)}catch{}}catch{}}

async function postAuth56(body,tok=appToken()){const r=await fetch(AUTH,{method:'POST',headers:{'content-type':'application/json',...(tok?{authorization:'Bearer '+tok}:{})},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(x.error||'모임 전환에 실패했습니다.');e.status=r.status;throw e}return x}
function switchUi56(on){const b=document.getElementById('groupBtn');if(!b)return;if(on){b.disabled=true;b.classList.add('groupSwitching12');b.classList.add('switching52');b.dataset.v56old=b.textContent||'';b.textContent='모임 변경 중…'}else{b.classList.remove('groupSwitching12','switching52');b.style.pointerEvents='';try{if(typeof renderHeader==='function')renderHeader();else b.disabled=false}catch{b.disabled=false}if(b.textContent==='모임 변경 중…'&&b.dataset.v56old)b.textContent=b.dataset.v56old;delete b.dataset.v56old;setTimeout(()=>{try{if(typeof renderHeader==='function')renderHeader()}catch{}},250);setTimeout(()=>{try{if(typeof renderHeader==='function')renderHeader()}catch{}},1000)}}
async function loadTarget56(target){await loadState(true);mirrorState56();const g=appGroupId(),grp=String(appGroup()?.groupId||'');if(g!==target||grp!==target)throw new Error('선택한 모임 정보를 불러오지 못했습니다.');return true}
async function restore56(oldG,oldT,oldView){setToken56(oldT);setGroupId56(oldG);resetProfiles56(oldG);try{await loadState(true)}catch{};try{if(oldView&&typeof goView==='function')goView(oldView)}catch{};mirrorState56();watch56();canonicalize56()}
async function switchStable56(target,adminHint=false,view=''){target=String(target||'');if(!target||switchBusy56)return false;const nowG=appGroupId();if(target===nowG){try{closeModal()}catch{};return true}const oldG=nowG,oldT=appToken(),oldView=String(view||appView()||'members'),global=appMe()?.globalAdmin===true||adminHint===true&&appMe()?.globalAdmin===true;switchBusy56=true;window.__kokmatchGroupSwitching12=true;switchUi56(true);try{if(!global){const x=await postAuth56({action:'switch_group',groupId:target},oldT);if(x.token)setToken56(x.token);target=String(x.groupId||target)}setGroupId56(target);try{closeModal()}catch{};resetProfiles56(target);lastGroup=target;await loadTarget56(target);try{if(oldView&&typeof goView==='function')goView(oldView)}catch{};try{if(oldView==='members'&&typeof window.memberPageGo46==='function')window.memberPageGo46(1)}catch{};try{window.scrollTo?.(0,0)}catch{};mirrorState56();canonicalize56();loadProfiles56(target,true).catch(()=>{});return true}catch(e){console.warn('v5.6 group switch',e);await restore56(oldG,oldT,oldView);if(typeof showError==='function')showError(e);else alert(e?.message||String(e));return false}finally{switchBusy56=false;window.__kokmatchGroupSwitching12=false;switchUi56(false);mirrorState56();canonicalize56()}}
function installSwitch56(){try{const own=async id=>switchStable56(id,appMe()?.globalAdmin===true,'');own.__v56stable=true;window.switchOwnGroup38=own;try{switchOwnGroup38=own}catch{};const adm=async(id,view='members')=>switchStable56(id,true,view);adm.__v56stable=true;window.adminSwitchGroup38=adm;try{adminSwitchGroup38=adm}catch{};const sg=(id,view='members')=>appMe()?.globalAdmin===true?adm(id,view):own(id);sg.__v56stable=true;window.switchGroup=sg;try{switchGroup=sg}catch{}}catch(e){console.warn('v5.6 switch install',e)}}

const versionMo56=new MutationObserver(()=>queueMicrotask(writeVersion56));
const identityMo56=new MutationObserver(()=>{if(raf56)return;raf56=requestAnimationFrame(()=>{raf56=0;canonicalize56()})});
function start56(){lockVersion56();installAvatar56();mirrorState56();installSwitch56();['renderMembers','renderQueue','renderAll','renderHeader','renderSettings'].forEach(wrapRender56);['changeProfile53','deleteProfile53'].forEach(wrapProfileAction56);try{versionMo56.observe(document.documentElement,{attributes:true,attributeFilter:['data-kokmatch-version']});const t=document.querySelector('title');if(t)versionMo56.observe(t,{childList:true,subtree:true,characterData:true})}catch{};for(const id of ['members','queue','loginBox']){const el=document.getElementById(id);if(el)identityMo56.observe(el,{childList:true,subtree:true})}watch56();canonicalize56()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start56,{once:true});else start56();
setInterval(()=>{lockVersion56();installAvatar56();mirrorState56();installSwitch56();watch56();decorateLogin56()},1000);
})();