(()=>{
'use strict';
if(window.__kokmatchV54Fix21)return;
window.__kokmatchV54Fix21=true;
window.__kokmatchProfileCanonical='21.2';
window.__kokmatchProfileFixReady='21.2';
window.__kokmatchProfilePatch='21.2';

const API='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-profile-v53';
const photos=new Map();
let loadedKey='',loading=null,seq=0,refreshing=false;

function e(v){return String(v??'').replace(/[&"<>]/g,c=>({'&':'&amp;','"':'&quot;','<':'&lt;','>':'&gt;'}[c]))}
function gid(){try{return String(currentGroupId||'')}catch{return''}}
function token(){try{return String(T||'')}catch{return''}}
function member(id){try{return id&&typeof M==='function'?M(String(id)):null}catch{return null}}
function gender(m){return String(m?.gender||'').trim()==='여'?'여':'남'}
function photo(m){return String(photos.get(String(m?.id||''))||'')}
function currentMember(){const id=String(me?.memberId||'').trim();return id?member(id):null}
function iconSvg(){return '<svg class="genderPersonIcon21" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.55-5.05 3.2-8 7.5-8s6.95 2.95 7.5 8z"></path></svg>'}
function identityHtml(m,extra=''){
 const g=gender(m),f=g==='여',src=photo(m),id=String(m?.id||'');
 if(src)return `<div class="avatar profileIdentity21 hasPhoto21 ${f?'female':'male'} ${extra}" data-member-id="${e(id)}" data-gender="${g}" data-photo="1" role="button" tabindex="0" aria-label="${e(m?.name||'회원')} 프로필 사진 크게 보기"><img src="${e(src)}" alt="${e(m?.name||'프로필')} 프로필" draggable="false"></div>`;
 return `<div class="avatar profileIdentity21 noPhoto21 ${f?'female':'male'} ${extra}" data-member-id="${e(id)}" data-gender="${g}" data-photo="0" aria-label="${f?'여성':'남성'}">${iconSvg()}</div>`;
}
function avatar21(m){return identityHtml(m)}
function installAvatar(){try{avatar=avatar21}catch{}try{window.avatar=avatar21}catch{}}

function installCss(){if(document.getElementById('v54fix21style'))return;const s=document.createElement('style');s.id='v54fix21style';s.textContent=`
.profileIdentity21{position:relative!important;display:grid!important;place-items:center!important;border-radius:50%!important;overflow:hidden!important;flex:0 0 auto!important;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
.profileIdentity21 img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important;border-radius:50%!important;pointer-events:none!important;-webkit-user-drag:none!important}
.profileIdentity21.noPhoto21{background:#eef3fb!important;border:1px solid #ccd7e8!important}
.profileIdentity21.noPhoto21.male{background:#eaf2ff!important;color:#2768e8!important;border-color:#b8cef9!important}
.profileIdentity21.noPhoto21.female{background:#fff0f4!important;color:#e34e67!important;border-color:#f4bdc9!important}
.genderPersonIcon21{width:58%!important;height:58%!important;display:block!important;fill:currentColor!important}
.memberCard>.profileIdentity21{width:50px!important;height:50px!important;min-width:50px!important}
.queueCard>.profileIdentity21{width:44px!important;height:44px!important;min-width:44px!important;margin:0!important}
.profilePreview53 .profileFallback21{width:100%!important;height:100%!important;min-height:64px!important;border-radius:50%!important;display:grid!important;place-items:center!important;overflow:hidden!important}
.profilePreview53 .profileFallback21.male{background:#eaf2ff!important;color:#2768e8!important;border:1px solid #b8cef9!important}.profilePreview53 .profileFallback21.female{background:#fff0f4!important;color:#e34e67!important;border:1px solid #f4bdc9!important}
.profilePreview53 .profileFallback21 .genderPersonIcon21{width:54%!important;height:54%!important}
#profileModal21{position:fixed;inset:0;z-index:1200;display:none;align-items:center;justify-content:center;background:#080d19ed;padding:18px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}#profileModal21.on{display:flex}.profileSheet21{position:relative;width:min(760px,96vw);max-height:94vh;display:flex;flex-direction:column;align-items:center;gap:9px}.profileImg21{display:block;max-width:94vw;max-height:84vh;width:auto;height:auto;object-fit:contain;border-radius:14px;background:#fff;box-shadow:0 18px 56px #0008;-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}.profileClose21{position:absolute;right:0;top:-6px;width:40px;height:40px;border:0;border-radius:50%;background:#fffffff2;color:#172033;font-size:25px;font-weight:900;display:grid;place-items:center}.profileName21{color:#fff;font-size:14px;font-weight:900}.profileState21{color:#dfe6f3;font-size:11px;min-height:16px}
@media(max-width:599px){.memberCard>.profileIdentity21{width:46px!important;height:46px!important;min-width:46px!important}.queueCard>.profileIdentity21{width:42px!important;height:42px!important;min-width:42px!important}}
`;document.head.appendChild(s)}

function cleanMemberLegacy(){const box=document.getElementById('members');if(!box)return;box.querySelectorAll('.v54genderText,.genderMark53').forEach(x=>x.remove())}
function decorateQueue(){const box=document.getElementById('queue');if(!box||typeof sortedQueue!=='function')return;const ids=sortedQueue();[...box.querySelectorAll('.queueCard')].forEach((card,i)=>{const m=member(ids[i]);if(!m)return;for(const x of [...card.children])if(x.classList?.contains('avatar')||x.classList?.contains('profileIdentity80')||x.classList?.contains('profileIdentity21')||x.classList?.contains('genderAvatar39')||x.classList?.contains('genderPerson54')||x.classList?.contains('genderMini39')||x.classList?.contains('v54genderText'))x.remove();card.querySelectorAll('.v54genderText').forEach(x=>x.remove());const ord=card.querySelector('.ord'),tmp=document.createElement('div');tmp.innerHTML=identityHtml(m,'queueProfile21');const el=tmp.firstElementChild;if(ord&&el)ord.insertAdjacentElement('afterend',el);else if(el)card.insertBefore(el,card.firstChild)})}

function ensureProfileControls(){const card=document.getElementById('profileCard53');if(!card)return;let inp=card.querySelector('#profileFile53');if(!inp){const holder=document.createElement('div');holder.className='profileBtns53 profileBtns21';holder.innerHTML='<label class="btn pri" for="profileFile53">사진 변경</label><input id="profileFile53" type="file" accept="image/*" style="display:none"><button id="profileDelete21" class="btn ghost" type="button">기본 사진으로</button>';card.appendChild(holder);inp=holder.querySelector('#profileFile53')}if(inp&&!inp.dataset.v21bound){inp.dataset.v21bound='1';inp.setAttribute('accept','image/*');inp.addEventListener('change',()=>window.changeProfile53(inp))}let del=card.querySelector('#profileDelete21');if(!del){const old=[...card.querySelectorAll('button')].find(b=>(b.textContent||'').includes('기본 사진으로'));if(old){old.id='profileDelete21';del=old}else{del=document.createElement('button');del.id='profileDelete21';del.type='button';del.className='btn ghost';del.textContent='기본 사진으로';(card.querySelector('.profileBtns53')||card).appendChild(del)}}if(del&&!del.dataset.v21bound){del.dataset.v21bound='1';del.addEventListener('click',()=>window.deleteProfile53())}if(!card.querySelector('#profileStatus21')){const st=document.createElement('div');st.id='profileStatus21';st.className='profileHelp53';st.style.fontWeight='700';st.style.marginTop='8px';card.appendChild(st)}}
function setStatus(text,bad=false){const st=document.getElementById('profileStatus21')||document.getElementById('profileStatus65');if(st){st.textContent=text||'';st.style.color=bad?'#b42318':'#667085'}}
function patchSettings(){const preview=document.querySelector('#profileCard53 .profilePreview53');if(!preview)return;ensureProfileControls();const m=currentMember();if(!m){preview.innerHTML='';preview.dataset.profile21='';return}const g=gender(m),f=g==='여',src=photo(m),sig=`${m.id}|${g}|${src}`;if(preview.dataset.profile21!==sig){preview.dataset.profile21=sig;preview.innerHTML=src?`<img src="${e(src)}" alt="내 프로필 사진" draggable="false">`:`<div class="profileFallback21 ${f?'female':'male'}" aria-label="${f?'여성':'남성'}">${iconSvg()}</div>`}const del=document.getElementById('profileDelete21');if(del)del.style.display=src?'':'none';const label=document.querySelector('label[for="profileFile53"]');if(label&&!(label.textContent||'').includes('중')&&!(label.textContent||'').includes('저장'))label.textContent='사진 변경'}

function refreshCurrent(){if(refreshing)return;refreshing=true;try{installAvatar();if(currentView==='members'&&typeof renderMembers==='function')renderMembers();else if(currentView==='queue'&&typeof renderQueue==='function')renderQueue();else if(currentView==='settings'&&typeof renderSettings==='function')renderSettings();else{cleanMemberLegacy();decorateQueue();patchSettings()}}catch(e){console.warn('profile21 refresh',e)}finally{refreshing=false}}
async function loadProfiles(force=false){const g=gid(),t=token(),key=g+'|'+t;if(!g||g==='__global__'||!t){loadedKey=key;photos.clear();window.__kokmatchProfilesLoaded21=g;refreshCurrent();return}if(!force&&loadedKey===key&&window.__kokmatchProfilesLoaded21===g)return;if(loading&&!force)return loading;loadedKey=key;window.__kokmatchProfilesLoaded21='';const mine=++seq;loading=(async()=>{try{const u=new URL(API);u.searchParams.set('groupId',g);u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+t},cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 조회 실패');if(mine!==seq||gid()!==g||token()!==t)return;photos.clear();for(const [id,v] of Object.entries(x?.profiles||{})){const src=String(v?.image||'');if(src)photos.set(String(id),src)}window.__kokmatchProfilesLoaded21=g;refreshCurrent()}catch(err){console.warn('profile21',err);if(mine===seq){photos.clear();window.__kokmatchProfilesLoaded21=g;refreshCurrent()}}finally{if(mine===seq)loading=null}})();return loading}
function ensureProfiles(){installAvatar();const key=gid()+'|'+token();if(key!==loadedKey||window.__kokmatchProfilesLoaded21!==gid())loadProfiles(false).catch(()=>{})}

function modal(){let m=document.getElementById('profileModal21');if(m)return m;m=document.createElement('div');m.id='profileModal21';m.innerHTML='<div class="profileSheet21"><button class="profileClose21" type="button" aria-label="닫기">×</button><img class="profileImg21" alt="프로필 사진 크게 보기" draggable="false"><div class="profileName21"></div><div class="profileState21"></div></div>';m.addEventListener('click',ev=>{if(ev.target===m)closeModal()});m.querySelector('.profileClose21')?.addEventListener('click',closeModal);document.body.appendChild(m);return m}
function closeModal(){document.getElementById('profileModal21')?.classList.remove('on');try{document.body.style.overflow=''}catch{}}
async function openModal(el){if(!el||el.dataset.photo!=='1')return;const id=String(el.dataset.memberId||''),m=member(id),thumb=String(el.querySelector('img')?.getAttribute('src')||'');if(!id||!thumb)return;const d=modal(),im=d.querySelector('.profileImg21'),nm=d.querySelector('.profileName21'),st=d.querySelector('.profileState21');im.src=thumb;nm.textContent=String(m?.name||'');st.textContent='고화질 사진 불러오는 중…';d.classList.add('on');try{document.body.style.overflow='hidden'}catch{}try{const u=new URL(API);u.searchParams.set('groupId',gid());u.searchParams.set('memberId',id);u.searchParams.set('full','1');u.searchParams.set('t',Date.now());const r=await fetch(u,{headers:{authorization:'Bearer '+token()},cache:'no-store'}),x=await r.json().catch(()=>({}));const full=String(x.fullImage||x.image||thumb);if(d.classList.contains('on'))im.src=full;st.textContent=full!==thumb?'고화질 보기':'저장된 프로필 사진 보기'}catch{st.textContent='저장된 프로필 사진 보기'}}
window.openProfilePhoto21=openModal;window.closeProfilePhoto21=closeModal;

function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>res(String(r.result||''));r.readAsDataURL(file)})}
function img(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
async function source(file){if(typeof createImageBitmap==='function')try{return await createImageBitmap(file)}catch{}return await img(await fileData(file))}
function jpeg(src,maxSide,q,crop=false){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)throw new Error('사진 크기를 확인해주세요.');const c=document.createElement('canvas'),g=c.getContext('2d');if(!g)throw new Error('사진 처리 기능을 사용할 수 없습니다.');if(crop){const z=Math.min(w,h);c.width=c.height=maxSide;g.fillStyle='#fff';g.fillRect(0,0,maxSide,maxSide);g.drawImage(src,(w-z)/2,(h-z)/2,z,z,0,0,maxSide,maxSide)}else{const sc=Math.min(1,maxSide/Math.max(w,h));c.width=Math.max(1,Math.round(w*sc));c.height=Math.max(1,Math.round(h*sc));g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(src,0,0,w,h,0,0,c.width,c.height)}return c.toDataURL('image/jpeg',q)}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token()},body:JSON.stringify(body),cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'프로필 저장 실패');return x}
window.changeProfile53=async function(input){const file=input?.files?.[0];if(!file)return;if(file.size>30*1024*1024){setStatus('원본 사진은 30MB 이하만 사용할 수 있습니다.',true);input.value='';return}try{setStatus('사진 처리 중…');const src=await source(file);let thumb=jpeg(src,256,.82,true),full=jpeg(src,2048,.9,false);for(const q of [.84,.78,.72,.66]){if(full.length<=2350000)break;full=jpeg(src,2048,q,false)}if(full.length>2450000)full=jpeg(src,1600,.78,false);if(thumb.length>220000)thumb=jpeg(src,256,.62,true);if(thumb.length>220000||full.length>2500000)throw new Error('사진 용량을 줄인 뒤 다시 선택해주세요.');await post({action:'save_profile',groupId:gid(),image:thumb,fullImage:full});try{src.close?.()}catch{}await loadProfiles(true);setStatus('프로필 사진 저장 완료')}catch(err){setStatus(err?.message||'프로필 사진 저장에 실패했습니다.',true)}finally{if(input)input.value=''}};
window.deleteProfile53=async function(){try{setStatus('프로필 사진 삭제 중…');await post({action:'delete_profile',groupId:gid()});await loadProfiles(true);setStatus('기본 프로필로 변경 완료')}catch(err){setStatus(err?.message||'프로필 삭제에 실패했습니다.',true)}};
try{changeProfile53=window.changeProfile53;deleteProfile53=window.deleteProfile53}catch{}

try{
 const rm=renderMembers;renderMembers=function(){installAvatar();const r=rm();cleanMemberLegacy();ensureProfiles();return r};
 const rq=renderQueue;renderQueue=function(){installAvatar();const r=rq();decorateQueue();ensureProfiles();return r};
 const rs=renderSettings;renderSettings=function(){installAvatar();const r=rs();patchSettings();ensureProfiles();return r};
 const ra=renderAll;renderAll=function(){installAvatar();const r=ra();cleanMemberLegacy();decorateQueue();if(currentView==='settings')patchSettings();ensureProfiles();return r};
}catch(err){console.warn('profile21 wrap',err)}

if(!window.__kokmatchProfileEvents21){window.__kokmatchProfileEvents21=true;window.addEventListener('click',ev=>{const t=ev.target instanceof Element?ev.target:null,el=t?.closest?.('.profileIdentity21');if(!el||!el.closest('#members,#queue'))return;if(el.dataset.photo==='1'){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();openModal(el)}},true);window.addEventListener('contextmenu',ev=>{const t=ev.target instanceof Element?ev.target:null;if(t?.closest?.('.profileIdentity21,#profileModal21')){ev.preventDefault();ev.stopImmediatePropagation()}},true);window.addEventListener('dragstart',ev=>{const t=ev.target instanceof Element?ev.target:null;if(t?.closest?.('.profileIdentity21,#profileModal21'))ev.preventDefault()},true);window.addEventListener('keydown',ev=>{if(ev.key==='Escape')closeModal()})}

function boot(){installCss();installAvatar();cleanMemberLegacy();decorateQueue();if(currentView==='settings')patchSettings();ensureProfiles();setTimeout(()=>{installAvatar();refreshCurrent()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();