(()=>{
if(window.__kokmatchV54Fix5)return;window.__kokmatchV54Fix5=true;
function badge5(m){if(m?.type==='guest')return '<span class="roleBadge guest45">게스트</span>';return typeof roleBadge==='function'?String(roleBadge(m)||''):''}
function genderMark5(m){const female=m?.gender==='여';return `<span class="genderMark53 ${female?'female':'male'}" title="${female?'여':'남'}" aria-label="${female?'여성':'남성'}">●</span>`}
function invite5(m){const v=m?.type==='guest'?String(m?.inviter||'').trim():'';return `<span class="inviteReserve54${v?' hasInvite54':''}">${v?`초대 ${esc(v)}`:'&nbsp;'}</span>`}
function slot5(id,i){const m=id&&typeof M==='function'?M(id):null;if(!m)return `<div class="pendingSlot emptySlot pendingEmpty54"><span>＋ 빈자리</span><span class="inviteReserve54">&nbsp;</span></div>`;return `<div class="pendingSlot pendingSlot53 pendingSlot54 clickable hasX53"><button class="pendingX" type="button" onclick="event.stopPropagation();draftRemove(${i})">×</button><div class="slotTop53"><span class="slotLabel">${i<2?'A팀':'B팀'} ${i%2+1}</span><span class="slotBadges53 slotBadges54">${genderMark5(m)}${badge5(m)}</span></div><div class="slotName slotName53"><span class="compactName53">${esc(m.name)}</span>${ageTag(m)}</div><div class="meta compactMeta53">게임 ${dailyCount(id)}회 · ${waitMins(m)}분 대기</div>${invite5(m)}</div>`}
function equalizeHeight5(grid){if(!grid)return;requestAnimationFrame(()=>{[...grid.querySelectorAll('.pendingSlot')].forEach(s=>{const mh=getComputedStyle(s).minHeight;if(mh&&mh!=='0px'&&mh!=='auto'){s.style.boxSizing='border-box';s.style.height=mh}})})}
function mirror5(){const box=typeof $==='function'?$('queue'):document.getElementById('queue');if(!box||!Array.isArray(draft))return;const comp=box.querySelector('.composer54,.composer');if(!comp)return;comp.classList.add('composer54','card','pendingCard','pendingCard53','pendingCard54');comp.classList.remove('composer');let title=comp.querySelector('.composerTitle');if(title){const head=document.createElement('div');head.className='pendingHead';head.innerHTML='<b>새 게임 편성</b>';title.replaceWith(head)}const grid=comp.querySelector('.slots,.pendingGrid');if(grid){grid.className='pendingGrid';grid.innerHTML=draft.slice(0,4).map(slot5).join('');equalizeHeight5(grid)}const acts=comp.querySelector('.composerActs,.pendingActs');if(acts)acts.className='pendingActs'}
const rq=renderQueue;renderQueue=function(){const r=rq();mirror5();return r};const ra=renderAll;renderAll=function(){const r=ra();mirror5();return r};mirror5();setTimeout(mirror5,0);
})();