(()=>{
const CUR47='4.7';let latest47=CUR47,refreshBusy47=false;
function cmp47(a,b){const A=String(a||'0').replace(/^v/i,'').split('.').map(n=>Number(n)||0),B=String(b||'0').replace(/^v/i,'').split('.').map(n=>Number(n)||0);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x!==y)return x>y?1:-1}return 0}
function style47(){if(document.getElementById('v47topStyle'))return;const s=document.createElement('style');s.id='v47topStyle';s.textContent=`#topActions37,#topActions39,#topActions40,#topActions41,#topActions42,#topActions43,#topActions44,#topActions45,#topActions46{display:none!important}#topActions47{margin-left:auto;display:flex;align-items:center;justify-content:flex-end;gap:4px;position:relative;z-index:110;pointer-events:auto;min-width:0}#currentVersion47{font-size:10px;font-weight:900;padding:6px 5px;border-radius:8px;background:rgba(255,255,255,.18);white-space:nowrap;flex:0 0 auto}#headerRefresh47{flex:0 1 auto;min-width:0;max-width:170px;min-height:30px;padding:6px 8px;font-size:10.5px;font-weight:800;line-height:1.15;white-space:normal;overflow-wrap:anywhere}#logout47{flex:0 0 64px;width:64px;min-width:64px;max-width:64px;min-height:30px;padding:6px 4px;font-size:11px;white-space:nowrap}.toprow>.logout{display:none!important}@media(max-width:380px){#currentVersion47{display:none}#headerRefresh47{max-width:135px;font-size:9.5px}#logout47{flex-basis:56px;width:56px;min-width:56px;max-width:56px;font-size:10px}}`;document.head.appendChild(s)}
function update47(){const v=document.getElementById('currentVersion47'),b=document.getElementById('headerRefresh47');if(v)v.textContent='v'+CUR47;if(!b)return;const newer=cmp47(latest47,CUR47)>0;b.textContent=refreshBusy47?'불러오는 중…':newer?`v${latest47} 업데이트 · 새로고침`:'↻ 새로고침';b.title=newer?`최신버전 v${latest47}이 있습니다. 눌러서 업데이트하세요.`:'현재 페이지를 다시 불러옵니다.'}
function ensure47(){style47();const row=document.querySelector('.toprow');if(!row)return;let a=document.getElementById('topActions47');if(!a){a=document.createElement('div');a.id='topActions47';a.innerHTML='<span id="currentVersion47">v4.7</span><button id="headerRefresh47" class="btn ghost" type="button">↻ 새로고침</button><button id="logout47" type="button">로그아웃</button>';row.appendChild(a);a.querySelector('#headerRefresh47')?.addEventListener('click',()=>refreshApp47());a.querySelector('#logout47')?.addEventListener('click',()=>logout())}update47()}
async function latestCheck47(){try{const r=await fetch('/latest-version.json?t='+Date.now(),{cache:'no-store'});if(r.ok){const x=await r.json();latest47=String(x.semanticVersion||x.label||CUR47).replace(/^v/i,'')||CUR47}}catch{}update47();return latest47}
window.refreshApp47=async function(target=''){if(refreshBusy47)return;refreshBusy47=true;update47();try{const v=String(target||await latestCheck47()||CUR47).replace(/^v/i,'');try{if(typeof saveRefreshState==='function')saveRefreshState()}catch{}location.replace('/?v='+encodeURIComponent(v)+'&refresh='+Date.now())}catch(e){refreshBusy47=false;update47();if(typeof showError==='function')showError(e);else alert(e?.message||'새로고침에 실패했습니다.')}};
window.refreshApp46=window.refreshApp47;window.refreshApp45=window.refreshApp47;window.refreshApp44=window.refreshApp47;window.refreshApp43=window.refreshApp47;window.refreshApp42=window.refreshApp47;window.refreshApp41=window.refreshApp47;window.refreshApp40=window.refreshApp47;window.refreshApp39=window.refreshApp47;window.refreshApp37=window.refreshApp47;
const renderHeaderPrev47=renderHeader;renderHeader=function(){const r=renderHeaderPrev47();ensure47();return r};
const renderSettingsPrev47=renderSettings;renderSettings=function(){const r=renderSettingsPrev47();const box=typeof $==='function'?$('settings'):null;if(box&&me?.globalAdmin===true&&String(me?.displayName||'').trim()==='박태영'){const card=[...box.querySelectorAll('.card')].find(c=>String(c.textContent||'').includes('프로그램 버전'));if(card){const m=card.querySelector('.meta');if(m)m.textContent='콕매치 v4.7 · 회원명부 경량조회 · 모바일 로딩 안정화'}}return r};
setTimeout(()=>{ensure47();latestCheck47()},0);setInterval(()=>latestCheck47(),60000);
})();
