(()=>{
if(window.__kokmatchV54Fix11)return;
window.__kokmatchV54Fix11=true;
window.__kokmatchStatsPatch='11.0';
const STATS11='https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/kokmatch-stats-v54';
let from11=businessDay11(),to11=from11,month11=from11.slice(0,7),personalOpen11=false;
let sortKey11='name',sortDir11=1,stats11=null,statsSig11='',statsSeq11=0,statsBusy11=false;

function esc11(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function businessDay11(ts=Date.now()){const d=new Date(ts-5*60*60*1000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function fmtDate11(v){const s=String(v||'');const p=s.split('-');return p.length===3?`${Number(p[1])}월 ${Number(p[2])}일`:s}
function fmtDateTime11(ms){if(!Number(ms))return '-';return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(Number(ms)))}
function fmtMin11(v){const n=Math.max(0,Number(v)||0);return n<10&&Math.abs(n-Math.round(n))>.05?n.toFixed(1):String(Math.round(n))}
function roleText11(r){return r==='manager'?'모임장':r==='organizer'?'운영진':r==='admin'?'개발자':'일반'}
function style11(){if(document.getElementById('v54fix11style'))return;const s=document.createElement('style');s.id='v54fix11style';s.textContent=`
#queue .composer54 .slotName .roleBadge,#queue .composer54 .slotName .roleShuttle50,#queue .pendingCard .slotName .roleBadge,#queue .pendingCard .slotName .roleShuttle50,#queue .pendingGrid .slotName .roleBadge,#queue .pendingGrid .slotName .roleShuttle50{display:none!important}
#queue .composer54 .slotBadges53 .roleBadge,#queue .composer54 .slotBadges54 .roleBadge,#queue .composer54 .slotBadges58 .roleBadge,#queue .pendingCard .slotBadges53 .roleBadge,#queue .pendingCard .slotBadges54 .roleBadge,#queue .pendingCard .slotBadges58 .roleBadge{display:inline-flex!important}
#stats .pollWrap90{margin-bottom:12px}
.stats11Title{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:12px 0 8px}.stats11Title h2,.stats11Title h3{margin:0}.stats11Sub{font-size:12px;color:#6f7890;line-height:1.5}
.statsRange11{display:grid;grid-template-columns:1fr auto 1fr auto;gap:6px;align-items:end;margin:9px 0}.statsRange11 label{font-size:11px;font-weight:800;color:#6f7890}.statsRange11 input{width:100%;min-width:0;box-sizing:border-box;font-size:13px;padding:8px 6px;border:1px solid #d9dfec;border-radius:9px;background:#fff}.statsRange11 .dash11{padding-bottom:9px;color:#8b94a8}.statsRange11 button{min-height:36px;white-space:nowrap}
.myStatsGrid11{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:8px 0 10px}.myStat11{background:#f5f7fc;border:1px solid #e6eaf3;border-radius:11px;padding:10px 6px;text-align:center}.myStat11 b{display:block;font-size:18px}.myStat11 span{display:block;font-size:10px;color:#70798f;margin-top:3px}
.coPlayers11{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.coPlayer11{font-size:11px;font-weight:800;padding:5px 7px;border-radius:999px;background:#eef3ff;color:#315cc3}.history11{margin-top:8px}.historyRow11{padding:9px 0;border-top:1px solid #edf0f6}.historyRow11:first-child{border-top:0}.historyHead11{display:flex;justify-content:space-between;gap:8px;font-size:12px}.historyPeople11{margin-top:3px;font-size:12px;line-height:1.45;color:#50596d}.historyMeta11{margin-top:3px;font-size:10.5px;color:#7b8498}
.personalHead11{display:flex;align-items:center;justify-content:space-between;gap:7px}.personalControls11{display:flex;align-items:center;gap:6px}.personalControls11 input{width:128px;font-size:13px;padding:7px;border:1px solid #d9dfec;border-radius:9px}.personalToggle11{width:100%;display:flex;justify-content:space-between;align-items:center;margin-top:8px}
.statsTableWrap11{overflow-x:auto;-webkit-overflow-scrolling:touch;margin-top:8px;border:1px solid #e4e8f1;border-radius:11px}.statsTable11{width:100%;min-width:570px;border-collapse:collapse;font-size:12px}.statsTable11 th{position:sticky;top:0;background:#f4f6fb;padding:9px 7px;border-bottom:1px solid #dfe4ee;white-space:nowrap;cursor:pointer;user-select:none}.statsTable11 td{padding:9px 7px;border-bottom:1px solid #edf0f5;text-align:center;white-space:nowrap}.statsTable11 tr:last-child td{border-bottom:0}.statsTable11 th:first-child,.statsTable11 td:first-child{text-align:left}.nameBtn11{border:0;background:none;padding:0;color:#2453d4;font-weight:900;text-decoration:underline;text-underline-offset:2px}.statZero11{color:#d92c3a!important;font-weight:950!important}.sortMark11{font-size:9px;margin-left:2px;color:#2453d4}.statsLoading11{padding:16px;text-align:center;color:#70798f}.statsError11{padding:10px;border-radius:10px;background:#fff2f3;color:#b72635;font-size:12px;line-height:1.5}.archiveNote11{margin-top:8px;padding:8px 10px;border-radius:9px;background:#fff8e6;color:#7c6020;font-size:11px;line-height:1.55}
.detailGame11{padding:10px 0;border-bottom:1px solid #edf0f5}.detailGame11:last-child{border-bottom:0}.detailGame11 b{font-size:13px}.detailGame11 .meta{margin-top:3px;line-height:1.5}.detailSummary11{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:9px 0}.detailSummary11>div{text-align:center;padding:8px 5px;border-radius:9px;background:#f4f6fb}.detailSummary11 b{display:block;font-size:16px}.detailSummary11 span{font-size:10px;color:#737c90}
@media(max-width:420px){.statsRange11{grid-template-columns:1fr 10px 1fr}.statsRange11 button{grid-column:1/4}.myStatsGrid11{gap:5px}.myStat11{padding:9px 3px}.myStat11 b{font-size:16px}.personalHead11{align-items:flex-start;flex-direction:column}.personalControls11{width:100%}.personalControls11 input{flex:1;width:auto}}
`;document.head.appendChild(s)}

function cleanupComposer11(){style11();const box=document.getElementById('queue');if(!box)return;box.querySelectorAll('.composer54 .slotName,.pendingCard .slotName,.pendingGrid .slotName').forEach(n=>{n.querySelectorAll('.roleBadge,.roleShuttle50').forEach(x=>x.remove());[...n.children].forEach(x=>{if(x.classList?.contains('compactName53')||x.classList?.contains('tag')||x.classList?.contains('nameGender58'))return;const t=String(x.textContent||'').trim();if(/^(일반|일반회원|총관리자|모임장|모임관리자|운영진|게임편성자|임시편성자)$/.test(t))x.remove()})})}
let qraf11=0;function scheduleComposer11(){if(qraf11)return;qraf11=requestAnimationFrame(()=>{qraf11=0;cleanupComposer11()})}

function pollNode11(box){return box?.querySelector('.pollWrap90')||null}
function mine11(data=stats11){const id=String(data?.selfMemberId||me?.memberId||'');return (data?.members||[]).find(m=>String(m.id)===id)||null}
function gamesFor11(data,id,kind='range'){const rows=kind==='month'?(data?.monthGames||[]):(data?.rangeGames||[]);return rows.filter(g=>Array.isArray(g.players)&&g.players.map(String).includes(String(id)))}
function names11(g){const ps=Array.isArray(g?.players)?g.players.map(String):[],ns=Array.isArray(g?.playerNames)?g.playerNames:[];return ps.map((id,i)=>String(ns[i]||stats11?.members?.find(m=>String(m.id)===id)?.name||'삭제회원'))}
function otherNames11(g,id){const ps=Array.isArray(g?.players)?g.players.map(String):[],ns=names11(g);return ps.map((p,i)=>p===String(id)?'':ns[i]).filter(Boolean)}
function rangeWait11(data,id,games){const vals=[];for(const g of games){const n=Number(g?.waitMsByPlayer?.[String(id)]);if(Number.isFinite(n)&&n>=0)vals.push(n)}const member=(data?.members||[]).find(m=>String(m.id)===String(id));if(String(data?.from||'')===String(data?.today||'')&&String(data?.to||'')===String(data?.today||'')&&member&&Number(member.waitTotalMs)>=0&&games.length){return Number(member.waitTotalMs)/games.length}return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}
function duration11(g){const d=Number(g?.durationMin);if(d>0)return d;const a=Number(g?.startedAt),b=Number(g?.endedAt);return a&&b?Math.max(0,(b-a)/60000):0}
function historyHtml11(games,id){if(!games.length)return '<div class="empty">선택한 기간에 완료한 경기가 없습니다.</div>';return `<div class="history11">${games.slice().reverse().map(g=>`<div class="historyRow11"><div class="historyHead11"><b>${fmtDateTime11(g.startedAt)} 시작</b><b>${fmtMin11(duration11(g))}분</b></div><div class="historyPeople11">함께한 사람 · ${otherNames11(g,id).map(esc11).join(' · ')||'-'}</div><div class="historyMeta11">${esc11(g.courtName||((g.court||'')?`${g.court}코트`:''))}${g.autoEnded?' · 자동종료':''}</div></div>`).join('')}</div>`}
function myCard11(data){const m=mine11(data),id=String(m?.id||data?.selfMemberId||'');if(!id)return `<div class="card"><div class="stats11Title"><h3>내 기록</h3></div><div class="empty">현재 모임의 내 회원정보를 찾지 못했습니다.</div></div>`;const games=gamesFor11(data,id,'range'),total=games.reduce((a,g)=>a+duration11(g),0),wait=rangeWait11(data,id,games),cos=[...new Set(games.flatMap(g=>otherNames11(g,id)))];return `<div class="card" id="myStatsCard11"><div class="stats11Title"><div><h3>내 기록</h3><div class="stats11Sub">기본은 오늘 기록입니다.</div></div></div><div class="statsRange11"><label>시작일<input id="statsFrom11" type="date" value="${esc11(from11)}"></label><span class="dash11">~</span><label>종료일<input id="statsTo11" type="date" value="${esc11(to11)}"></label><button class="btn pri" id="statsRangeBtn11" type="button">조회</button></div><div class="myStatsGrid11"><div class="myStat11"><b>${games.length}</b><span>완료 게임</span></div><div class="myStat11"><b>${fmtMin11(total)}분</b><span>총 게임시간</span></div><div class="myStat11"><b>${fmtMin11(wait/60000)}분</b><span>평균 게임대기</span></div></div><div><b style="font-size:12px">같이 게임한 사람</b><div class="coPlayers11">${cos.length?cos.map(n=>`<span class="coPlayer11">${esc11(n)}</span>`).join(''):'<span class="stats11Sub">없음</span>'}</div></div>${historyHtml11(games,id)}</div>`}
function attendance11(m,month,data){const h=m?.attendanceHistory&&typeof m.attendanceHistory==='object'?Number(m.attendanceHistory[month]):NaN;if(Number.isFinite(h))return Math.max(0,h);if(String(m?.attendanceMonth||'')===month)return Math.max(0,Number(m?.attendanceCount)||0);const b=(data?.baselines||[]).find(x=>String(x.memberId)===String(m.id));return Math.max(0,Number(b?.attendanceCount)||0)}
function monthlyCount11(m,data){const b=(data?.baselines||[]).find(x=>String(x.memberId)===String(m.id));const games=gamesFor11(data,m.id,'month');if(b){const after=games.filter(g=>Number(g.endedAt)>Number(b.capturedAtMs||0)).length;return Math.max(0,Number(b.gameCount)||0)+after}return games.length}
function rows11(data){return (data?.members||[]).filter(m=>String(m.type||'member')!=='guest').map(m=>{const attendance=attendance11(m,month11,data),games=monthlyCount11(m,data),avg=attendance?games/attendance:0;return {m,attendance,games,avg}})}
function val11(r,k){if(k==='name')return String(r.m.name||'');if(k==='age')return Number(r.m.age)||0;if(k==='cls')return String(r.m.cls||'Z');if(k==='attendance')return r.attendance;if(k==='games')return r.games;if(k==='avg')return r.avg;return ''}
function sortedRows11(data){const arr=rows11(data);return arr.sort((a,b)=>{const A=val11(a,sortKey11),B=val11(b,sortKey11);let c=0;if(typeof A==='number'&&typeof B==='number')c=A-B;else c=String(A).localeCompare(String(B),'ko',{numeric:true});if(!c)c=String(a.m.name||'').localeCompare(String(b.m.name||''),'ko');return c*sortDir11})}
function mark11(k){return sortKey11===k?`<span class="sortMark11">${sortDir11>0?'▲':'▼'}</span>`:''}
function z11(n,text){return `<td class="${Number(n)===0?'statZero11':''}">${text}</td>`}
function table11(data){const rs=sortedRows11(data);return `<div class="statsTableWrap11"><table class="statsTable11"><thead><tr><th data-sort11="name">이름${mark11('name')}</th><th data-sort11="age">나이${mark11('age')}</th><th data-sort11="cls">급수${mark11('cls')}</th><th data-sort11="attendance">출석 횟수${mark11('attendance')}</th><th data-sort11="games">게임횟수${mark11('games')}</th><th data-sort11="avg">평균 게임수${mark11('avg')}</th></tr></thead><tbody>${rs.map(r=>`<tr><td><button type="button" class="nameBtn11" data-member11="${esc11(r.m.id)}">${esc11(r.m.name)}</button></td><td>${esc11(r.m.age||'-')}</td><td>${esc11(r.m.cls||'-')}</td>${z11(r.attendance,`${r.attendance}회`)}${z11(r.games,`${r.games}회`)}${z11(r.avg,r.avg?`${r.avg.toFixed(1)}회`:'0회')}</tr>`).join('')||'<tr><td colspan="6">회원 기록이 없습니다.</td></tr>'}</tbody></table></div>`}
function personalCard11(data){return `<div class="card" id="personalStats11"><div class="personalHead11"><div><h3 style="margin:0">개인별 기록</h3><div class="stats11Sub">월간 출석과 게임 기록</div></div><div class="personalControls11"><input id="statsMonth11" type="month" value="${esc11(month11)}"></div></div><button id="personalToggle11" type="button" class="btn ghost personalToggle11"><b>${Number(month11.slice(5))}월 월간기록 ${personalOpen11?'접기':'보기'}</b><span>${personalOpen11?'▲':'▼'}</span></button>${personalOpen11?table11(data):''}</div>`}
function loadingCard11(){return `<div class="card"><div class="stats11Title"><h3>내 기록</h3></div><div class="statsLoading11">기록 불러오는 중…</div></div><div class="card"><h3 style="margin:0">개인별 기록</h3><div class="statsLoading11">월간 기록 불러오는 중…</div></div>`}
function errorCards11(msg){return `<div class="card"><div class="statsError11">${esc11(msg||'통계 기록을 불러오지 못했습니다.')}</div></div>`}
function bindStats11(box){box.querySelector('#statsRangeBtn11')?.addEventListener('click',()=>{const f=String(box.querySelector('#statsFrom11')?.value||''),t=String(box.querySelector('#statsTo11')?.value||'');if(!f||!t||f>t)return alert('조회 기간을 확인해주세요.');from11=f;to11=t;loadStats11(true)});box.querySelector('#personalToggle11')?.addEventListener('click',()=>{personalOpen11=!personalOpen11;paintStats11()});box.querySelector('#statsMonth11')?.addEventListener('change',e=>{const v=String(e.target?.value||'');if(!/^\d{4}-\d{2}$/.test(v))return;month11=v;personalOpen11=true;loadStats11(true)});box.querySelectorAll('[data-sort11]').forEach(h=>h.addEventListener('click',()=>{const k=String(h.dataset.sort11||'name');if(sortKey11===k)sortDir11*=-1;else{sortKey11=k;sortDir11=1}paintStats11()}));box.querySelectorAll('[data-member11]').forEach(b=>b.addEventListener('click',()=>openMemberDetail11(String(b.dataset.member11||''))))}
function paintStats11(){style11();const box=document.getElementById('stats');if(!box)return;const poll=pollNode11(box);if(poll)poll.remove();const header=`<div class="stats11Title"><div><h2>통계</h2><div class="stats11Sub">경기와 출석 기록</div></div></div>`;let body;if(statsBusy11&&!stats11)body=loadingCard11();else if(stats11?.error)body=errorCards11(stats11.error);else if(stats11)body=myCard11(stats11)+personalCard11(stats11);else body=loadingCard11();box.innerHTML=header+body;if(poll)box.insertBefore(poll,box.firstChild);bindStats11(box)}
async function reqStats11(){const u=new URL(STATS11);u.searchParams.set('groupId',String(currentGroupId||''));u.searchParams.set('from',from11);u.searchParams.set('to',to11);u.searchParams.set('month',month11);u.searchParams.set('t',String(Date.now()));const r=await fetch(u,{headers:{authorization:'Bearer '+T},cache:'no-store',credentials:'omit'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`통계 조회 실패 (${r.status})`);return x}
async function loadStats11(force=false){if(!T||!currentGroupId||currentGroupId==='__global__')return;const sig=[currentGroupId,from11,to11,month11].join('|');if(!force&&stats11&&statsSig11===sig){paintStats11();return}const seq=++statsSeq11;statsBusy11=true;paintStats11();try{const x=await reqStats11();if(seq!==statsSeq11)return;stats11=x;statsSig11=sig}catch(e){if(seq!==statsSeq11)return;stats11={error:e?.message||'통계 기록을 불러오지 못했습니다.'};statsSig11=sig}finally{if(seq===statsSeq11){statsBusy11=false;paintStats11()}}}
function openMemberDetail11(id){if(!stats11||stats11.error)return;const m=(stats11.members||[]).find(x=>String(x.id)===String(id));if(!m)return;const games=gamesFor11(stats11,id,'month').slice().sort((a,b)=>Number(b.startedAt)-Number(a.startedAt)),total=games.reduce((a,g)=>a+duration11(g),0),agg=monthlyCount11(m,stats11),attendance=attendance11(m,month11,stats11),missing=Math.max(0,agg-games.length);const detail=games.map(g=>`<div class="detailGame11"><b>${fmtDateTime11(g.startedAt)} 시작 · ${fmtMin11(duration11(g))}분</b><div class="meta">같이 게임 · ${otherNames11(g,id).map(esc11).join(' · ')||'-'}</div><div class="meta">${esc11(g.courtName||((g.court||'')?`${g.court}코트`:''))}${g.autoEnded?' · 자동종료':''}</div></div>`).join('')||'<div class="empty">저장된 상세 경기기록이 없습니다.</div>';const note=missing?`<div class="archiveNote11">기록 보존 기능 적용 이전 경기 ${missing}건은 월간 총 게임수에는 포함되지만, 시작시간과 함께한 사람 등의 상세정보는 남아 있지 않아 표시할 수 없습니다.</div>`:'';const html=`<h3>${esc11(m.name)} · ${Number(month11.slice(5))}월 기록</h3><div class="meta">${esc11(m.age||'-')}세 · ${esc11(m.cls||'-')}급 · ${esc11(roleText11(m.role))}</div><div class="detailSummary11"><div><b>${attendance}</b><span>출석</span></div><div><b>${agg}</b><span>게임</span></div><div><b>${attendance?(agg/attendance).toFixed(1):'0'}</b><span>평균 게임</span></div></div>${note}${detail}<button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">닫기</button>`;if(typeof openModal==='function')openModal(html)}
window.openMemberDetail11=openMemberDetail11;

const prevStats11=renderStats;renderStats=function(){const r=prevStats11();paintStats11();if(currentView==='stats')queueMicrotask(()=>loadStats11(false));return r};
const prevQueue11=renderQueue;renderQueue=function(){const r=prevQueue11();scheduleComposer11();return r};
const prevAll11=renderAll;renderAll=function(){const oldG=String(currentGroupId||'');const r=prevAll11();scheduleComposer11();if(String(currentGroupId||'')!==oldG){stats11=null;statsSig11=''}return r};
const prevGo11=goView;goView=function(id){const r=prevGo11(id);if(id==='stats'){renderStats();loadStats11(false)}return r};
try{window.renderStats=renderStats;window.renderQueue=renderQueue;window.renderAll=renderAll;window.goView=goView}catch{}
const mo11=new MutationObserver(scheduleComposer11);function boot11(){style11();const q=document.getElementById('queue');if(q)mo11.observe(q,{childList:true,subtree:true});scheduleComposer11();if(me&&currentView==='stats'){renderStats();loadStats11(true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot11,{once:true});else boot11();
})();