const GRADE={S:6,A:5,B:4,C:3,D:2,E:1};
const HOUR=3600000;
const DAY_FMT=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'});

export function calendarDay(now=Date.now()){return DAY_FMT.format(new Date(now))}
export function businessDay(now=Date.now()){return DAY_FMT.format(new Date(now-5*HOUR))}
function startBusinessFromDay(day){const [y,m,d]=String(day).split('-').map(Number);return Date.UTC(y,m-1,d)-4*HOUR}
export function startBusinessMs(now=Date.now()){return startBusinessFromDay(businessDay(now))}
export function currentWaitMin(m,now=Date.now()){if(!m||!['waiting','matched'].includes(String(m.state||'')))return 0;const joined=Number(m.joinedAt)||0;if(!joined)return 0;const start=startBusinessMs(now);return Math.max(0,Math.floor((now-Math.max(joined,start))/60000))}
export function totalWaitMin(m,now=Date.now()){if(!m)return 0;const biz=businessDay(now),start=startBusinessFromDay(biz);let ms=String(m.waitDay||'')===biz?Math.max(0,Number(m.waitTotalMs)||0):0;const joined=Number(m.joinedAt)||0;if(joined&&['waiting','matched'].includes(String(m.state||'')))ms+=Math.max(0,now-Math.max(joined,start));return Math.max(0,Math.floor(ms/60000))}
function gameIsTodayWithStart(g,start){const t=Number(g?.endedAt||g?.startedAt||g?.matchedAt)||0;return !t||t>=start}
export function gameCountToday(id,s,now=Date.now()){id=String(id||'');let n=0;const start=startBusinessMs(now);for(const h of Array.isArray(s?.history)?s.history:[]){if(!gameIsTodayWithStart(h,start))continue;if(Array.isArray(h?.players)&&h.players.map(String).includes(id))n++}return n}
function keyOf(a,b){a=String(a||'');b=String(b||'');return a<b?a+'|'+b:b+'|'+a}
export function pairCountToday(a,b,s,now=Date.now()){a=String(a||'');b=String(b||'');let n=0;const start=startBusinessMs(now);for(const h of Array.isArray(s?.history)?s.history:[]){if(!gameIsTodayWithStart(h,start)||!Array.isArray(h?.players))continue;const p=h.players.map(String);if(p.includes(a)&&p.includes(b))n++}return n}
export function adjustedSkill(m){const cls=String(m?.cls||'').toUpperCase();if(String(m?.gender||'')==='여'&&cls==='C')return GRADE.D;return GRADE[cls]||1}
function partnerDayValidKnown(day,cal,biz){const d=String(day||'');return !!d&&(d===cal||d===biz)}
function partnerDayValid(day,now){return partnerDayValidKnown(day,calendarDay(now),businessDay(now))}
export function isPartnerPair(a,b,byId,now=Date.now()){a=String(a||'');b=String(b||'');const ma=byId.get(a),mb=byId.get(b);if(!ma||!mb)return false;return (partnerDayValid(ma.partnerDay,now)&&String(ma.partnerId||'')===b)||(partnerDayValid(mb.partnerDay,now)&&String(mb.partnerId||'')===a)}
function buildFastContext(s,queue,byId,now){const biz=businessDay(now),cal=calendarDay(now),start=startBusinessFromDay(biz);const gameCounts=new Map(queue.map(id=>[id,0])),pairCounts=new Map();for(const h of Array.isArray(s?.history)?s.history:[]){if(!gameIsTodayWithStart(h,start)||!Array.isArray(h?.players))continue;const players=[...new Set(h.players.map(String))];for(const id of players)if(gameCounts.has(id))gameCounts.set(id,(gameCounts.get(id)||0)+1);for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const k=keyOf(players[i],players[j]);pairCounts.set(k,(pairCounts.get(k)||0)+1)}}const infos=new Map();for(const id of queue){const m=byId.get(id),live=['waiting','matched'].includes(String(m?.state||'')),joined=Number(m?.joinedAt)||0,liveMs=live&&joined?Math.max(0,now-Math.max(joined,start)):0,current=Math.max(0,Math.floor(liveMs/60000));let totalMs=String(m?.waitDay||'')===biz?Math.max(0,Number(m?.waitTotalMs)||0):0;totalMs+=liveMs;const total=Math.max(0,Math.floor(totalMs/60000)),burden=current+total;infos.set(id,{m,current,total,burden,band:Math.floor(burden/5),game:gameCounts.get(id)||0,skill:adjustedSkill(m),female:String(m?.gender||'')==='여'})}const partnerSet=new Set(),queueSet=new Set(queue);for(const id of queue){const m=byId.get(id),pid=String(m?.partnerId||'');if(pid&&queueSet.has(pid)&&partnerDayValidKnown(m?.partnerDay,cal,biz))partnerSet.add(keyOf(id,pid))}return {infos,pairCounts,partnerSet}}
function pairingMetricsFast(ids,info,partnerIndexPairs){const pairings=[[[0,1],[2,3]],[[0,2],[1,3]],[[0,3],[1,2]]],totalFemale=info.reduce((n,x)=>n+(x.female?1:0),0);let best=null;for(const teams of pairings){const [t1,t2]=teams;let splitPartners=0;for(const [i,j] of partnerIndexPairs){const together=(t1.includes(i)&&t1.includes(j))||(t2.includes(i)&&t2.includes(j));if(!together)splitPartners++}const power1=info[t1[0]].skill+info[t1[1]].skill,power2=info[t2[0]].skill+info[t2[1]].skill,f1=(info[t1[0]].female?1:0)+(info[t1[1]].female?1:0),f2=(info[t2[0]].female?1:0)+(info[t2[1]].female?1:0),balance=Math.abs(power1-power2)*10+Math.abs(f1-f2)*4+Math.abs(totalFemale-2)*2,row={teams,splitPartners,balance,power:[power1,power2],female:[f1,f2]};if(!best||row.splitPartners<best.splitPartners||(row.splitPartners===best.splitPartners&&row.balance<best.balance))best=row}return best}
function vecCompare(a,b){const n=Math.max(a.length,b.length);for(let i=0;i<n;i++){const av=Number(a[i]??0),bv=Number(b[i]??0);if(av!==bv)return av-bv}return 0}
function selectionMetricsFast(ids,ctx){const info=ids.map(id=>ctx.infos.get(id)),waits=info.map(x=>({current:x.current,total:x.total})),waitVector=info.map(x=>x.band).sort((a,b)=>b-a),waitExactVector=info.map(x=>x.burden).sort((a,b)=>b-a),games=info.map(x=>x.game),gameTotal=games.reduce((a,b)=>a+b,0),gameSpread=Math.max(...games)-Math.min(...games),partnerIndexPairs=[];let hardRepeat=0,repeatTotal=0;for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=keyOf(ids[i],ids[j]);if(ctx.partnerSet.has(k)){partnerIndexPairs.push([i,j]);continue}const c=ctx.pairCounts.get(k)||0;repeatTotal+=c;if(c>=3)hardRepeat++}const pairing=pairingMetricsFast(ids,info,partnerIndexPairs);return {waitVector,waitExactVector,gameTotal,gameSpread,partners:partnerIndexPairs.length,balance:pairing?.balance??999,splitPartners:pairing?.splitPartners??99,hardRepeat,repeatTotal,pairing,waits,games}}
function better(a,b){if(!b)return true;const A=a.metrics,B=b.metrics;let v=vecCompare(A.waitVector,B.waitVector);if(v!==0)return v>0;if(A.gameTotal!==B.gameTotal)return A.gameTotal<B.gameTotal;if(A.gameSpread!==B.gameSpread)return A.gameSpread<B.gameSpread;if(A.partners!==B.partners)return A.partners>B.partners;if(A.splitPartners!==B.splitPartners)return A.splitPartners<B.splitPartners;if(A.balance!==B.balance)return A.balance<B.balance;if(A.hardRepeat!==B.hardRepeat)return A.hardRepeat<B.hardRepeat;if(A.repeatTotal!==B.repeatTotal)return A.repeatTotal<B.repeatTotal;v=vecCompare(A.waitExactVector,B.waitExactVector);if(v!==0)return v>0;return a.ids.join('|')<b.ids.join('|')}
export function bestFour(s,now=Date.now()){const members=Array.isArray(s?.members)?s.members:[],byId=new Map(members.map(m=>[String(m.id),m]));let queue=(Array.isArray(s?.queue)?s.queue:[]).map(String).filter(id=>byId.has(id)&&String(byId.get(id)?.state||'')==='waiting');if(queue.length<4)return null;const ctx=buildFastContext(s,queue,byId,now);queue.sort((a,b)=>{const A=ctx.infos.get(a),B=ctx.infos.get(b);if(A.band!==B.band)return B.band-A.band;if(A.game!==B.game)return A.game-B.game;if(A.burden!==B.burden)return B.burden-A.burden;return String(A.m?.name||a).localeCompare(String(B.m?.name||b),'ko')});const pool=queue.slice(0,Math.min(24,queue.length));let best=null;for(let a=0;a<pool.length-3;a++)for(let b=a+1;b<pool.length-2;b++)for(let c=b+1;c<pool.length-1;c++)for(let d=c+1;d<pool.length;d++){const ids=[pool[a],pool[b],pool[c],pool[d]],metrics=selectionMetricsFast(ids,ctx),row={ids,metrics};if(better(row,best))best=row}if(!best)return null;const p=best.metrics.pairing.teams,players=[best.ids[p[0][0]],best.ids[p[0][1]],best.ids[p[1][0]],best.ids[p[1][1]]];return {players,metrics:{...best.metrics,pairing:undefined}}}
