import fs from 'node:fs';
import { chromium } from 'playwright';
const latest=JSON.parse(fs.readFileSync('latest-version.json','utf8'));const VERSION=String(latest.semanticVersion||'').replace(/^v/,'');
const fmt=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d),today=fmt(new Date()),yesterday=fmt(new Date(Date.now()-86400000)),month=today.slice(0,7);
const state={courtCount:8,courtNames:Array.from({length:8},(_,i)=>`${i+1}코트`),queue:[],pendingGames:[],games:[],history:[],pairCounts:{},members:[{id:'mgr',name:'관리자',year:1985,gender:'남',age:'40',cls:'B',type:'member',role:'manager',state:'out',totalGames:4,attendanceMonth:month,attendanceCount:2,attendanceHistory:{[month]:2}},{id:'m1',name:'수정대상',year:1990,gender:'남',age:'30',cls:'C',type:'member',role:'member',state:'out',totalGames:3,attendanceMonth:month,attendanceCount:1,attendanceHistory:{[month]:1}},{id:'m0',name:'미출석회원',year:1995,gender:'여',age:'30',cls:'D',type:'member',role:'member',state:'out',totalGames:0,attendanceMonth:month,attendanceCount:0,attendanceHistory:{[month]:0}}],attendancePolls:[{id:'p1',date:today,time:'18:30',endTime:'20:30',location:'QA 코트',title:'QA 투표',createdBy:'관리자',memberVotes:{},guestEntries:[],totalLimit:0,guestLimit:0,guestClosed:false}]};
const clone=()=>JSON.parse(JSON.stringify(state));
const game=(id,day,players,durationMin,wait)=>({gameId:id,businessDay:day,startedAt:1,endedAt:2,matchedAt:1,durationMin,court:1,courtName:'1코트',players,playerNames:players.map(id=>state.members.find(m=>m.id===id)?.name||id),waitMsByPlayer:wait,autoEnded:false});
const monthGames=[game('g-y',yesterday,['mgr'],20,{mgr:300000}),game('g-1',today,['mgr','m1'],30,{mgr:600000,m1:1200000}),game('g-2',today,['m1'],25,{m1:1800000})];
let memberSaveCalls=0,lastMemberSave=null,lastStatsQuery=null;
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e?.stack||e)));
await page.route('https://wjelumpbjklfrdjxbesj.supabase.co/functions/v1/**',async route=>{const req=route.request(),url=new URL(req.url());let body={};try{body=JSON.parse(req.postData()||'{}')}catch{}
 if(url.pathname.endsWith('/kokmatch-v60-api')){if(body.op==='member_save'){memberSaveCalls++;lastMemberSave=body;const id=String(body.memberId||'m-new');let m=state.members.find(x=>String(x.id)===id);if(!m){m={id,state:'out',totalGames:0};state.members.push(m)}Object.assign(m,{name:body.name,year:body.year,gender:body.gender,age:'30',cls:body.cls,type:body.type,role:body.role,inviter:body.inviter||''});if(body.compact===true)return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,member:JSON.parse(JSON.stringify(m)),group:{groupId:'qa',name:'QA'}})});}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,data:clone(),group:{groupId:'qa',name:'QA'}})});}
 if(url.pathname.endsWith('/kokmatch-v21-api'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,data:clone()})});
 if(url.pathname.endsWith('/kokmatch-stats-v54')){const from=url.searchParams.get('from')||today,to=url.searchParams.get('to')||from,mon=url.searchParams.get('month')||month;lastStatsQuery={from,to,month:mon};const rangeGames=monthGames.filter(g=>g.businessDay>=from&&g.businessDay<=to);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,groupId:'qa',today,from,to,month:mon,selfMemberId:'mgr',members:clone().members,rangeGames,monthGames:mon===month?monthGames:[],baselines:[]})});}
 if(url.pathname.includes('profile'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({profiles:{},success:true})});return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,data:clone(),profiles:{},groups:[],group:{groupId:'qa',name:'QA'}})});});
try{await page.goto('http://127.0.0.1:4173/?qa=v628',{waitUntil:'networkidle'});await page.waitForFunction(v=>window.__kokmatchVersionLock===v&&typeof window.renderAll==='function',VERSION,{timeout:15000});await page.evaluate(({state})=>{T='qa-token';currentGroupId='qa';currentView='members';S=JSON.parse(JSON.stringify(state));window.S=S;me={memberId:'mgr',displayName:'관리자',role:'manager',globalAdmin:false,tempOrganizer:false,groupId:'qa'};group={groupId:'qa',name:'QA 모임'};groups=[];normalizeClient();renderAll();document.getElementById('login')?.classList.add('hide')},{state:clone()});
 const edit=page.locator('#members .memberCard[data-member-id22="m1"] .memberBtns button').filter({hasText:'수정'}).first();await edit.click();await page.waitForSelector('#memberEditorV615');await page.fill('#v618Name','저장속도QA');await page.locator('#v618Save').click();await page.waitForSelector('#memberEditorV615',{state:'detached',timeout:5000});if(memberSaveCalls!==1||lastMemberSave?.compact!==true)throw new Error('compact member save regression');
 await page.evaluate(()=>goView('stats'));await page.waitForSelector('.pollWrap623');await page.waitForSelector('.statsMonthly628');await page.waitForFunction(()=>document.querySelector('.statsDateGrid628 .stat b')?.textContent==='2');
 const pollSelectedBefore=await page.locator('.pollDay623.selected span').textContent();const todayCompleted=await page.locator('.statsDateGrid628 .stat').nth(0).locator('b').textContent();const avgToday=await page.locator('.statsDateGrid628 .stat').nth(3).locator('b').textContent();if(todayCompleted?.trim()!=='2'||avgToday?.trim()!=='20분')throw new Error('today stats/average wait wrong: '+todayCompleted+' / '+avgToday);
 await page.locator('#statsDateInput628').evaluate((el,val)=>{el.value=val;el.dispatchEvent(new Event('change',{bubbles:true}))},yesterday);await page.waitForFunction(d=>window.__qaLastStatsDate===d,yesterday,{timeout:5000});await page.waitForFunction(()=>document.querySelector('.statsDateGrid628 .stat b')?.textContent==='1');if(lastStatsQuery?.from!==yesterday||lastStatsQuery?.to!==yesterday)throw new Error('independent stats date query wrong');const avgYesterday=await page.locator('.statsDateGrid628 .stat').nth(3).locator('b').textContent();if(avgYesterday?.trim()!=='5분')throw new Error('yesterday avg wait wrong: '+avgYesterday);const pollSelectedAfter=await page.locator('.pollDay623.selected span').textContent();if(pollSelectedAfter!==pollSelectedBefore)throw new Error('poll calendar changed when stats date changed');
 const headers=await page.locator('.statsMonthlyTable628 thead').textContent();for(const t of ['이름','년생','나이급수','역할','출석','게임'])if(!headers.includes(t))throw new Error('monthly header missing '+t);const fit=await page.evaluate(()=>{const w=document.querySelector('.statsTableWrap628'),t=document.querySelector('.statsMonthlyTable628'),p=document.querySelector('.statsMonthPicker628'),bs=p?[...p.querySelectorAll('button')]:[],inp=p?.querySelector('input'),r0=bs[0]?.getBoundingClientRect(),ri=inp?.getBoundingClientRect(),r1=bs[1]?.getBoundingClientRect();return{wrap:w?.clientWidth||0,scroll:w?.scrollWidth||0,table:t?.getBoundingClientRect().width||0,b0:r0?.width||0,b1:r1?.width||0,gap0:r0&&ri?ri.left-r0.right:0,gap1:r1&&ri?r1.left-ri.right:0}});if(fit.scroll>fit.wrap+1||fit.table>fit.wrap+1)throw new Error('monthly table horizontally overflows: '+JSON.stringify(fit));if(fit.b0<40||fit.b1<40||fit.gap0<10||fit.gap1<10)throw new Error('month arrow spacing too tight: '+JSON.stringify(fit));
 let rows=page.locator('.statsMonthlyTable628 tbody tr');if(await rows.count()!==3)throw new Error('monthly rows mismatch');await page.locator('button[data-stats-sort628="attendance"]').click();let first=await rows.first().locator('td').first().textContent();if(!first?.includes('미출석회원'))throw new Error('ascending sort failed');await page.locator('button[data-stats-sort628="attendance"]').click();first=await rows.first().locator('td').first().textContent();if(!first?.includes('관리자'))throw new Error('descending sort failed');await page.locator('#statsZeroOnly628').click();rows=page.locator('.statsMonthlyTable628 tbody tr');if(await rows.count()!==1||!(await rows.first().textContent())?.includes('미출석회원'))throw new Error('zero attendance filter failed');if(pageErrors.length)throw new Error('page errors: '+pageErrors.join(' | '));console.log(`PASS v6.28 stats QA`);console.log('PASS independent date picker / poll calendar decoupled');console.log('PASS average game wait time');console.log('PASS monthly table fits 390px without horizontal scroll');console.log('PASS month arrows >=40px with >=10px spacing');console.log('PASS sorting / zero-attendance filter / compact member save');}finally{await browser.close();}
